### ISSUE TITLE
Styles in giu

### ISSUE THREAD

**Issue by bezrazli4n0** [AllenDang/giu#1]
Hi, how can i apply styles to widgets?

**Comment by AllenDang** [comment]
@bezrazli4n0 
You can use following APIs to apply styles at anytime.

imgui.PushStyleColor
imgui.PushStyleVarFloat
imgui.PushStyleVarVec2

Here you can find a complete list of StyleIDs
[Style.go](https://github.com/AllenDang/giu/blob/master/imgui/Style.go)

**Comment by bezrazli4n0** [comment]
> @bezrazli4n0
> You can use following APIs to apply styles at anytime.
> 
> imgui.PushStyleColor
> imgui.PushStyleVarFloat
> imgui.PushStyleVarVec2
> 
> Here you can find a complete list of StyleIDs
> [Style.go](https://github.com/AllenDang/giu/blob/master/imgui/Style.go)
> 
> Just remember to invole imgui.PopStyleVar after you push them in.

Ok, but how to apply style only for one widget in layout?, for example:
`
g.Layout{
			g.Label("One line label"),
		        g.Button("Click Me", nil),
}
`
and how to set color only for label?

**Comment by bezrazli4n0** [comment]
Nice, we can do it by call: `giu.Custom`, see examples.

**Comment by AllenDang** [comment]
@bezrazli4n0 
:P, yes, I'm thinking about how to make it more convenient.
I'll ping you back if I got something.
