### ISSUE TITLE
How to cross compile from Mac OS to Windows (with answer)

### ISSUE THREAD

**Issue by cgimenez** [AllenDang/giu#101]
Just in case, for people who want to cross compile from Mac OS to Windows. It's not restricted to giu, but might be useful to people using it.

At first I thought It will be a nightmare, but it proved to be very easy, without using https://github.com/karalabe/xgo - so without installing Docker.

My config is : 
- Mac OS 10.12.6 (rather old uh?)
- Mac ports 2.6.4 (I'm a port big fan over brew)

Under terminal :
`sudo port install mingw-w64`

Then, you would appreciate to run your app under Wine instead of using a full blown VM. So head to https://www.winehq.org/ - Don't bother trying to install Wine under mac ports, it's a trap, will take forever and a bunch of installed packaged will be "upgraded" to universal versions.

You're done.

Under your giu app directory use 
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ HOST=x86_64-w64-mingw32 go build -ldflags "-extldflags=-static" -p 4 -v -o bin/app-amd64.exe`

First compilation will take some times to proceed, but subsequent builds will be very fast.

Then 
`wine bin/app-amd64.exe`

Fine. Simple. Efficient. Easy. Coding/Debugging iterations are very fast, it's a breeze !

**Comment by AllenDang** [comment]
@cgimenez Works like a charm!
BTW, do you know how to embed icon in to exe? 
Currently I still have to open Windows in VM and use ResHack to set icon.

**Comment by cgimenez** [comment]
I did not tried but there's an explanation here : https://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable

Hopefully, the windres utility is available with the mac port's x86_64-w64-mingw32-binutils
You can check its presence by issuing a `x86_64-w64-mingw32-windres --version`

So, I think you might try to 
- create a .rc file, 
- "compile" it with windres during your build process (or manually, once in a time), 
- then pass the .o file generated by windres to the mingw linker via the -extldflags

**Comment by AllenDang** [comment]
Update here, I got it works!

```sh
cat > YourExeName.rc << EOL
id ICON "./res/app_win.ico"
GLFW_ICON ICON "./res/app_win.ico"
EOL

x86_64-w64-mingw32-windres YourExeName.rc -O coff -o YourExeName.syso

GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ HOST=x86_64-w64-mingw32 go build -ldflags "-s -w -H=windowsgui -extldflags=-static" -p 4 -v -o YourExeName.exe

rm YourExeName.syso
rm YourExeName.rc
```

This script could build Window Executable from MacOS and set app icon and window icon properly.

**Comment by cgimenez** [comment]
Great !! Seems that embedding the .syso file is the go linker's job (I thought would be done by the mingw linker)

Found this article about windows manifests files, might be useful to configure further the behaviour of a windows application at runtime : https://xuri.me/2016/06/15/embedded-icon-in-go-windows-application.html
