### ISSUE TITLE
undefined giu.TreeNodeV and giu.IsItemClicked on giu/examples/widgets/widgets.go

### ISSUE THREAD

**Issue by cydside** [AllenDang/giu#103]
Hi,
I just create a new folder and a new go.mod as follow:

`go mod init package/name`
`go mod tidy`

and copied `widget.go` in the folder having those files:

`go.mod`
`go.sum`
`widgets.go`

now running `go build widget.go` compiler gives me those messages:

`./widget.go:142:5: undefined: giu.TreeNodeV`
`./widget.go:144:10: undefined: giu.IsItemClicked`

**Comment by AllenDang** [comment]
@cydside Seems you need to `go get -u github.com/AllenDang/giu@master`

**Comment by cydside** [comment]
@AllenDang Thanks, lesson learned.
