### ISSUE TITLE
fixed SplitLayout

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#108]
Is it possible to have a splitlayout that is fixed (so the borders cannot be moved)?

**Comment by AllenDang** [comment]
Use giu.Child to create fixed panel

**Comment by marcelloh** [comment]
is there documentation, or an example in how to use this?
I've tried to have 2 horizontally next to each other but I get them below each other, which is wierd because the given width and height is not respected, I think.
```
func layout2() {
	g.Layout{
		g.Child("split", true, 200, 400, g.WindowFlagsNone,
			g.Layout{
				g.Label("Left panel"),
				g.Line(g.Button("Button1", nil), g.Button("Button2", nil)),
			}),
		g.Child("split", true, 200, 400, g.WindowFlagsNone,
			g.Layout{
				g.Label("right panel"),
				g.Line(g.Button("Button3", nil), g.Button("Button4", nil)),
			}),
	}.Build()
}
```

**Comment by AllenDang** [comment]
@marcelloh Use g.Line(g.Child(), g.Child()) to put them in same line.

**Comment by marcelloh** [comment]
that gives me the same effect:
```
func layout2() {
	g.Layout{
		g.Line(
			g.Child("split", true, 200, 400, g.WindowFlagsNone,
				g.Layout{
					g.Label("Left panel layout 2"),
					g.Line(g.Button("Button1", nil), g.Button("Button2", nil)),
				}),
			g.Child("split", true, 200, 400, g.WindowFlagsNone,
				g.Layout{
					g.Label("right panel layout 2"),
					g.Line(g.Button("Button3", nil), g.Button("Button4", nil)),
				}),
		),
	}.Build()
}
```
![screenshot1](https://user-images.githubusercontent.com/17491986/103510455-95fd4900-4e65-11eb-9074-eb64251b3c7b.png)

**Comment by marcelloh** [comment]
and is there a possibility to have the height the remaining  size to the bottom?

**Comment by AllenDang** [comment]
```go
package main

import (
	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow("hello world").Layout(g.Layout{
		g.Label("Hello world from giu"),
		g.Line(
			g.Child("Left Panel").Size(100, 100).Layout(g.Layout{
				g.Label("Label"),
			}),
			g.Child("Right Panel").Size(100, 100).Layout(g.Layout{
				g.Label("Label 2"),
			}),
		),
	})
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable, nil)
	wnd.Run(loop)
}
```
And set the height of Child to negative number to make it's height be dynamic.

**Comment by marcelloh** [comment]
Don't know if you use another giu version, but I get:
```
not enough arguments in call to giu.Child
have (string)
want (string, bool, float32, float32, giu.WindowFlags, giu.Layout)

giu.Child("Left Panel").Size undefined (type *giu.ChildWidget has no field or method Size)
```

**Comment by AllenDang** [comment]
@marcelloh You need to update to newest version.

**Comment by marcelloh** [comment]
Now I get a lot of errors :-(
It seems that a lot has changed.
I find it hard to understand if there is a thing that has a function like g.Menu("Home").Layout( g.Layout{...})
To me it seems that the g.Layout part doesn't have to be present, because it's already known it is a layout because of the function Layout(). I think layout should get the content you normally put in the g.Layout{}. But I have no idea what your explanation is.
Now I'm trying to fix everything that is broken.

**Comment by AllenDang** [comment]
@marcelloh Refer examples/widgets/Widgets.go. There has all the demo code. And check examples folder, you could find all demo about everything.
