### ISSUE TITLE
cimgui bindings

### ISSUE THREAD

**Issue by zlianon** [AllenDang/giu#109]
have you considered this option?
https://github.com/cimgui/cimgui

https://github.com/xlab/c-for-go

i tried to "rewrite" current bindings, but it's too much work...
https://github.com/zlianon/imgui-go

**Comment by AllenDang** [comment]
Actually cimgui was an option in the beginning, but soon I found that too much work need to be done, and imgui-go saved me a lot effort.

May I ask why you suggest to use it?

**Comment by lotodore** [comment]
Sorry for digging out this old issue: I was wondering pretty much the same as @zlianon.
The C bindings cimgui are generated, not manually maintained. This leads to additional libraries like dearimplot also offering generated C bindings https://github.com/cimgui/cimplot, but they do not have golang bindings. I'd very much love to use dearimplot with giu...

**Comment by AllenDang** [comment]
@lotodore Yeah, automatically binding generator is always a sweet dream for me. Manual adjustment to catch up each release of imgui is kind of exhausted... 
I've tried many times frankly about to use c-for-go or other automatic binding generator, none of them works so far.
And if something goes wrong, it's nearly impossible to debug.

**Comment by lotodore** [comment]
@AllenDang Thank you for the feedback. Sounds reasonable. Keep up the great work!
