### ISSUE TITLE
Add widget dynamically

### ISSUE THREAD

**Issue by J7mbo** [AllenDang/giu#11]
Hi, I'm trying to, given the click of a button (in it's triggered func(){}) add another button next to the previous one.

I can't find a concrete example of how to do this because the widgets are not passed by reference. Do I need to copy and re-render the whole window with all it's previous state and just the new button added? How can I achieve this?

Many thanks for the great lib!

**Comment by AllenDang** [comment]
1. Use the Condition widget.
2. Create a func returns g.Layout, build what ever You need in it.
3. Use g.Custom widget add bool to indicate when to build a new button.

**Comment by J7mbo** [comment]
Excellent, thanks for the options.

**Comment by anthracis** [comment]
@J7mbo or @AllenDang can You write any example for this case ?

**Comment by HACKERALERT** [comment]
@AllenDang @rjablecki Here's a short example of adding widgets dynamically:

```go
package main

import (
	g "github.com/AllenDang/giu"
)

func buildStuff() g.Layout{
	dynamicLabel := g.Label("I am rendered dynamically!")
	dynamicButton := g.Button("I am also rendered dynamically!")
	l := g.Layout([]g.Widget{dynamicLabel,dynamicButton})
	return l
}

func loop() {
	g.SingleWindow("Drag and Drop").Layout(
		g.Label("I am not dynamic."),
		buildStuff(),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hi",600,400,g.MasterWindowFlagsNotResizable,nil)
	wnd.Run(loop)
}
```

**Comment by AllenDang** [comment]
@HACKERALERT Good suggestion, will do. And I think this is the most charming part of immediate ui. :)
