### ISSUE TITLE
OpenGL 2 ES support

### ISSUE THREAD

**Issue by arkadiam** [AllenDang/giu#110]
I'm trying to build examples on a platform that only supports gles2 (pinephone, arm64, Mali-400) with:

`~/go/src/github.com/AllenDang/giu/examples/widgets$ go build -tags gles2
`

Running the app fails with:

```
$ ./widgets 
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

goroutine 1 [running, locked to thread]:
github.com/AllenDang/giu.NewMasterWindow(0x6d7d34, 0x8, 0x320, 0x258, 0x0, 0x0, 0x7)
        /home/mobian/go/src/github.com/AllenDang/giu/MasterWindow.go:49 +0x3c4
main.main()
        /home/mobian/go/src/github.com/AllenDang/giu/examples/widgets/widgets.go:192 +0x164
```

Please advise if gles2 is supported. If not, is this something that can be achieved? Thanks!

**Comment by AllenDang** [comment]
@arkadiam I'm afraid you need to write a renderer for GLES2 manually.

**Comment by arkadiam** [comment]
Thank you for your reply.

Is it what this project is doing?
github.com/inkyblackness/imgui-go-examples/cmd/example_glfw_opengl2
I can build and run this example.

**Comment by AllenDang** [comment]
@arkadiam Giu is based on opengl3, but yes, you could refer the renderer from imgui-go and implement it.
