### ISSUE TITLE
`GetCursorScreenPos()` doesn't work on Windows?

### ISSUE THREAD

**Issue by Holmqvist1990** [AllenDang/giu#118]
**Expected**
`GetCursorScreenPos()` returns `Point` with correct values.

**Actual**
`GetCursorScreenPos()` always returns `Point{8 27}`.

**Steps to reproduce**
```
Windows 10
go1.15.6
giu v0.5.0
```

**Comment by AllenDang** [comment]
@Holmqvist1990 Can you share your code?

**Comment by Holmqvist1990** [comment]
I am sorry for having wasted your time; you are correct. I had experimented with `GetCursorPos` and `GetCursorScreenPos` inspired by examples/canvas, failing to notice `GetMousePos`.

Thank you for a quick and accurate answer!
