### ISSUE TITLE
How to do things only once

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#121]
I have this part:
```
func splash() {
	println("splash")
	g.Layout{
		g.Label("Im a label from layout 1"),
		g.ImageWithFile("./images/logo_splash.png").Size(800, 403),
	}.Build()
}
```
but when I move my mouse, I see that the println is constantly printed. This means If I have a time consuming piece, it will also be triggered (like reading from a database or so)

I tried to do it once with a bool (do it when still false) like int his part:
```
	if !showLayout {
		showLayouts = true
		println("show me the money")
		items = libFile.GetAllDirs("/")
		g.Layout{
			g.Label("Select n item from below"),
			g.Combo("", items[itemSelected], items, &itemSelected).OnChange(doSomething),
		}.Build()
	}
```
but then it only prints the "show me the money" and not the other stuff.

Is there a good way to solve this problem?

**Comment by Nicify** [comment]
This is not a problem at all, this is how the immediate mode GUI works, giu just provides a new way to create dear imgui widgets and implement event driven updates etc, it is still essentially imgui.
So if you don't know how to use the immediate mode GUI, you will have a tough time using giu.

**Comment by marcelloh** [comment]
I solved it by moving the gui part out of the test like this:
```
	if !showLayout {
		showLayouts = true
		println("show me the money")
		items = libFile.GetAllDirs("/")
	}
	g.Layout{
		g.Label("Select n item from below"),
		g.Combo("", items[itemSelected], items, &itemSelected).OnChange(doSomething),
	}.Build()
```
