### ISSUE TITLE
scroll speed of mouse

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#123]
is it possible to change the scroll speed of the mouse?

When a layout is bigger than the screen, I can scroll, but with the mouse it's super-fast. :-(
(I know there's a scrollbar, bar not everybody uses that)

**Comment by AllenDang** [comment]
There is no easy way to control scroll speed.

**Comment by marcelloh** [comment]
is there some event that is triggered when scrolling with the mouse?

**Comment by AllenDang** [comment]
What are you going to archive?

**Comment by marcelloh** [comment]
To slow down the scrolling.It is much faster in my GIU application that in
any other application.
If I have 1000 lines, it's hard to read (because the scrolling is that fast)

Op vr 15 jan. 2021 om 17:06 schreef Allen Dang <notifications@github.com>:

**Comment by AllenDang** [comment]
@marcelloh Sorry, but currently there is no easy way to control the scroll speed.
