### ISSUE TITLE
Wrapping scroll functions

### ISSUE THREAD

**Issue by saucesaft** [AllenDang/giu#129]
Hi, for an application im developing with this library, i need the scroll [functions](https://github.com/inkyblackness/imgui-go/blob/0065f3b918a366865b6ddf984c15e85f92a171ab/Scroll.go) provided by imgui. For what i've seen, the only one wrapped in the imgui's fork of this repo is `SetScrollHereY()`, so i was wondering, is there any special reason why only that function is wrapped? If not, can i proceed with a pr wrapping the previously mentioned functions?
Thanks :)

**Comment by AllenDang** [comment]
Aha, because that's the only function I've used, :P
Welcome to make PR.

**Comment by saucesaft** [comment]
Great, thanks, working rn on the pr.
