### ISSUE TITLE
giu project not work on Mac 

### ISSUE THREAD

**Issue by sndnvaps** [AllenDang/giu#13]
i have build it with travis-ci 
my .travis.yml file 
https://github.com/sndnvaps/ebookdownloader/blob/master/.travis.yml

<img width="1680" alt="微信图片_20200125001814" src="https://user-images.githubusercontent.com/1549019/73084721-75fca000-3f08-11ea-977b-4796dcb74c82.png">

**Comment by sndnvaps** [comment]
@AllenDang have you test giu project on mac platform.. 
i have got crash when double click the app.

**Comment by AllenDang** [comment]
@sndnvaps Yes, mac is tested on MacOS 10.15. Is there still crash? It seems something is not proper initialized.

**Comment by sndnvaps** [comment]
> @sndnvaps Yes, mac is tested on MacOS 10.15. Is there still crash? It seems something is not proper initialized.

not sure now .i just test in my friends mac book.
i dont have mac book. so i cann't fix it ....
