### ISSUE TITLE
proposal: simplify `WindowWidget.Layout` API usage

### ISSUE THREAD

**Issue by mewmew** [AllenDang/giu#131]
Hi @AllenDang,

Just want to start of by saying how inspiring it has been to learn about giu. I think the declarative approach to UI is really quite beautiful! Thank you for sharing this project with the community!

I also find the Widget interface to be beautiful in it's simplicity, every widget knows what imgui operations to invoke to build itself. And the `Layout` is also very simple, just a list of `Widget`s. Through it's simplicity, you've arrived at such a powerful declarative API.

I was taking a look at the different examples and found a small change of the `WindowWidget.Layout` API could help improve readability.

The current helloworld example has the following code:

```go
func loop() {
	g.SingleWindow("hello world").Layout(g.Layout{
		g.Label("Hello world from giu"),
		g.Line(
			g.Button("Click Me").OnClick(onClickMe),
			g.Button("I'm so cute").OnClick(onImSoCute),
			g.Button("Quit").OnClick(onQuit),
		),
	})
}
```

If the API of `WindowWidget.Layout` was updated from `func (w *WindowWidget) Layout(layout Layout)` to `func (w *WindowWidget) Layout(widgets ...Widget)`, then the helloworld example could be written as follows. Notice that `g.Layout{}` was removed from the code.

```go
func loop() {
	g.SingleWindow("hello world").Layout(
		g.Label("Hello world from giu"),
		g.Line(
			g.Button("Click Me").OnClick(onClickMe),
			g.Button("I'm so cute").OnClick(onImSoCute),
			g.Button("Quit").OnClick(onQuit),
		),
	)
}
```

What do you think of the API change?

Cheers,
Robin

**Comment by AllenDang** [comment]
@mewmew Aha! That's a very good solution! I also feel the .Layout(g.Layout{}) is kind of ugly. Will you make a PR for the change?

**Comment by mewmew** [comment]
> @mewmew Aha! That's a very good solution! I also feel the .Layout(g.Layout{}) is kind of ugly. Will you make a PR for the change?

Wow, very quick response time :)

Sure! I'll submit a PR!

**Comment by mewmew** [comment]
As a benefit, this change is backwards compatible, since `Layout` implements the `Widget` interface.

**Comment by AllenDang** [comment]
@mewmew Sorry to close the PR, cause I cannot wait and implement this already...
