### ISSUE TITLE
can not run hello world

### ISSUE THREAD

**Issue by jeel2331** [AllenDang/giu#133]
i copied hello world from the readme file and it is giving me this error
```
.\practice.go:24:5: syntax error: unexpected ), expecting }
.\practice.go:25:1:
```

i am running it on windows 10 with go  15.6 what is wrong with it help me!

here 's the code i copied
```
package main

import (
    "fmt"

    g "github.com/AllenDang/giu"
)

func onClickMe() {
    fmt.Println("Hello world!")
}

func onImSoCute() {
    fmt.Println("Im sooooooo cute!!")
}

func loop() {
    g.SingleWindow("hello world").Layout(
        g.Label("Hello world from giu"),
        g.Line(
            g.Button("Click Me").OnClick(onClickMe),
            g.Button("I'm so cute").OnClick(onImSoCute)),
        )
    )
}

func main() {
    wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable, nil)
    wnd.Run(loop)
}
```

**Comment by AllenDang** [comment]
@jeel2331 Thanks, it is fixed. I updated README.

**Comment by jeel2331** [comment]
> @jeel2331 Thanks, it is fixed. I updated README.

i tried your updated code but now it is giving me this error
``` 
# command-line-arguments
.\practice.go:18:38: too many arguments in call to giu.SingleWindow("hello world").Layout
        have (*giu.LabelWidget, *giu.LineWidget)
        want (giu.Layout)
```

**Comment by AllenDang** [comment]
@jeel2331 Please show me your code. And what version of giu you are using?

**Comment by jeel2331** [comment]
it is the latest version i downloaded it today
i found it in my go.mod file
`require github.com/AllenDang/giu v0.5.1 // indirect`

**Comment by AllenDang** [comment]
Run `go get -u github.com/AllenDang/giu@master` in your project's path and it should fix it.

**Comment by jeel2331** [comment]
> Run `go get -u github.com/AllenDang/giu@master` in your project's path and it should fix it.

thanks it is now working.
but when i run the build it is showing console window can you tell me how do i hide it and also while building the binary file(.exe file) it consumes so much ram and cpu power any tips?

after your answer issue will be closed

**Comment by AllenDang** [comment]
@jeel2331 I asume you are using Windows, you could build a gui executable like this `go build -ldflags "-s -w -H=windowsgui -extldflags=-static" .`.
First time building giu will compile all cpp files comes from imgui library, after that, the build speed and cpu usage will be normal.

**Comment by jeel2331** [comment]
thanks for your help
