### ISSUE TITLE
SplitterLayout looks broken

### ISSUE THREAD

**Issue by wowtk777** [AllenDang/giu#135]
I try to use SplitterLayout but get an error after application start:

`Assertion failed: (g.WithinEndChild) && "Must call EndChild() and not End()!", file imgui.cpp, line 6216`
`exit status 3`

I tried to compile `splitter.go` example and got same error.

**Comment by AllenDang** [comment]
@wowtk777 Can you confirm you are using latest version of giu? Try to run `go get -u github.com/AllenDang/giu@master` in your project folder.

**Comment by wowtk777** [comment]
@AllenDang thank you
The command `go get -u github.com/AllenDang/giu` solved my issue on Linux (go 1.15, Ubuntu 18)
I will check on Windows at evening

**Comment by wowtk777** [comment]
@AllenDang I can reproduce this bug.

When any splitter go out of window border a application crashes. It reproduces both Linux and Windows.

I make a video to show the bug: https://youtu.be/fBLgr-Bg3T0. I used go version 1.15.7 windows/amd64 (MINGW64)

**Comment by AllenDang** [comment]
@wowtk777 Nick catch!! Can you paste the error message to help me locate the issue?

**Comment by wowtk777** [comment]
@AllenDang Yes. Full message is:
```
$ go run examples/splitter/splitter.go
Assertion failed: (g.WithinEndChild) && "Must call EndChild() and not End()!", file imgui.cpp, line 6216
exit status 3
```

**Comment by AllenDang** [comment]
@wowtk777 Issue sovled. Please update giu and help to try again.

**Comment by wowtk777** [comment]
@AllenDang thank you. It works on Windows and Linux.

I checked slide movenent and window resise. All are ok.
