### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by undeadindustries** [AllenDang/giu#14]
Sorry to put this in "issues". Didn't know where else to put this. 

I clicked on the Wiki, but it was the same as the main page.

Is there documentation for this? I'd really like to check it out.

Thanks!!

**Comment by AllenDang** [comment]
Im creating document now. Needs more time. For now, You could check examples for usage.

**Comment by AllenDang** [comment]
@undeadindustries I created the first page of Wiki, I know it's not enough, but I will keep improving it.

**Comment by undeadindustries** [comment]
Thank you so much. This is an exciting project!
