### ISSUE TITLE
dependency cycle?

### ISSUE THREAD

**Issue by librariusbabble** [AllenDang/giu#144]
I was trying to get giu working in a test program.  To that end, I copied the example from the readme, but the compiler throws an "import cycle" error.  This is true also when using ``go get`` to, well, get giu.

**Comment by AllenDang** [comment]
@librariusbabble Can you run any demo code in examples folder?

**Comment by AllenDang** [comment]
@librariusbabble And please paste the complete code you are trying to run.

**Comment by librariusbabble** [comment]
So it turned out to be an issue with **$GOPATH** for some reason, but regardless I've fixed the issue.  Thanks!
