### ISSUE TITLE
[Windows] go get github.com/AllenDang/giu fails

### ISSUE THREAD

**Issue by bartimus-primed** [AllenDang/giu#151]
Not sure what the requirements are, just following along with the README.

Error:
```
# github.com/AllenDang/giu/imgui
C:\Users\#####\AppData\Local\Temp\go-build3633627171\b001\_x039.o: In function `ImeSetInputScreenPosFn_DefaultImpl':
..\..\..\go\pkg\mod\github.com\!allen!dang\giu@v0.5.3\imgui/imgui.cpp:10724: undefined reference to `ImmGetContext'
..\..\..\go\pkg\mod\github.com\!allen!dang\giu@v0.5.3\imgui/imgui.cpp:10730: undefined reference to `ImmSetCompositionWindow'
..\..\..\go\pkg\mod\github.com\!allen!dang\giu@v0.5.3\imgui/imgui.cpp:10731: undefined reference to `ImmReleaseContext'
collect2.exe: error: ld returned 1 exit status
```

**Comment by AllenDang** [comment]
@bartimus-primed What's the mingw version you are using?

**Comment by nitrix** [comment]
Found this in the imgui changelogs:

```
 - 2021/02/22 (1.82) - win32+mingw: Re-enabled IME functions by default even under MinGW. In July 2016, issue #738 had me incorrectly disable those default functions for MinGW. MinGW users should: either link with -limm32, either set their imconfig file  with '#define IMGUI_DISABLE_WIN32_DEFAULT_IME_FUNCTIONS'.
```

Does giu/go-imgui do either of these things?

**Comment by bartimus-primed** [comment]
@AllenDang sorry I didn't get back to you, I wasn't at my computer very long yesterday. Msys is from 20200903, I think I need more caffeine cause I it took me awhile to find:
gcc version 6.3.0 (x86_64-win32-seh-rev1, Built by MinGW-W64 project)

**Comment by AllenDang** [comment]
@nitrix Thanks a lot! @bartimus-primed Can you also try the newest version?

**Comment by bartimus-primed** [comment]
@AllenDang I'm still having the same issues, i'm going to clear the go cache and reinstall msys/mingw to see if that rectifies the issue.

**Comment by AllenDang** [comment]
@bartimus-primed I installed a windows 10 VM and got a clean build with TDM-GCC https://jmeubank.github.io/tdm-gcc/download/.

**Comment by kineticeagle** [comment]
@AllenDang downloading that now and will let you know.

**Comment by AllenDang** [comment]
@kineticeagle Remember to delete C:\Users\name\AppData\Local\go-build

**Comment by bartimus-primed** [comment]
@AllenDang , yeah I am not even sure now, cause I did all of that. I am going to just wipe the box in a few days and try again. I'll close this though since it seems to be on my end.

**Comment by AllenDang** [comment]
@bartimus-primed If you are working on MacOS, and need to cross-build a Windows version, you don't need to install a VM, check this https://github.com/AllenDang/giu/issues/101.

**Comment by Ramoflaple** [comment]
> @AllenDang , yeah I am not even sure now, cause I did all of that. I am going to just wipe the box in a few days and try again. I'll close this though since it seems to be on my end.

You are not alone. I have the same problem with the same mingw version as yours.

**Comment by Ramoflaple** [comment]
> > @AllenDang , yeah I am not even sure now, cause I did all of that. I am going to just wipe the box in a few days and try again. I'll close this though since it seems to be on my end.
> 
> You are not alone. I have the same problem with the same mingw version as yours.

emm, linking to libimm32.a solves the problem

**Comment by eliodilar** [comment]
@Ramoflaple you'r a boss man ;-)

**Comment by shash29-dev** [comment]
This seems very old issue,
But at present, what should we do?
#define` `IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS
or 
#define IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS   [From #4301]

Tried both none works.
However, linking with libimm32.a works.  Thanks @Ramoflaple
