### ISSUE TITLE
[WIN10] exit status 3221225477

### ISSUE THREAD

**Issue by alchem1ster** [AllenDang/giu#156]
**OS:** Windows 10 20H2 19042.870
**CPU:** Ryzen 3700X
**GPU:** RTX 2070S
**Go:** go1.16.2 windows/amd64

1. Installed latest Go version;
2. Installed TDM-GCC 9.2.0;
3. `go init` new project;
3. `go get github.com/AllenDang/giu@master`;
4. Copied `examples/helloworld/helloworld.go` into project dir;
5. `go run helloworld.go`.

**What I get:**
>exit status 3221225477

**What I expect:**
Perfect GUI window with Hello world :)

**Comment by AllenDang** [comment]
@alchem1ster Are your using a windows VM?

**Comment by alchem1ster** [comment]
> @alchem1ster Are your using a windows VM?

No, it's not a VM

**Comment by alchem1ster** [comment]
![image](https://user-images.githubusercontent.com/3815426/112303417-4fbdc600-8cad-11eb-9b14-4460f13e7b01.png)

**Comment by AllenDang** [comment]
@alchem1ster After a long time search, this issue seems may come with TDM-GCC. I'm trying to build with cygwin now...

**Comment by alchem1ster** [comment]
@AllenDang 
So, confirmed. This problem was solved by uninstalling TDM-GCC and installing MinGW.
I used this: https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-8.0.0-r8
Both compiling and running successful works.

**Comment by AllenDang** [comment]
@alchem1ster Thanks very much!
