### ISSUE TITLE
No references in widget click functions

### ISSUE THREAD

**Issue by anthracis** [AllenDang/giu#16]
Hi. I am really interested about this project! I want to rewrite my old app using this layout but I have problem with events functions. For example: i render buttons based on array of strings. I need to pass this string to click function. There is any option to pass any data to this function or to get reference for clicked button ?

```
itms := []string{"foo", "bar", "zzz", "www"}
var rows []*g.RowWidget
for i,name := range  itms {
    rows = append(rows,  g.Row(g.Label(fmt.Sprintf("a%d",i)), g.Label(fmt.Sprintf("b%d",i)), g.Button(name, func(){
			fmt.Println(name) // It's always www now. I need correct ID here
    })))
}
```
I know that this code is wrong but it explains my problem

**Comment by AllenDang** [comment]
Here is a demo

```
package main

import (
	"fmt"
	g "github.com/AllenDang/giu"
)

var (
	names []string
)

func buildButtons() g.Layout {
	var buttons g.Layout
	for i, name := range names {
		selected := name
		buttons = append(buttons, g.Button(fmt.Sprintf("%s##%d", name, i), func() {
			fmt.Println(selected)
		}))
	}

	return buttons
}

func loop() {
	g.SingleWindow("Test", g.Layout{
		buildButtons(),
	})
}

func main() {
	names = []string{"Hello", "Buttons", "Haha"}

	wnd := g.NewMasterWindow("Test", 400, 200, true, nil)
	wnd.Main(loop)
}
```

**Comment by AllenDang** [comment]
Incase anyone who met this issue. I added a RangeBuilder to handle this properly. Check examples/rangebuilder for usage.

**Comment by darkermatter** [comment]
Hi Allen,

I'm generating a table and I want a button in each row. The problem I'm having is that the button ID and label are the same value. Is there any way to get around this?

Thanks!

**Comment by AllenDang** [comment]
@darkermatter 
The demo code I've given in this thread (look upper) could solve this issue.

**Comment by darkermatter** [comment]
Hi Allen,

the label will still have the same string as the identifier. So, I can't have a button on each row labelled "delete", it would end up being "delete-0001", "delete-0002", etc.

**Comment by darkermatter** [comment]
Wait, is the ## some sort of tag indicator?

**Comment by darkermatter** [comment]
Okay, just tested it and the '##' makes all the difference, thank you so much! :-)
