### ISSUE TITLE
[Question] Building GLFW for wayland

### ISSUE THREAD

**Issue by santiagocezar** [AllenDang/giu#161]
(note that this is an issue that I posted in go-gl/glfw#314 but as it's related to this library I post it here too)

> Hi, I've been trying to use [AllenDang/giu](https://github.com/AllenDang/giu), an application framework that uses go-glfw under the hood.  
> When I try to build the app using `-tags wayland` I got an error:
> ```
> # github.com/go-gl/glfw/v3.3/glfw
> In file included from /tmp/glfw/src/internal.h:190,
>                  from /tmp/glfw/src/context.c:30,
>                  from ./c_glfw.go:4:
> /tmp/glfw/src/wl_platform.h:57:10: fatal error: wayland-xdg-shell-client-protocol.h: No such file or directory
>    57 | #include "wayland-xdg-shell-client-protocol.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```
> 
> In the wiki I found that i should use `scripts/generate-wayland-protocols.sh`, which successfully compiled this repository.
> 
> But that didn't solve my problem, because I need to run the script for the library that I downloaded via `go get`.
> 
> Where should I run the script? and do I make it permanent so it doesn't get overridden by updates?

I'm not sure if something can be done from giu but if it can I hope this helps

**Comment by AllenDang** [comment]
@santiagocezar I guess this should be added into cgo parameter in the cgo related code in glfw.

**Comment by santiagocezar** [comment]
Sorry, I've found out that this issue was caused because go get doesn't download symbolic links, closing as it's unrelated to the library
