### ISSUE TITLE
Not able to enable horizontal scroll bar

### ISSUE THREAD

**Issue by vivekvardha** [AllenDang/giu#168]
I am working on to create "InputTextMultiline" widget.
This widget would be containing data read from a text file. Vertical scroll is already provided with the widget. I am trying to enable/disable horizontal scroll bar based on the horizontal resizing of the window.

In the single window creation, I tried passing the flag "WindowFlagsHorizontalScrollbar" but this is did not help me.
Second thing that I tried out is to  add custom widget. I referred "Miscellaneous Horizontal Scrolling Demo" in the file imgui_demo.cpp. However, I could not complete this trial as I faced hurdles in understanding what is done over there. 
I tried adding the below three lines
```
		g.Custom(func() {
			//imgui.Vec2 scrolling_child_size = imgui.Vec2{X:0, Y:imgui.GetFrameHeightWithSpacing() * 7 + 30}
			imgui.BeginChildV("scrolling", imgui.Vec2{X: 0, Y: 0}, true, imgui.WindowFlagsHorizontalScrollbar)
			imgui.SetScrollHereX(0.5)
			imgui.EndChild()
		})
```
**Eventually what I understood is vertical scroll has been inbuilt into 'InputTextMultilineWidget' and its appearance is not due to SingleWindow flag settings. With 'InputTextMultilineWidget', horizontal scroll functionality is not provided. Correct me if my understanding is wrong. 
Is there anyway I can enable the working of horizontal scroll bar on 'InputTextMultilineWidget'?**

Requesting some inputs/pointer to proceed with this.

Also, how will I feed the information about the max width of the string which should enable the horizontal scroll bar? max width would be dynamic in nature considering the resized value of window. Requesting to help me in clear this understanding.

**Comment by AllenDang** [comment]
@vivekvardha This is an long-term issue of imgui. The most nearly solution is create a Child as container of InputTextMultiline and set the width of InputTextMultiline to the longest line of text it contains.

**Comment by vivekvardha** [comment]
Hello @AllenDang ,
The text that I am going to read a log file and length of line is something which is not certain.

I tried going through the method InputTextEx of class ImGui in file imgui_widget.cpp.
I tried to understand this function and I thought that if I make the control hit the scroll section, things should start working but this did not happen.

Thank you for the response.

**Comment by AllenDang** [comment]
@vivekvardha Another solution is to use the CodeEditor widget it already implement a horizontal scroll bar. Check examples/codeeditor for demo.

**Comment by AllenDang** [comment]
@vivekvardha If you just need to view the content, doesn't need to edit it, I think using FastTable+Label is a good solution to display a large set of text lines.
