### ISSUE TITLE
Drag and drop files?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#169]
Hi, thanks for creating this beautiful Go UI library. Looking in the examples, there's a drag and drop example, but that's only for widgets inside the window. Is it possible to add an event handler for dragging and dropping files from a file manager into a giu window? Thank you.

**Comment by AllenDang** [comment]
@HACKERALERT Check out examples/ondrop.

**Comment by HACKERALERT** [comment]
Great thanks! I think I missed it the first time I looked.
