### ISSUE TITLE
Can't link successfully but have required input 

### ISSUE THREAD

**Issue by fxfactorial** [AllenDang/giu#17]
/usr/lib/x86_64-linux-gnu/libGL.so
/usr/lib/x86_64-linux-gnu/libGL.so.1
/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0

uname -a 
Linux edgar-ThinkPad-X1-Extreme-2nd 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

go build -ldflags '-L /usr/lib/x86_64-linux-gnu -w -extldflags "-static"' gui/main.go 
# command-line-arguments
/home/edgar/.gimme/versions/go1.13.6.linux.amd64/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: /tmp/go-link-679058208/000039.o: in function `_glfwInitVulkan':
c_glfw.cgo2.c:(.text+0x6e5e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status

where the main.go example is your README's example

**Comment by AllenDang** [comment]
May I ask what are you trying to do? Build the project? Build a test project of your own?

**Comment by fxfactorial** [comment]
Build the code example of yours in readme

**Comment by AllenDang** [comment]
@fxfactorial I'm not a linux user, so I'm afraid I cannot provide much help on this. I'll leave this issue open in case someone could figure out how to fix.

**Comment by saucesaft** [comment]
I'm a linux user, can you post the error print and distro please.

**Comment by fxfactorial** [comment]
@saucesaft its all written in the first post
