### ISSUE TITLE
examples/dynamicloadfont: example crashes

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#171]
Hi!
I wanted to run `examples/dynmiacloadfont` but it panics:
```
dynamicloadfont: imgui.cpp:7112: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed.
SIGABRT: abort
PC=0x7f43aff019d5 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6131f0, 0xc0000cddb8, 0x4000)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000cdd88 sp=0xc0000cdd50 pc=0x48567b
github.com/AllenDang/imgui-go._Cfunc_iggNewFrame()
        _cgo_gotypes.go:4546 +0x3c fp=0xc0000cddb8 sp=0xc0000cdd88 pc=0x571d5c
github.com/AllenDang/imgui-go.NewFrame(...)
        /home/user/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210420132712-af9cab48ddf4/imgui.go:28
github.com/AllenDang/giu.(*MasterWindow).render(0xc000186000)
        /home/user/git/d2/me/giu/MasterWindow.go:174 +0x96 fp=0xc0000cde28 sp=0xc0000cddb8 pc=0x60faf6
github.com/AllenDang/giu.(*MasterWindow).run.func1()
        /home/user/git/d2/me/giu/MasterWindow.go:193 +0x59 fp=0xc0000cde68 sp=0xc0000cde28 pc=0x610219
github.com/faiface/mainthread.Call.func1()
        /home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f fp=0xc0000cde98 sp=0xc0000cde68 pc=0x57804f
github.com/faiface/mainthread.Run(0xc00000e4c8)
        /home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1 fp=0xc0000cdf20 sp=0xc0000cde98 pc=0x577dd1
github.com/AllenDang/giu.(*MasterWindow).Run(0xc000186000, 0x8aca58)
        /home/user/git/d2/me/giu/MasterWindow.go:250 +0x65 fp=0xc0000cdf40 sp=0xc0000cdf20 pc=0x60fda5
main.main()
        /home/user/git/d2/me/giu/examples/dynmiacloadfont/dynamicloadfont.go:34 +0x73 fp=0xc0000cdf88 sp=0xc0000cdf40 pc=0x6108f3
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000cdfe0 sp=0xc0000cdf88 pc=0x4ba0f6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000cdfe8 sp=0xc0000cdfe0 pc=0x4ebb81

goroutine 5 [chan receive]:
github.com/faiface/mainthread.Call(0xc00009af60)
        /home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc000186000)
        /home/user/git/d2/me/giu/MasterWindow.go:191 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
        /home/user/git/d2/me/giu/MasterWindow.go:255 +0x4d
github.com/faiface/mainthread.Run.func1(0xc00000e4c8, 0xc000024120)
        /home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
        /home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5

rax    0x0
rbx    0x7f43afd79740
rcx    0x7f43aff019d5
rdx    0x0
rdi    0x2
rsi    0x7fff653957b0
rbp    0x7f43b0057680
rsp    0x7fff653957b0
r8     0x0
r9     0x7fff653957b0
r10    0x8
r11    0x246
r12    0x8e48b2
r13    0x1bc8
r14    0x8e8978
r15    0xffffffffffffffff
rip    0x7f43aff019d5
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by AllenDang** [comment]
@gucio321 Open the source file of this demo, you will find there is a hardcode font file path, change it to any valid font path.

**Comment by gucio321** [comment]
@AllenDang already modified before panic report. loadFont method looks like:
```golang
func loadFont() {
        fonts := g.Context.IO().Fonts()

        ranges := imgui.NewGlyphRanges()

        builder := imgui.NewFontGlyphRangesBuilder()
        builder.AddText("铁憨憨你好！")
        // builder.AddRanges(fonts.GlyphRangesChineseFull())
        builder.BuildRanges(ranges)

        fontPath := "/home/user/git/giu/examples/dynmiacloadfont/fonts/somefont.ttf"
        if _, err := os.Stat(fontPath); err != nil {
                log.Fatal("Font file doesn't exist")
        }
        fonts.AddFontFromFileTTFV(fontPath, 12, imgui.DefaultFontConfig, ranges.Data())
}
```

**Comment by AllenDang** [comment]
@gucio321 Can you tell me which line caused the crash?

**Comment by gucio321** [comment]
@AllenDang the panic isn't clear for me.
I commented out the following line:
`        fonts.AddFontFromFileTTFV(fontPath, 12, imgui.DefaultFontConfig, ranges.Data())`
and programm runs (obviously not working properly - characters are ????)

I attach my code:
[dynamicloadfont.txt](https://github.com/AllenDang/giu/files/6357196/dynamicloadfont.txt)

**Comment by AllenDang** [comment]
@gucio321 Please paste the panic message with the code here.

**Comment by gucio321** [comment]
hmm, @AllenDang :confused: I suppose, that full stack trace is in the header post of this issue
![image](https://user-images.githubusercontent.com/73652197/115699277-cd84f800-a365-11eb-9751-ffe5bb3820a3.png)

But, I'll re-attach panic
[output.txt](https://github.com/AllenDang/giu/files/6357546/output.txt)

also, code again:
[dynamicloadfont.go](https://github.com/AllenDang/giu/files/6357196/dynamicloadfont.txt)

**Comment by gucio321** [comment]
generally, DearImgui's assertion:
`Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed`

**Comment by AllenDang** [comment]
@gucio321 Strange, I could run your code under MacOS.

**Comment by gucio321** [comment]
hmmm.
my os info:
os: Fedora release 33 (Thirty Three)
desktop: GNOME Shell 3.38.4
go: go version go1.16.2 linux/amd64

**Comment by gucio321** [comment]
> @gucio321 Strange, I could run your code under MacOS.
@allenDang so, is it DearImgui's or imgui-go's bug?

**Comment by AllenDang** [comment]
@gucio321 What's your giu version?

**Comment by gucio321** [comment]
> @gucio321 What's your giu version?

code from `master`

**Comment by gucio321** [comment]
@AllenDang but v0.5.3 doesn't work too

**Comment by AllenDang** [comment]
@gucio321 It's weired.I figure you are using linux right? Sadlly I don't familiar with it...

**Comment by madwizard** [comment]
stracing it I have 

`[pid 39325] 18:40:34 openat(AT_FDCWD, "c:/Windows/Fonts/MSYHL.TTC", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 39325] 18:40:34 write(2, "dynamicloadfont: imgui_draw.cpp:"..., 191dynamicloadfont: imgui_draw.cpp:2115: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
`

on my Ubuntu 20.04. Seems like it tries to load using Windows paths

**Comment by AllenDang** [comment]
@madwizard Because your are using wrong font path.

**Comment by AllenDang** [comment]
@gucio321 I know what's going on here. If you are using range builder, make sure the font you choose does contain the character it build with. For example, in my demo, I have to use a chinese font so the range builder find the characters I intend to display and build the font texture correctly.

**Comment by gucio321** [comment]
oky, @AllenDang seems like it works!
thanx for help!
also, it looks, like if there is at least 1 character, which exists in a font.ttf, the panic doesn't appear.
e.g., if I'll do sth like that
```golang
        builder.AddText("铁憨憨你好！")
        builder.AddText("你好啊世界！铁憨憨")
```
the app will crash, but if I'll add a following line:
```golang
        builder.AddText("x")
```
It will run properly (of course other than "x" letters will not be displayed)
In my opinion `giu` should check it, or it is `imgui-go`'s fault?

**Comment by AllenDang** [comment]
@gucio321 Font related issue is the pain in my ass... I'm working on how to solve it once for all right now...
