### ISSUE TITLE
How to change window background colour?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#172]
Is there a way to change the background colour and text colour of a giu window? I tried `g.Style().SetColor(imgui.StyleColorWindowBg,color.RGBA{0xf5,0xf6,0xf7,255},)` and some others, but only the window's child elements were affected. The window itself didn't change background colour, and when I try to use `g.Style()....To(g.SingleWindow().Layout())`, it gives me an error.

**Comment by AllenDang** [comment]
@HACKERALERT MasterWindow.SetBgColor()

**Comment by HACKERALERT** [comment]
SetBgColor doesn't work:
```go
window := g.NewMasterWindow("Test",480,480,g.MasterWindowFlagsNotResizable,nil)
window.SetBgColor(color.RGBA{0xf5,0xf6,0xf7,255})
window.SetDropCallback(onDrop)
window.Run(loop)
````

**Comment by AllenDang** [comment]
```go
package main

import (
	"image/color"

	g "github.com/AllenDang/giu"
)

var (
	content string
)

func loop() {
	g.Window("small window").Size(200, 100).Layout(
		g.Label("Hello world from giu"),
		g.InputTextMultiline("##content", &content),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0, nil)
	wnd.SetBgColor(color.RGBA{R: 255, G: 255, B: 255, A: 255})
	wnd.Run(loop)
}
```

![截屏2021-04-23 下午1 25 41](https://user-images.githubusercontent.com/18550/115822620-6d5e8680-a437-11eb-957d-4a7995fcff68.png)

**Comment by AllenDang** [comment]
@HACKERALERT If you use SingleWIndow, it will cover all area of MasterWindow, so you will not see the background color has been changed.
