### ISSUE TITLE
Widget state (enabled/disabled)?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#173]
Is there a way to disable (and re-enable) a widget? There's a thread on imgui about this: https://github.com/ocornut/imgui/issues/1889. Just asking if it exists, not requesting it. Thank you.

**Comment by AllenDang** [comment]
@HACKERALERT I'm afraid currently there is no such thing.

**Comment by HACKERALERT** [comment]
Thanks for letting me know, I understand that Go is a new player in the desktop UI field.

**Comment by ocornut** [comment]
For cross referencing, we added PushDisabled/PopDisabled in imgui_internal.h today:
https://github.com/ocornut/imgui/issues/211#issuecomment-857704649

**Comment by AllenDang** [comment]
@ocornut Wow! That's really useful! I will support it ASAP. Thanks for notice!

**Comment by HACKERALERT** [comment]
@ocornut Thank you very much! I've been hoping for this feature in giu, and it looks like it will be possible now! Good luck to AllenDang as well for the implementation.

**Comment by AllenDang** [comment]
@HACKERALERT I just pushed a commit to add "Disabled" method to ButtonWidget, it works as expect! :)

**Comment by HACKERALERT** [comment]
Awesome! Thank you and ocornut so much, widget states are a valuable feature for a UI library :)
