### ISSUE TITLE
Where can i found sqlpower program from the screenshots path?

### ISSUE THREAD

**Issue by Numenorean** [AllenDang/giu#174]
It is located there as SqlPower.png, but i couldn't find it on the github

**Comment by AllenDang** [comment]
@Numenorean Oh, SqlPower is a private project and it's quality is not ready to publish. Are you curious about some part of it?

**Comment by Numenorean** [comment]
> @Numenorean Oh, SqlPower is a private project and it's quality is not ready to publish. Are you curious about some part of it?

I'd just like to see it as an example, because it's pretty interesting project. And yeah, i really liked imgui, so I'm trying to find as much real projects that uses that as possible. If it works even a little bit, could you publish it as a beta?

**Comment by AllenDang** [comment]
@Numenorean We've used it as primary sql query tool in my team for almost 2 years and it works pretty good. But the code is messy, and doesn't have a good structure. I'm thinking to publish it in future, like within half year.

**Comment by Numenorean** [comment]
> @Numenorean We've used it as primary sql query tool in my team for almost 2 years and it works pretty good. But the code is messy, and doesn't have a good structure. I'm thinking to publish it in future, like within half year.

looking forward to, thanks

**Comment by phorcys420** [comment]
I'm personally interested in the text editor, where could I find that ? 
(it looks similar to the O.G https://github.com/BalazsJako/ImGuiColorTextEdit but themed properly)

**Comment by AllenDang** [comment]
@phorcys420 Inside giu, named "CodeEditor", and it is ImGuiColorTextEdti

**Comment by phorcys420** [comment]
> @phorcys420 Inside giu, named "CodeEditor", and it is ImGuiColorTextEdti

any docs on how to use it ? I've tried using https://github.com/AllenDang/giu/blob/4c8d5daa3d70d8a8f63b8054f0ac55d2ebf521f5/examples/codeeditor/codeeditor.go as an example to implement it into my code and it throws different errors at me:
```
src/main.go:42:31: cannot use editor (type *giu.CodeEditorWidget) as type giu.Widget in argument to giu.TabItem("Scripts").Layout:
        *giu.CodeEditorWidget does not implement giu.Widget (missing Build method)
src/main.go:63:34: giu.CodeEditor("Scripts").ShowWhitespaces undefined (type *giu.CodeEditorWidget has no field or method ShowWhitespaces)
src/main.go:67:22: undefined: giu.LanguageDefinitionSQL
```

Code:
```go
g.CodeEditor("Scripts").
		ShowWhitespaces(false).
		TabSize(2).
		Text("select * from greeting\nwhere date > current_timestamp\norder by date").
		LanguageDefinition(giu.LanguageDefinitionSQL).
		Border(true)
```

**Comment by gucio321** [comment]
@phorcys420 you're probably using older version of giu in your app.
IIRC CodeEditor have been changed some time ago but it wasn't included in any release yer.
You probably need to do something like
```bash
go get -u github.com/AllenDang/giu@master
```
to update your giu dependency version to latest code
