### ISSUE TITLE
How to know which TabItem is active?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#176]
```go
g.TabBar("TabBar").Layout(
	g.TabItem("Encryption/decryption").Layout(
		...
	),
	g.TabItem("Shredder").Layout(
		...
	),
	...
)
```

Sorry if I'm creating a lot of issues. Is there a way to know which tab is currently active? I looked in the widgets.go under examples but I couldn't find a way to do it. I tried

```go
g.TabItem("Encryption/decryption").Layout(
	...
).OnClick(),
```

but it seems like OnClick doesn't exist for TabItem. Is there a way to know which tab is currently active? Thank you.

**Comment by AllenDang** [comment]
@HACKERALERT You could use g.IsItemActive() to check whether a tab is active.
```go
g.TabItem("Multiline Input").Layout(
  g.Custom(func() {
	  if g.IsItemActive() {
		  fmt.Printf("Active %v\n", time.Now())
	  }
  }),
  g.Label("This is first tab with a multiline input text field"),
  g.InputTextMultiline("##multiline", &multiline).Size(-1, -1),
),
```
