### ISSUE TITLE
How to move objects?

### ISSUE THREAD

**Issue by Numenorean** [AllenDang/giu#177]
Is there any way to do this? Or can i just remove them and add afterwards?

**Comment by Numenorean** [comment]
As I understand I shouldn't add this object manually, but with custom widget(there will be if condition move object or not) and then(or before building object) add Dummy, then increment width or height?

**Comment by AllenDang** [comment]
@Numenorean To move object horizontally in a line, use Dummy and update it's width as a spacer to change the location of the widget next to it. Note you could use negative number as width and height.

**Comment by Numenorean** [comment]
> @Numenorean To move object horizontally in a line, use Dummy and update it's width as a spacer to change the location of the widget next to it. Note you could use negative number as width and height.

 Can I do the same with height? I believe it is impossible because of the structure of layers that statically generated

**Comment by AllenDang** [comment]
@Numenorean It's possible. Try below code. Group will create a column in same row.
```go
g.Line(
  g.Label("Label in same line"),
  g.Group().Layout(
    g.Dummy(1, 100),
    g.Label("Label in same line 2"),
  ),
)
```

**Comment by Numenorean** [comment]
> @Numenorean It's possible. Try below code. Group will create a column in same row.
> 
> ```go
> g.Line(
>   g.Label("Label in same line"),
>   g.Group().Layout(
>     g.Dummy(1, 100),
>     g.Label("Label in same line 2"),
>   ),
> )
> ```

OH, I see. But is there any way to move it on vertical and horizontal in the same time?

**Comment by AllenDang** [comment]
@Numenorean Oh man.... I don't know what to say...
Combine Group with Line. 
```go
g.Line(
  g.Label("Label in same line"),
  g.Group().Layout(
    g.Dummy(1, 100),
    g.Line(
      g.Dummy(...),
      g.Label("Label in same line 2"),
    ),
  ),
)
```

**Comment by Numenorean** [comment]
> @Numenorean Oh man.... I don't know what to say...
> You asked how to move horizontally, I said using Line + Dummy.
> And you asked how to move vertically, I said using Line + Group.
> Now you asked how to move them together, Line + Group + (Line + Dummy).
> The answer is so clear.
> 
> Your question makes me feels very sad...
> 
> Demo code here.
> 
> ```go
> g.Line(
>   g.Label("Label in same line"),
>   g.Group().Layout(
>     g.Dummy(1, 100),
>     g.Line(
>       g.Dummy(...),
>       g.Label("Label in same line 2"),
>     ),
>   ),
> )
> ```

Thanks, and relax :) It doesn't work for me because I changed both height and width in the same Dummy
