### ISSUE TITLE
Question: why don't switch to upstream-based (inkyblackness/imgui-go) imgui copy

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#179]
Hi!
Current giu stuff uses hard-modified [imgui-go repository](https://github.com/AllenDang/imgui-go)  with completely changed structure.
This imgui copy is really hard to sync with [upstream](https://github.com/inkyblackness/imgui-go) so, also [GIU](https://github.com/AllenDang/giu) can't follow the [Dear ImGui's base](https://github.com/ocornut/imgui).
Is it possible to make updates simplier?

**Comment by gucio321** [comment]
for example:
I want to add [this VSliderFloat widget](https://github.com/inkyblackness/imgui-go/blob/bed7fdfcba8248960e3d8a6aa251bc8665340d9d/Widgets.go#L502)
so first, I need to update [AllenDang/imgui-go](https://github.com/AllenDang/imgui-go).
I need to manually copy-paste VSliderFloat's stuff into imgui.go file.
It'd be much easier to just use `git cherry-pick`, right?
Also, if some bug appears, it is reported in upstream, and upstream's developers fixes it, we need to manually identity the bug, bugged lines and fix it.

**Comment by AllenDang** [comment]
@gucio321 I'd rather use a modified version so I could direclty change something and test in a short time. The thing I usually do is not copy somthing from imgui-go but hand-write the changes.

**Comment by gucio321** [comment]
> Frankly speaking, I don't think to cooperate with upstream repo is a good idea.

You don't need to cooperate with imgui-go. You can use your own fork / new repo, but you'd be able to cherry-pick something from imgui-go. 

lets tell, that you have a clear fork of imgui-go. You can make some changes and push them, but you can still update from upstream. in my opinion, it would take less work to keep the repository up-to-date, right?

**Comment by AllenDang** [comment]
@gucio321 To this question, the reason why don't switch to upstream-based repo, is clear. For cherry-pick, yes, that will take less work. Thing is I don't cherry-pick for a long time cause my update goes faster :P

**Comment by gucio321** [comment]
oky, @AllenDang thanx for your answer!
