### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by remeh** [AllenDang/giu#18]
You've noted in the README that you may need some help for the Linux testing, I can probably do that for you.

As far as I've tested it, giu works well on Linux, everything I've tested in the `widgets` example worked well. The `dynamicloadfont` did not work though, even by providing a correct path to a valid `ttf` font but the error doesn't look alarming:

```
panic: Assertion failed!
File: imgui.cpp, Line 3508

Expression: g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8() ?"
```

Thanks for the lib, it is awesome and I'll probably use it for a personal project. Please let me know what I could do if you need further testing :+1:

**Comment by AllenDang** [comment]
Thanks very much! All the demo in examples works except dynamicfont?

**Comment by AllenDang** [comment]
@remeh Can you provide the changed dynamicfont code which reports the error?

**Comment by remeh** [comment]
@AllenDang I'll do that asap!

**Comment by remeh** [comment]
Hey @AllenDang I had the chance to look into this again:

![image](https://user-images.githubusercontent.com/1798689/74092995-52bb1e80-4acc-11ea-890a-f15fa6f126d2.png)

I've runned all examples succesfully! Even the dynamicfont works in the end, I've just had to:
  - change the font used to a TTF one (I don't have any `.ttc` available unfortunately and a quick Google search didn't do it)
  - because of this, had to switch to `AddFontFromFileTTF`

But worked perflectly :ok_hand: Here's the diff for completeness:

```diff
diff --git a/examples/dynmiacloadfont/dynamicloadfont.go b/examples/dynmiacloadfont/dynamicloadfont.go
index 4b738bc..a5c4859 100644
--- a/examples/dynmiacloadfont/dynamicloadfont.go
+++ b/examples/dynmiacloadfont/dynamicloadfont.go
@@ -11,17 +11,17 @@ func loadFont() {
        ranges := imgui.NewGlyphRanges()

        builder := imgui.NewFontGlyphRangesBuilder()
-       builder.AddText("铁憨憨你好！")
+       builder.AddText("铁憨憨你好！ Helowrd")
        // builder.AddRanges(fonts.GlyphRangesChineseFull())
        builder.BuildRanges(ranges)

-       fontPath := "/System/Library/Fonts/STHeiti Light.ttc"
-       fonts.AddFontFromFileTTFV(fontPath, 12, imgui.DefaultFontConfig, ranges.Data())
+       fontPath := "/usr/share/fonts/TTF/DejaVuSansMono.ttf"
+       fonts.AddFontFromFileTTF(fontPath, 12)
 }

 func loop() {
        g.SingleWindow("dynamic load font", g.Layout{
-               g.Label("你好啊世界！铁憨憨"),
+               g.Label("你好啊世界！铁憨憨 Hello world"),
        })
 }

```

**Comment by AllenDang** [comment]
@remeh Thank you sooooo much for helping me on this. Feel free to open issue if you meet any bug or inconvinient or suggestion. :P
