### ISSUE TITLE
Help with basic split window

### ISSUE THREAD

**Issue by citizenrich** [AllenDang/giu#181]
Hi, thanks for the cool product! I'm trying to modify the splitter example to create a basic vertical split but not succeeding. I'd like just a left and right window. Can I have a hint on how to do so? Sorry for bothering, and again, thanks for this repo.

**Comment by AllenDang** [comment]
@citizenrich You mean create a split layout without enabling drag resizing? It's simple.
```go
g.Row(  <- create a row layout, place two child panel side by side horizontally.
  g.Child(...).Size(100, -1), <- create left child panel with width 100, and adapt window's height.
  g.Child(...).Size(-1, -1),   <- create right child panel with width and height adapt remain space.
)
```

**Comment by citizenrich** [comment]
Thanks @AllenDang!
