### ISSUE TITLE
GUYS I NEED YOUR HELP!!! To enpower giu to display text from any language.

### ISSUE THREAD

**Issue by AllenDang** [AllenDang/giu#185]
Hi guys.

The font setting issue is a pain of giu. It blocks the hope to create universal application which aim to display text from any language.

I always need to deal with the font and glyph range before send my application to friends for different county.

After a long time search and lots of experiments, I refined the font system in master branch, to implement a mechanism which could build font atlas according to all strings about to be displayed in UI.

The solution is:
1. Pre define a font list for different languages for different os.
2. Try to find usable font after init.
3. Gather all strings need to be displayed.
4. Build font atlas between drawing frame.

Code is:
```go
	// Pre-register fonts
	os := runtime.GOOS
	switch os {
	case "darwin":
		// English font
		registerDefaultFont("Menlo", 14)
		// Chinese font
		registerDefaultFont("PingFang", 15)
		// Jananese font
		registerDefaultFont("ヒラギノ角ゴシック W0", 15)
		// Korean font
		registerDefaultFont("AppleSDGothicNeo", 15)
		// TODO add more fonts for different languages.
	case "windows":
		// English font
		registerDefaultFont("Calibri", 14)
		// Chinese font
		registerDefaultFont("MSYH", 15)
		// TODO add more fonts for different languages.
	}

```

Related code is located at `FontAtlasProcessor.go`.

Currently it works well on MacOS with Chinese, Japanese and Korean characters. But I need your help to tell me whats the default fonts for different os.

Please help me on this. Create a PR or just tell me the font name is more then welcome!

**Comment by barnsza** [comment]
The default font on Windows for English and probably a few other languages (see the list of supported code pages on the website) is Segoe UI size 9, which is presumably scaled up for HDPI screens. I'm currently using it at size 16 and it still seems small (my content scale is set to 1.75). Link to font information: https://docs.microsoft.com/en-us/typography/font-list/segoe-ui

**Comment by AllenDang** [comment]
@barnsza Thanks for the information. Font related part is trivial and complicate, different OS version comes with different default font, and different font comes with different drawing size. But I think this is something that a common GUI framework must conquer. I will follow your clue and work them out.
