### ISSUE TITLE
DPI scaling issue in v0.5.5

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#186]
It seems that a change in v0.5.5 has caused the DPI scaling to break (which wasn't present in v0.5.4). This is what things look like in v0.5.5:
![Screenshot (16)](https://user-images.githubusercontent.com/48808396/118700910-23bc4e00-b7e1-11eb-8521-7aeff6c3ee2c.png)
As you can see, things are not aligned properly and the font is huge. When I used v0.5.4, everything fit in the window and the buttons on the right were all aligned properly. This is what v0.5.4 looked like:
![Screenshot (17)](https://user-images.githubusercontent.com/48808396/118701752-15226680-b7e2-11eb-9879-418328ce667d.png)

I don't know much about how the internals work, although I know that commit 63251c65b872d0005682354219eee1e3e03973c9 (last commit of v0.5.4 I think) works like it should, and the next commit (694025951bc2bfe4a0cff25996287337317a85d3, first of v0.5.5 I think) caused the DPI issues.

**Comment by AllenDang** [comment]
Thanks to report this. Can you tell me your OS and are you using a high DPI screen?
If you are using Windows with hight DPI, please help me to do some test.

Find giu source code folder, should be $GOPATH/src/github.com/AllenDang/giu, open `FontAtlasProsessor.go`, go to line 49, you will find font settings there.

Change the engilish font's size, increase or decrease, and run `examples/widgets` to see which value is suitable for your situation.

**Comment by HACKERALERT** [comment]
Sure! It's a little late today, so I'll test things if I have time tomorrow.

**Comment by AllenDang** [comment]
@HACKERALERT Thanks very much!

**Comment by HACKERALERT** [comment]
What is the name of the previous monospace font used in v0.5.4? I can only figure out the appropriate size if I can compare it to v0.5.4 with the same font. So far, Calibri@10 seems like it fits, but I can give an exact number if I know the original font.

**Comment by HACKERALERT** [comment]
Also, since you've been working with fonts recently, is there a way to display unicode? I have a password box, and I would like to display `👁` next to the box to unmask the password, but it just shows up as `?`.

**Comment by AllenDang** [comment]
@HACKERALERT I just pushed a update for the font scaling, can you help to try it? How the font size looks now?
For the colorful emoji, I'm working on it now, there are still some issues but I think I will figure them out.

**Comment by HACKERALERT** [comment]
Sure, I can try that tomorrow when I have time.

**Comment by HACKERALERT** [comment]
@AllenDang The font works properly now. The font size is perfect:
![Screenshot (18)](https://user-images.githubusercontent.com/48808396/118985180-3bfcac00-b94c-11eb-80e9-e53def620290.png)
The buttons aren't aligned and the content is a little longer than the window because I had hard coded a `g.Dummy(x,0)`, and since the font's width is different from the previous font, there's some minor layout shifts (which I can easily fix). So, everything works fine now. Thanks!

Do you happen to know what the original terminal-like font was called in v0.5.4? I really loved that font and it would be nice if I could continue to use it as opposed to the new Calibri.

**Comment by AllenDang** [comment]
@HACKERALERT Glad to hear that. One trick may help you to align the button easily, use negative number as the width of g.Dummy, like g.Dummy(-100, 0) will make it occupy avaialbe space minus 100.
And for the default font, it's kind of blurry compare with default UI font comes with OS. It's not easy to change default font by now. It's name is `ProggyClean.ttf`, you could find it at `https://github.com/ocornut/imgui/tree/master/misc/fonts` if you insist to change.

**Comment by HACKERALERT** [comment]
> One trick may help you to align the button easily, use negative number as the width of g.Dummy, like g.Dummy(-100, 0)

Thank you very much for letting me know. This will make it _a lot_ easier to align the buttons properly. Since everything is solved, I'll close this issue. Thanks for your help, and I wish you good luck in continuing development of this awesome GUI. It's my go to Go GUI library because it's so small and fast.
