### ISSUE TITLE
FR: Support OpenGL 2.1 for Raspberry Pi 4

### ISSUE THREAD

**Issue by SamClarke2012** [AllenDang/giu#187]
Great job on this project, I really like it!  Any chance of porting it to the Raspberry Pi 4 (opengl 2.1)? 

I've had a quick attempt at getting imgui-go / giu running on the raspberry pi 4 (using a 60hz hi-res DPI touchscreen) by changing the go-gl / glfw versions to 2.1, but the code seems to hang before creating a window. I can't see any problems using LIBGL_DEBUG=verbose etc.  I expect that the v2.1 API isn't compatible with 3.2. 

I think the raspberry pi would be a great platform for your code!

**Comment by AllenDang** [comment]
@SamClarke2012 This should create a new renderer based on opengl 2.1. Frankly I'm not familiar with opengl, the reason I choose opengl 3.2 is simply think that higher version means better implementation...

**Comment by SamClarke2012** [comment]
@AllenDang I'm not familiar with opengl, but I am familiar with golang.  If I manage to get it working I'll let you know what was required.   The screen I'm using is running via a highspeed interface on the Raspberry Pi, but it's not on the PCI bus like opengl expects.  I'll run some tests via the HDMI ports when I get the time.🤞

**Comment by SamClarke2012** [comment]
To get it working for a Raspberry Pi 4,  you just need to force the version.  The latest drivers use 3.1/2 GLES (not 2.1), which is close enough. 

`MESA_GL_VERSION_OVERRIDE=3.3`

Hopefully this helps someone else!

Keep up the great work Allen! I look forward to seeing this project develop into the future.
![pi4_opengl3_3](https://user-images.githubusercontent.com/1995384/118788102-4a619f80-b848-11eb-834c-d7c5562ec200.png)

**Comment by AllenDang** [comment]
@SamClarke2012 May you help me to do one more thing, preload some default fonts for Raspberry Pi platform. In `FontAtlasProsessor.go` I've create default fonts of English, Chinese and Japanese for Windows and MacOS, do you think we could do the same for RaspBerry Pi? Or it doesn't ship with any default font at all?

**Comment by SamClarke2012** [comment]
@AllenDang, sure.  I just had a look, and `/usr/share/fonts` is empty.  This is the latest Pi image (downloaded today).  A quick search seems to indicate that people tend to install fonts as required.  

I guess you could package up an opensource font to float the demo examples across platforms?

**Comment by AllenDang** [comment]
@AllenDang Got it. CJK fonts are huge (usually 10~20 MB) to ship with the package.
