### ISSUE TITLE
widgets/inputintwidget: support for `uint32`

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#188]
Yo,
I need to use `giu.InputInt(...)` for displaying `uint32` value, but it is impossible for larger values.
the reason is obvious: max int32 value = 2^31
max uint32 = 2^32

Is it possible to do it althought? is this issue related with `giu` or I need to go higher; to the imgui-go and `Dear ImGui`?

**Comment by AllenDang** [comment]
@gucio321 You could use a string as the bridge to work with uint32.

```go
package main

import (
	"fmt"
	"strconv"

	g "github.com/AllenDang/giu"
)

var (
	str string
	i   uint64
)

func loop() {
	g.SingleWindow("hello world").Layout(
		g.InputText("Uint32", &str).Flags(g.InputTextFlags_CharsDecimal).OnChange(func() {
			i, _ = strconv.ParseUint(str, 10, 32)
		}),
		g.Label(fmt.Sprintf("The value of uint64 is %d", i)),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```
