### ISSUE TITLE
How to increase font size?

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#190]
The default font on Kali Linux is pretty small and not clear. How to increase the font size or use some other font line "FiraCode" ?
![font](https://user-images.githubusercontent.com/4710875/119271134-cd14a100-bc32-11eb-8a53-6da6144efea2.png)

**Comment by AllenDang** [comment]
@aj3423 Can you tell me the default UI font's file name using by OS? I could add it to giu. Or refer `FontAtlasProcessor.go` and createa PR directly. Currently giu could adapte font for MacOS and Windows, but not Linux because I dont have any experience about it.

**Comment by AllenDang** [comment]
@aj3423 If you just need to set font once for this application you are making, you could use giu.AddFont.
```go
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	content string
)

func loop() {
	g.SingleWindow("hello world").Layout(
		g.Label("Hello world from giu"),
		g.InputTextMultiline("##content", &content).Size(-1, -1),
	)
}

func main() {
	g.AddFont("STHeiti", 15)
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by aj3423** [comment]
@AllenDang I tried the code, but the font is not changed, I tried "STHeiti", "FiraCode", or some other font, it looks the same as the previous image. I'm using Kali linux, the default system font is "Fira Code Medium" size 10.

**Comment by AllenDang** [comment]
@aj3423 Just confirm, runtime.GOOS is 'linux' and the default font name is `FiraCode-Medium.ttf` right?

**Comment by aj3423** [comment]
@AllenDang Yes runtime.GOOS is 'linux', the default font name is `FiraCode-Medium.ttf`.
I tried the code, it works, the gui font is changed to FiraCode.

**Comment by AllenDang** [comment]
@aj3423 Can you make a PR for this?

**Comment by aj3423** [comment]
@AllenDang I created a PR(https://github.com/AllenDang/giu/pull/192) , I'm new to creating PR, don't know if I did it right :)
But the `AddFont` function seems not work, sometimes I need to increase the font size, how to do that?

**Comment by AllenDang** [comment]
@aj3423 Thanks very much!
