### ISSUE TITLE
Is is possible to create tree grid? 

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#194]
The tree grid I want:

![1](https://user-images.githubusercontent.com/4710875/119483476-969c6a80-bd87-11eb-8ce5-e8f45b472d36.png)

The Image is a demo screenshot from [https://github.com/ocornut/imgui](url), but I don't find the implementation code.

 I tried:
```go

package main

import (
    "github.com/AllenDang/giu"
    "github.com/AllenDang/imgui-go"
)

func loop() {
    row1 := giu.TableRow(
        giu.TreeNode(`parent`).Layout(
            giu.TableRow(
                giu.TreeNode(`child`),
                giu.Label(`ch1`),
                giu.Label(`ch2`),
            ),
        ),
        giu.Label(`p1`),
        giu.Label(`p2`),
    )

    giu.SingleWindow(`win`).Layout(
        giu.Table(`table`).Columns(
            giu.TableColumn(`Column_1`),
            giu.TableColumn(`Column_2`),
            giu.TableColumn(`Column_3`),
        ).Rows(row1),
    )
}

func main() {
    wnd := giu.NewMasterWindow("app", 400, 300, 0)
    imgui.StyleColorsLight()
    wnd.Run(loop)
}
```

It shows:
![2](https://user-images.githubusercontent.com/4710875/119483518-a156ff80-bd87-11eb-9890-282ef1245ed5.png)

How to fix it ? Thanks.

**Comment by AllenDang** [comment]
@aj3423 Currently giu doesn't suppor to build tree grid yet. I'm trying to find a proper implmentation. Feedback to you later when it's done.

**Comment by aj3423** [comment]
@AllenDang Thanks. Looking forward to that.

**Comment by AllenDang** [comment]
@aj3423 It's done. TreeTable widget is ready to use.
