### ISSUE TITLE
How to center a widget in the window?

### ISSUE THREAD

**Issue by nilopaim** [AllenDang/giu#199]
Is there a way to do this, no matter the size of the window? And by center, it means horizontally and/or vertically.

By the way, nice software! Congratulations!

**Comment by AllenDang** [comment]
@nilopaim You will have to calcuate the widget size manually and use dummy to span space.
Here is a demo to place a button in the center of a window.
```go
package main

import (
	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow("hello world").Layout(
		g.Custom(func() {
			// Get availabel region size
			width, height := g.GetAvaiableRegion()

			// Estimate widget size
			buttonWidth, buttonHeight := g.CalcTextSize("Centered button")
			buttonWidth += 16
			buttonHeight += 16

			// Place a row layout
			g.Row(
				// Use dummy to span leading space
				g.Dummy(width/2-buttonWidth/2, 0),
				// Place a column layout
				g.Column(
					// User dummy to span heading space
					g.Dummy(0, height/2-buttonHeight/2),
					g.Button("Centered button"),
				),
			).Build()

		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by nilopaim** [comment]
@AllenDang Thanks! Exactly what I need!

**Comment by ItsVoltz** [comment]
> @nilopaim You will have to calcuate the widget size manually and use dummy to span space.
> Here is a demo to place a button in the center of a window.
> 
> ```go
> package main
> 
> import (
> 	g "github.com/AllenDang/giu"
> )
> 
> func loop() {
> 	g.SingleWindow("hello world").Layout(
> 		g.Custom(func() {
> 			// Get availabel region size
> 			width, height := g.GetAvaiableRegion()
> 
> 			// Estimate widget size
> 			buttonWidth, buttonHeight := g.CalcTextSize("Centered button")
>                         // Add button frame padding
> 			buttonWidth += 16
> 			buttonHeight += 16
> 
> 			// Place a row layout
> 			g.Row(
> 				// Use dummy to span leading space
> 				g.Dummy(width/2-buttonWidth/2, 0),
> 				// Place a column layout
> 				g.Column(
> 					// User dummy to span heading space
> 					g.Dummy(0, height/2-buttonHeight/2),
> 					g.Button("Centered button"),
> 				),
> 			).Build()
> 
> 		}),
> 	)
> }
> 
> func main() {
> 	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
> 	wnd.Run(loop)
> }
> ```

Yeah but how can we do it with inputs? I wanna just center every widget on my UI, except I cant seem to find correct padding for inputs etc...

**Comment by AllenDang** [comment]
@ItsVoltz The size of input could be set explicitly with Size() method. And you could the the width of label text by CalcTextSize().

**Comment by ItsVoltz** [comment]
> @ItsVoltz The size of input could be set explicitly with Size() method. And you could the the width of label text by CalcTextSize().

Yes I did this, however the differences in the widths of the text labels cause the center to be off a few pixels, I tried doing a blank label and doing a label myself but then the horizontal padding looked funky

**Comment by AllenDang** [comment]
@ItsVoltz Can you describe more clear what are you trying to archive (a simple layout painting will be helpful)? Let me see what I can do to help.

**Comment by ItsVoltz** [comment]
> @ItsVoltz Can you describe more clear what are you trying to archive (a simple layout painting will be helpful)? Let me see what I can do to help.
Alright, so here is my UI: 
![kAnlUNI](https://user-images.githubusercontent.com/29076540/121549592-fe83bf80-c9db-11eb-92f9-c5dcf5f0ec33.png)

My Loop: 
```go
func Loop() {
	g.SingleWindow("Astolfo").Layout(
		g.Label("Astolfo"),
		g.Child("login").Layout(
			g.InputText("username", &user),
			g.InputText("password", &pass).Flags(g.InputTextFlags_Password),
			g.Row(
				g.Button("Login").Size(115, 20),
				g.Button("Exit").Size(115, 20).OnClick(func() {
					os.Exit(0)
					}),
				),
			),
		)
}
```

By default all widgets are aligned to the left, I want everything to be aligned horizontally to the center

**Comment by ItsVoltz** [comment]
Bump
