### ISSUE TITLE
Change window icon?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#203]
I created a giu program. When I run it, the window doesn't have an icon (as I expected). I used the Resource Hacker to change the icon of the executable, but when I run it, the window icon is still the generic program icon, not the one I set it to. Is there a way to set the window icon of a giu program? Perhaps a GLFW function or imgui function? Thank you.

**Comment by AllenDang** [comment]
@HACKERALERT Use Resource Hacker, add an Icon named 'GLFW_ICON'.

**Comment by HACKERALERT** [comment]
Great, that makes sense. Thank you!
