### ISSUE TITLE
giu.Selectable: how to set double-click event

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#204]
Hi,
I need to handle event on `giu.Selectable` when it is double-clicked
<details><summary>I wrote a following code</summary>

```golang
package main

import (
	"fmt"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow("Test").Layout(
		giu.Selectable("double-click me").OnClick(func() {
			fmt.Println("I was clicked")
			if giu.IsMouseDoubleClicked(giu.MouseButtonLeft) {
				fmt.Println("I was double clicked")
			}
		}),
	)
}

func main() {
	wnd := giu.NewMasterWindow("double click", 640, 480, 0)

	wnd.Run(loop)
}
```

</details>

But I never see "I was double clicked" message

**Comment by AllenDang** [comment]
@gucio321 Use event detector code like this.

```go
package main

import (
	"fmt"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow("Test").Layout(
		giu.Selectable("double-click me"),
                 giu.Custom(func() {
                         if giu.IsMouseDoubleClicked(giu.MouseButtonLeft) {
				fmt.Println("I was double clicked")
			}                
                }),
	)
}
```

**Comment by gucio321** [comment]
@AllenDang but this code also prints `I was double clicked` when you click outside of `double-click me` selectable

**Comment by AllenDang** [comment]
@gucio321 Sorry, I missed a flag. Here is the code.
```go
		g.Selectable("Double click me").Flags(g.SelectableFlagsAllowDoubleClick),
		g.Custom(func() {
			if g.IsMouseDoubleClicked(g.MouseButtonLeft) {
				fmt.Println("Double click detected")
			}
		}),

```

**Comment by gucio321** [comment]
@AllenDang, but double-click out of `Selectabl` box, still prints `Double click detected`. The message should be only displayed, when double-clicking on `Double click me`

**Comment by AllenDang** [comment]
@gucio321 Sorry again. I should check whether selectable is hovered first. Here is the code.
```go
		g.Selectable("Double click me").Flags(g.SelectableFlagsAllowDoubleClick),
		g.Custom(func() {
			if g.IsItemHovered() && g.IsMouseDoubleClicked(g.MouseButtonLeft) {
				fmt.Println("Selectable is double clicked")
			}
		}),
```

**Comment by gucio321** [comment]
ok, works fine, thank you

**Comment by gucio321** [comment]
@AllenDang one more question:  Is `g. SelectableFlagsAllowDoubleClick` necessary? It seems working without that.

**Comment by AllenDang** [comment]
@gucio321 The flags will make selectable report Click event when it is DClicked. So in your scenario, it is unnecessary.
