### ISSUE TITLE
Do not bring MasterWindow to foreground

### ISSUE THREAD

**Issue by valentinEmpy** [AllenDang/giu#206]
Hi folks,
I do not see such a feature implemented - is it possible to make the master window unfocusable (not come to the foreground on mouse click).
I am trying to achieve something similar to a window with flags (WS_EX_NOACTIVATE | WS_EX_TOPMOST | WS_EX_LAYERED).
Could this be achieved? If not I'd be interested to dive into the topic and possibly contribute.
Thanks!

**Comment by AllenDang** [comment]
@valentinEmpy Currently it is not implemented. Giu is based on GLFW, so I did a quick check, here is the window related attributes.
```go
// Window related hints/attributes.
const (
	Focused                Hint = C.GLFW_FOCUSED                 // Specifies whether the window will be given input focus when created. This hint is ignored for full screen and initially hidden windows.
	Iconified              Hint = C.GLFW_ICONIFIED               // Specifies whether the window will be minimized.
	Maximized              Hint = C.GLFW_MAXIMIZED               // Specifies whether the window is maximized.
	Visible                Hint = C.GLFW_VISIBLE                 // Specifies whether the window will be initially visible.
	Hovered                Hint = C.GLFW_HOVERED                 // Specifies whether the cursor is currently directly over the content area of the window, with no other windows between. See Cursor enter/leave events for details.
	Resizable              Hint = C.GLFW_RESIZABLE               // Specifies whether the window will be resizable by the user.
	Decorated              Hint = C.GLFW_DECORATED               // Specifies whether the window will have window decorations such as a border, a close widget, etc.
	Floating               Hint = C.GLFW_FLOATING                // Specifies whether the window will be always-on-top.
	AutoIconify            Hint = C.GLFW_AUTO_ICONIFY            // Specifies whether fullscreen windows automatically iconify (and restore the previous video mode) on focus loss.
	CenterCursor           Hint = C.GLFW_CENTER_CURSOR           // Specifies whether the cursor should be centered over newly created full screen windows. This hint is ignored for windowed mode windows.
	TransparentFramebuffer Hint = C.GLFW_TRANSPARENT_FRAMEBUFFER // Specifies whether the framebuffer should be transparent.
	FocusOnShow            Hint = C.GLFW_FOCUS_ON_SHOW           // Specifies whether the window will be given input focus when glfwShowWindow is called.
	ScaleToMonitor         Hint = C.GLFW_SCALE_TO_MONITOR        // Specified whether the window content area should be resized based on the monitor content scale of any monitor it is placed on. This includes the initial placement when the window is created.
)
```
The mose related attributes are FocusOnShow and Floating. Seems it lacks NO_ACTIVATE.

**Comment by valentinEmpy** [comment]
@AllenDang 
After digging a little bit, I was able to achieve what I wanted by using the win32 API and modify the "extended window styles" programmatically: https://pastebin.com/B5SwjFNp
The result is a fully transparent, click-through window.
Just for reference if anyone needs to achieve this.

**Comment by VityaSchel** [comment]
> @AllenDang After digging a little bit, I was able to achieve what I wanted by using the win32 API and modify the "extended window styles" programmatically: https://pastebin.com/B5SwjFNp The result is a fully transparent, click-through window. Just for reference if anyone needs to achieve this.

@valentinEmpy 
Hi! I'm new to go, can you specify what "mem" is? Did you use currently unavailable library or is that standart lib?

**Comment by VityaSchel** [comment]
For anyone coming here in the future, I found that imports has to be
```
import (
    "fmt"
    "github.com/TheTitanrain/w32"
    "errors"
    "syscall"
)
```
and you should rename and place main function in the end of loop() function in giu module
