### ISSUE TITLE
widgets/PopupModal: using `IsOpen` method doesn't work properly

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#208]
Hi there,
I want my PopupModal opens, when I change some variable value to `true`
<details><summary>code looks like that</summary>

```golang
package main

import (
	"github.com/AllenDang/giu"
)

var isOpen bool = false

func main() {
	wnd := giu.NewMasterWindow("close-popup", 640, 480, 0)
	wnd.Run(loop)
}

func loop() {
	giu.Window("open popup").Layout(
		giu.Button("open popup").OnClick(func() {
			isOpen = true
		}),
		giu.PopupModal("popup").Layout(
			giu.Button("Close Me").OnClick(func() {
				isOpen = false
			}),
		).IsOpen(&isOpen),
	)
}
```

</details>

but any popup isn't opened, when I click the button.
Is it possible to do that without calling `giu.OpenPopup(...)`?

**Comment by AllenDang** [comment]
You can use a bool to control popup like this, but I don't think it's elegent.
```go
package main

import (
	"github.com/AllenDang/giu"
)

var isOpen bool = false

func main() {
	wnd := giu.NewMasterWindow("close-popup", 640, 480, 0)
	wnd.Run(loop)
}

func loop() {
	giu.Window("open popup").Layout(
		giu.Button("open popup").OnClick(func() {
			isOpen = true
		}),
		giu.Custom(func() {
			if isOpen {
				giu.OpenPopup("popup")
			}
		}),
		giu.PopupModal("popup").Layout(
			giu.Button("Close Me").OnClick(func() {
				isOpen = false
			}),
			giu.Custom(func() {
				if !isOpen {
					giu.CloseCurrentPopup()
				}
			}),
		),
	)
}
```

**Comment by gucio321** [comment]
hmm, @AllenDang I just found this: https://github.com/ianling/giu/commit/98573db688bb981afbf9b000689dce792bd7c344 what do you think about `cherry-pick`?

**Comment by AllenDang** [comment]
@gucio321 I don't think it's a good idea. IsOpen is a indicator to check whether the popup is opened. If we use it to trigger the open event, it should be able to trigger close event by setting it to false. It's kind of violate the purpose just for a grammer sugar.

**Comment by AllenDang** [comment]
@gucio321 I know the pain for popup, as they have to be placed at the same level where the open method is invoked. I'm thinking about how to solve it properly.

**Comment by gucio321** [comment]
@alldndang why are there two ways to open/manage open-state of popups?
1. IsOpen method
2. giu.OpenPopup(...), giu.CloseCurrentPopup()

**Comment by AllenDang** [comment]
IsOpen is used to check whether the popup is opened. In case you need to do some background operation when some popup is opened.

**Comment by gucio321** [comment]
but why couldn't it be used to manage PopUp's state?
e.g., you can do:
```golang
var isOpen bool
// ...
g.PopupModal("...").IsOpen(&isOpen).Layout(
   g.Button("close me").OnClick(func() { isOpen = false }),
),
```

**Comment by AllenDang** [comment]
It will break the mechanism how popup works in imgui. I know current implementation causes many misunderstanding, so does the author of imgui. I noticed this part will be refined in near future, so I intend to wait few releases of imgui.
