### ISSUE TITLE
no `FireCode-Medium` font on fedora-linux

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#209]
Hi there,
I see a following warning on my machine:
```console
[Warning]Cannot find font FiraCode-Medium at system, related text will not be rendered.
```

OS: Fedora release 32 (Thirty Two)
(on Fedora 33 the same)
Desktop: GNOME Shell 3.36.9

**Comment by AllenDang** [comment]
@gucio321 What's the default UI font for your system?

**Comment by gucio321** [comment]
@AllenDang I suppose, it is something like that
![image](https://user-images.githubusercontent.com/73652197/121004539-19152900-c78f-11eb-8fb5-669ba3abeebd.png)

**Comment by AllenDang** [comment]
@gucio321 Is there anything we could distinguish your system from kali-linux? I think runtime.GOOS should both return linux.

**Comment by gucio321** [comment]
@AllenDang I suppose, you need to use some golang module like [this](https://github.com/gravestench/osinfo)
this repo is based on a gist, so you can use this code: https://gist.github.com/flxxyz/ae3ef071dc4ffb0c55daedc7f0740611

**Comment by gucio321** [comment]
generally, you can access `/etc/*release` to get linux distribution name

**Comment by gucio321** [comment]
@AllenDang btw of fonts.
On gnome desktops, there is a config entry for default font.
you can call the following command: `gsettings get org.gnome.desktop.interface font-name`

**Comment by AllenDang** [comment]
@gucio321 I just removed the warning about missing default font message and add Cantarell as another default font for linux. Because there are too many linux distributions out there, I think I just need to add more and more default fonts for linux, and this will be much easier to do.
