### ISSUE TITLE
Label auto-wrap

### ISSUE THREAD

**Issue by pztrn** [AllenDang/giu#21]
It'll be very good if labels will auto-wrap based on parent widget/layout/window sizes.

**Comment by AllenDang** [comment]
@pztrn You could archive auto-wrap by doing this

```
g.Layout{
    g.Custom(func() {
        g.PushTextWrapPos()
        g.Label("A very long text...").Build()
        g.PopTextWrapPos()
    }),
}
```

PushTextWrapPos could work on any widget which displays text.

**Comment by pztrn** [comment]
Thanks for recipe!

This issue about providing auto-wrap, so users won't bother about custom widgets (like in all other toolkits - they have something like ``Label.SetWordWrap(true)``).

What if do something like imgui::TextWrapped (https://github.com/ocornut/imgui/issues/70) but for labels?

**Comment by AllenDang** [comment]
@pztrn Sure thing! That's really convinient. I just added a widget "LabelWrapped".

**Comment by pztrn** [comment]
Thanks, tested and it works!

**Comment by marcelloh** [comment]
this "LabelWrapped" is now gone?
