### ISSUE TITLE
There is an issue with download/install

### ISSUE THREAD

**Issue by cvq** [AllenDang/giu#210]
I try to download/install giu, but there is an issue:
+ "go get github.com/AllenDang/giu@master". This gives the following message: go: can only use path@version syntax with 'go get' and 'go install' in module-aware mode
+ "go install github.com/AllenDang/giu@master". This gives the following message: go install: package github.com/AllenDang/giu is not a main package
Please help to fix. Thank you.
My platform: windows, amd64, go 1.16.5

**Comment by AllenDang** [comment]
@cvq The error message indicates you should run it in a go project with mod enabled. If you want to install giu globally, just run 'go get github.com/AllenDang/giu`.

**Comment by cvq** [comment]
Follow your instruction, it' ok now.
Thank you.

**Comment by AllenDang** [comment]
@cvq You are right, I should update the installation instruction.
