### ISSUE TITLE
fonts: adding custom fonts

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#213]
Hi there,
In some cases, I want to add a font from my own source (e.g. byte slice) using e.g. IO().Fonts().AddFontFromMemoryTTF(...) but it looks, that font atlas rebuilder clears currently registered fonts. so how to register a font from bytes using imgui/giu? Also I need to specify a custom glyph ranges (like japanese / korean e.t.c)

**Comment by AllenDang** [comment]
@gucio321 Check the demo code located at `examples/multiplefonts`. And you don't need to specify custom glyph ranges, font atlas processer will build all the fonts in UI dynamically.

**Comment by gucio321** [comment]
@AllenDang but how to add a font from a `custom source`?
e.g. I have a font loaded into a byte slice (by go:embed) and I want to load it.
the example only shows, that I can load font from its name (using  `g.AddFont(...)`)

**Comment by AllenDang** [comment]
@gucio321 I see, I need to add a new method to do that. Get back to you later when it's ready.

**Comment by AllenDang** [comment]
@gucio321 It's done. Try the new function "AddFontFromBytes".

**Comment by gucio321** [comment]
@AllenDang this fonts stuff doesn't seems working correct:
<details><summary>code</summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	bigFont *g.FontInfo

	content = "Hello world from giu!\n你好啊世界！"
)

func loop() {
	g.SingleWindow("Multiple fonts").Layout(
		g.Label("Title line").Font(bigFont),
		g.Label("Content line"),

		g.Label("Change font for other widgets"),

		g.Style().SetFont(bigFont).To(
			g.Button("Button with big font"),
		),

		g.Button("Normal button"),

		// Show chinese characters
		g.Label("你好啊！世界"),

		// Change font for input area
		g.InputTextMultiline("##content", &content).Size(-1, -1),
	)
}

func main() {
	bigFont = g.AddFont("/home/user/fonts/DiabloBold.ttf", 24)

	wnd := g.NewMasterWindow("Multiple fonts", 600, 400, g.MasterWindowFlagsNotResizable)
	wnd.Run(loop)
}
```

</details>

![image](https://user-images.githubusercontent.com/73652197/122091520-2c686a00-ce09-11eb-97fa-39cee95cbca6.png)

this font doesn't seem to be diffrent than default

**Comment by AllenDang** [comment]
@gucio321 That means none of the default fonts can be found in your system. I've changed to logic to use default font if none of the pre-registered fonts can be found. But can you help to test what's the right font name for your system?

**Comment by gucio321** [comment]
@AllenDang I'm currently not loading any default font because of #212.
But I suppose, that `giu.Label(...).Font(...)` should change default font to this loaded by the programm...

**Comment by AllenDang** [comment]
@gucio321 Try newest code.

**Comment by gucio321** [comment]
ok, it works fine for now
