### ISSUE TITLE
how to change a default font

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#215]
Hi,
I'd like to change a default font.
Befor your font atlas refactor it was possible by `giu.IO().Fonts().AddFontFromFileTTFV(...)`
how to do that now?

**Comment by AllenDang** [comment]
The reason why I intend to create font atlas builder is, not more change default font staff should in the way to create a GUI app. This should be handled by framework itself like Qt, wxwidgets does.
I think the best way is to register a readable font in FontAtlasProcessor, create a PR, and solve this kind of issues once for all.

**Comment by gucio321** [comment]
Yah, but I'm creating an app, where I want to use my own font, not system defined font.

well, user shouldn't carry about default font, but framework should provide a feature to change it if the user want it.

**Comment by AllenDang** [comment]
@gucio321 Fair enough, SetDefaultFont is added.

**Comment by gucio321** [comment]
@AllenDang maybe `SetDefaultFont(f *FontInfo)` would be better?
if not, you also need to add `SetDefaultFontFromBytes` (#213)

**Comment by AllenDang** [comment]
@gucio321 Sure, to avoid confusion, I added SetDefaultFontFromBytes.

**Comment by gucio321** [comment]
okey, thank you
