### ISSUE TITLE
DPI awareness not working

### ISSUE THREAD

**Issue by pztrn** [AllenDang/giu#22]
Using commit bccdc445689825f69fd0c43c31d97ce713ab64d0

DPI awareness (autoscaling based on system settings, in my case - 175% in Windows 10) works only with default font. But when I tried to use another font (Go Regular) - I have to do scaling manually and choose larger font size, e.g.:

```go
func (m *mainWindow) initialize() {
	m.window = giu.NewMasterWindow("My Mega App", 1000, 750, true, m.loadFont)
	m.window.Main(m.loop)
}

func (m *mainWindow) loadFont() {
	fonts := giu.Context.IO().Fonts()

	fonts.AddFontFromMemoryTTF(goregular.TTF, 24)

	imgui.CurrentStyle().ScaleAllSizes(1.75)
}
```

Which isn't "DPI awareness" at all. Am I miss something important here, or it is a bug?

**Comment by AllenDang** [comment]
@pztrn 
Current implementation of DPI awareness is actually multiply any size with Context.GetPlatform().GetContentScale().

If you use custom font, multiply the font size with this factor will do the trick.

fonts.AddFontFromMemoryTTF(goregular.TTF, 24 * giu.Context.GetPlatform().GetContentScale()

**Comment by AllenDang** [comment]
@pztrn Btw, I'm working on wrapping font related APIs to cover that part with DPI awareness.

**Comment by pztrn** [comment]
Got:

```
panic: runtime error: invalid memory address or nil pointer dereference
```

When trying to use ``giu.Context.GetPlatform().GetContentScale()`` in loadFont func for MasterWindow. Looks like it isn't initialized at the moment when loadFontFunc is called.

**Comment by AllenDang** [comment]
@pztrn Sorry, my bad. That's a little bit tricky. I'll check if I can do it inside, get back to you later.

**Comment by AllenDang** [comment]
@pztrn I fixed this issue. Try to use platform.GetContentScale() again, it should work now.

**Comment by AllenDang** [comment]
@pztrn I've finished the DPI awareness for AddFontxxx functions. So right now you just need to AddFontXXX as usual and the size will be scaled automatically.

**Comment by pztrn** [comment]
Working, thanks!
