### ISSUE TITLE
tabbar: assign selected tab item to a variable

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#221]
lets say, I have a `TabBar` with `TabItem`s. e.g.
```golang
giu.TabBar().Layout(
       giu.TabItem("tab 1"),
       giu.TabItem("tab 2"),
),
```
how to identify/set, currently selected tab item?
e.g. to assign the number (`?`) of selected tab item to a variable

PS: very cool ID setter :grinning:

**Comment by gucio321** [comment]
btw, another question:
```golang
type TabItemWidget struct {
        label  string
        open   *bool
        flags  TabItemFlags
        layout Layout
}
```
does it make sens to put something else than `TabItem`s in `layout` field? maybe this field should be just of type `[]TabItemWidget`?

**Comment by AllenDang** [comment]
@gucio321 You are right. I've changed the TabBar.Layout to TabBar.TabItems.
And TabItemWidget.IsOpen(..) could be used to check which tab item is activated.

**Comment by AllenDang** [comment]
@gucio321 And to set selected tab item, use TabItemWidget.Flags(TabItemFlagsSetSelected).
