### ISSUE TITLE
Custom widget renders at new line even in giu.Row

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#226]
```golang
func loop() {
	giu.SingleWindow().Layout(
		giu.Row(
			giu.Button("a"),
			giu.Button("b"),
			giu.Custom(func() {
				giu.Label("c").Build()
			}),
		),
	)
}

func main() {
	Wnd := giu.NewMasterWindow("", 300, 200, 0)
	Wnd.Run(loop)
}
```

I expect the three items in one row,  but actually they are in two lines.
![111](https://user-images.githubusercontent.com/4710875/124911924-e7a6ac00-e01f-11eb-84f0-248f90b4699e.png)

**Comment by AllenDang** [comment]
@aj3423 Thanks for reporting this, it is fixed now.
