### ISSUE TITLE
Need a little help with colours

### ISSUE THREAD

**Issue by macbutch** [AllenDang/giu#227]
Hello and thank you for the excellent work here. I'm really enjoying working with giu and particularly surprised at how easy (almost) everything has been. It's really really nice.

I'm using 0.5.4 and I'm trying to understand how to customise colours. Mostly, I have it working but there's a few points that I've not figured out yet. Specifically, right now, I'm trying to find a way to change the colour of the progress bars. I'm expecting to do something that looks a lot like this:

```
	g.Style().
		SetColor(imgui.StyleColorText, textColor).
		SetColor(imgui.???, progressColor).
		To(
			g.ProgressBar(1).Overlay(status),
		),

```

Would love some help here if possible.

**Comment by AllenDang** [comment]
@macbutch Sorry for late reply. Use this
```go
g.Style().SetColor(g.StyleColorPlotHistogram, color.RGBA{...}).To(
    g.ProgressBar(...)
)
```

**Comment by macbutch** [comment]
Thanks @AllenDang! Works perfectly.
