### ISSUE TITLE
.Size(-1) is 1px less than width

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#228]
When I want to make a button take up the whole window, I use `btn.Size(-1,h)`. However, the button is 1px smaller than full size. If I use `btn.Size(-0.01,h)`, now the button takes up the whole screen. Is there a standard way in giu to make the button take up the whole window, not just to the last pixel and therefore be 1px less than the window width? Not sure about you, but being 1px off makes me feel uncomfortable :)

**Comment by AllenDang** [comment]
@HACKERALERT Currently you could calculate avaiable region and set button's width manualy.
```go
		g.Row(
			g.Label("Label before the button"),
			g.Custom(func() {
				width, _ := g.GetAvaiableRegion()
				g.Button("Button").Size(width, 20).Build()
			}),
		),

```

**Comment by HACKERALERT** [comment]
Unbelievable how there's (almost) always a way in giu to do something 🙏 . Thank you very much, keep up the awesome work!

**Comment by HACKERALERT** [comment]
@AllenDang I thought you had a typo, so I tried `g.GetAvailableRegion` (correct spelling), but it seems like that isn't defined and `g.GetAvaiableRegion` works and it's not spelled correctly. Do you plan on correcting the spelling?

**Comment by AllenDang** [comment]
@HACKERALERT You could create a PR for that :P

**Comment by HACKERALERT** [comment]
Alright, np. Do you know which file the function is defined?

**Comment by AllenDang** [comment]
@HACKERALERT I got it fixed. :P
