### ISSUE TITLE
Dropdown in TabBar?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#229]
Is there a way to put a widget in a TabBar that's not a TabBarWidget? I'd like to put a language dropdown menu on the right side of a TabBar but currently haven't thought of a possible way. For example:
![Screenshot (122)](https://user-images.githubusercontent.com/48808396/126221577-f60eb359-1aba-48c4-96ad-9f04e36c804e.png)
Thank you very much!

**Comment by AllenDang** [comment]
@HACKERALERT Try this
```go
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	items    []string
	selected int32
)

func loop() {
	g.SingleWindow().Layout(
		g.Custom(func() {
			// Save widget drawing position
			pos := g.GetCursorPos()

			g.Row(
				g.Dummy(-70, 0),
				g.Combo("##combo", "value1", items, &selected).Size(70),
			).Build()

			// Reset widget drawing position
			g.SetCursorPos(pos)

			g.TabBar().TabItems(
				g.TabItem("Tab1").Layout(
					g.Label("Content 1"),
				),
				g.TabItem("Tab2").Layout(
					g.Label("Content 2"),
				),
			).Build()
		}),
	)
}

func main() {
	items = []string{
		"value1",
		"value2",
		"value3",
	}

	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by HACKERALERT** [comment]
Oh, that is genius! Save the current position, add the widget, then reset! Many thanks for this genius solution :)
