### ISSUE TITLE
Incorrect first table line height calculation

### ISSUE THREAD

**Issue by pztrn** [AllenDang/giu#23]
First line in tables won't recalculate it's height with LabelWrapped used inside. Second line is okay:

![изображение](https://user-images.githubusercontent.com/869402/74104859-d16e9500-4b7a-11ea-9ff8-fae6d4220fa0.png)

**Comment by pztrn** [comment]
That's how table rows are generated:

```

func generateTableRow(name string, license string, buttons [][]string) *giu.RowWidget {
	row := []giu.Widget{
		giu.LabelWrapped(name),
		giu.LabelWrapped(license),
	}

	for _, btnData := range buttons {
		row = append(row, giu.Button(btnData[0], func() {
			_ = browser.OpenURL(btnData[1])
		}))
	}

	return giu.Row(row...)
}

```

**Comment by AllenDang** [comment]
@pztrn Looks like it's a but for imgui, I reported it to imgui. And I also will look into C++ part to see if I can fix it by myself.

**Comment by AllenDang** [comment]
@pztrn It's fixed. It's not a bug of imgui. This issue is on my side.

**Comment by pztrn** [comment]
Confirming, thanks!
