### ISSUE TITLE
How to use keyboard's arrows for navigation in Table?

### ISSUE THREAD

**Issue by ojanovsky** [AllenDang/giu#230]
Please, how to do keyboard's navigation in Table?

**Comment by AllenDang** [comment]
@ojanovsky Can you describe more?

**Comment by ojanovsky** [comment]
I want to use keyboard navigation in Table. Not only mouse. Arrow keys for move cursor between columns and rows, enter for action, PgUp, PgDown for scrolling ....

**Comment by AllenDang** [comment]
@ojanovsky giu currently doesn't have direct support for this. You may need to check imgui's manual directly.

**Comment by ojanovsky** [comment]
Thank you, for explanation.
