### ISSUE TITLE
Suggestion: Use universal font

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#231]
Hi Allen,

I know that you are in the process of adding multiple language fonts to giu. I have a suggestion: Use a font that contains multiple language character sets to make the look of giu universal, and also to simplify multilingual support. For example, Google's [Noto](https://www.google.com/get/noto/) font supports 582 languages:
![Screenshot (124)](https://user-images.githubusercontent.com/48808396/126347868-e660e29d-1451-4267-9353-bef132442af9.png)
So instead of adding individual fonts for specific languages, maybe use one that contains 99% of languages, and then add additional ones to fill in languages that aren't supported by Noto? My project currently is using this custom font to support Chinese and Turkish (among many others) characters, so I thought I might let you know about this, in case you didn't before. Have a great day!

**Comment by AllenDang** [comment]
@HACKERALERT Oh, thank you! I'll check it out and feedback to you.

**Comment by HACKERALERT** [comment]
I just fixed the broken link :)

**Comment by AllenDang** [comment]
@HACKERALERT I've check it and I think it's not a good solution to embed those fonts directly into giu. Cause this will increase the size (like 30+MB) of giu and make the deployment more complicate.

**Comment by HACKERALERT** [comment]
Cool, no problem. Just a suggestion, it's totally up to you :)
