### ISSUE TITLE
widgets/ImageButtonWidget: use image.rgba instead of texture arg

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#233]
Hi there,
as you know, loading textures is a bit painful, is it possible to rewrite ImageButton using `image.RGBA` instead of `Texture`? or maybe add a new type like `image` and `imageWithRGBA`

**Comment by AllenDang** [comment]
@gucio321 I think its reasonable to rewrite ImageButton. I'll do that soon, or you could create a PR?

**Comment by gucio321** [comment]
I can, just tell me, how would you like to  do that:
1. should I leave ImageButton, and add something new
2. or make ImageButtonWidget to use image.RGBA
