### ISSUE TITLE
imageWithRGBA: id generator

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#234]
https://github.com/AllenDang/giu/blob/fe0ecd71ecfc27472e790f4d64b7e29e8941197d/Widgets.go#L737
it might behave in unexpected way. e.g. what if the first 100 pixels of image is empty or you want to display the same image 2 times?

**Comment by AllenDang** [comment]
@gucio321 Yes, that's a problem. Maybe I should use AutoID, should be more robust. You think?

**Comment by gucio321** [comment]
should be better

**Comment by AllenDang** [comment]
@gucio321 It is fixed.

**Comment by gucio321** [comment]
okey, thank you
