### ISSUE TITLE
window icon

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#235]
hi there!
in reffer to #203 i found, that hajimehoshi/ebiten, which also uses GLFW provides a function to change window icon.
https://github.com/hajimehoshi/ebiten/blob/main/window.go
https://github.com/hajimehoshi/ebiten/blob/0ec5b7b8572fa023019c049c3b9e5d3358b70e6c/window.go#L92
```golang
// SetWindowIcon sets the icon of the game window.
//
// If len(iconImages) is 0, SetWindowIcon reverts the icon to the default one.
//
// For desktops, see the document of glfwSetWindowIcon of GLFW 3.2:
//
//     This function sets the icon of the specified window.
//     If passed an array of candidate images, those of or closest to the sizes
//     desired by the system are selected.
//     If no images are specified, the window reverts to its default icon.
//
//     The desired image sizes varies depending on platform and system settings.
//     The selected images will be rescaled as needed.
//     Good sizes include 16x16, 32x32 and 48x48.
//
// As macOS windows don't have icons, SetWindowIcon doesn't work on macOS.
//
// SetWindowIcon doesn't work on browsers or mobiles.
//
// SetWindowIcon is concurrent-safe.
```

also, in go-gl/glfw:
https://github.com/go-gl/glfw/blob/master/v3.3/glfw/window.go
https://github.com/go-gl/glfw/blob/ab6297867137a7647dfc93f220405887d9d40123/v3.3/glfw/window.go#L397
```golang
// SetIcon sets the icon of the specified window. If passed an array of candidate images,
// those of or closest to the sizes desired by the system are selected. If no images are
// specified, the window reverts to its default icon.
//
// The image is ideally provided in the form of *image.NRGBA.
// The pixels are 32-bit, little-endian, non-premultiplied RGBA, i.e. eight
// bits per channel with the red channel first. They are arranged canonically
// as packed sequential rows, starting from the top-left corner. If the image
// type is not *image.NRGBA, it will be converted to it.
//
// The desired image sizes varies depending on platform and system settings. The selected
// images will be rescaled as needed. Good sizes include 16x16, 32x32 and 48x48.
```

maybe it is possible to use it in giu?

**Comment by AllenDang** [comment]
@gucio321 Thanks! I will take a look.

**Comment by AllenDang** [comment]
@gucio321 I think it's not the time to set icon to window by using those apis. Currently I intend to pack resources by external cmd like rsc for windows and plist for MacOS. Reason is the resource path is platform dependent. Maybe we could facilitate resource loading related api when imgui's docker branch is merged to main.

**Comment by gucio321** [comment]
> Reason is the resource path is platform dependent.

i don't think it is the such the problem. you can do `SetWindowIcon(data []byte)` and data could be variable loaded by go:embed or anything else.

**Comment by AllenDang** [comment]
@gucio321 Make sense, I'll add it.

**Comment by gucio321** [comment]
cool, looking forward to see the feature :tada:

**Comment by AllenDang** [comment]
@gucio321 It's done!

**Comment by HACKERALERT** [comment]
@AllenDang Thanks for implementing this feature, it will be a lot easier for me to add a window icon now. I have a question. On Windows, the native icon format is .ico, for macOS it's .icns, and for Linux it's .png. Is this method currently cross platform? Thank you very much!

**Comment by AllenDang** [comment]
@HACKERALERT I quote the comment of SetIcon here.
         // SetIcon sets the icon of the specified window. If passed an array of candidate images,
	// those of or closest to the sizes desired by the system are selected. If no images are
	// specified, the window reverts to its default icon.
	//
	// The image is ideally provided in the form of *image.NRGBA.
	// The pixels are 32-bit, little-endian, non-premultiplied RGBA, i.e. eight
	// bits per channel with the red channel first. They are arranged canonically
	// as packed sequential rows, starting from the top-left corner. If the image
	// type is not *image.NRGBA, it will be converted to it.
	//
	// The desired image sizes varies depending on platform and system settings. The selected
	// images will be rescaled as needed. Good sizes include 16x16, 32x32 and 48x48.

**Comment by HACKERALERT** [comment]
So I read this thread carefully again and what I'm getting here is that I should load different sizes of my icon as image.Image/image.NRGBA and pass it in a []image.NRGBA to giu.SetWindowIcon. Great, thanks!

**Comment by gucio321** [comment]
@AllenDang thanx for implementation!
