### ISSUE TITLE
widgets/imageButton: use autoID

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#236]
hi there!
if we'll use the same texture for imageButton 2 or more times, app will crash
```golang
                if imgui.ImageButtonV(b.texture.id, imgui.Vec2{X: b.width, Y: b.height}, ToVec2(b.uv0), ToVec2(b.uv1), b.framePadding, ToVec4Color(b.bgColor), ToVec4Color(b.tintColor)) && b.onClick != nil {
```
I suggest to use auto id generator

**Comment by AllenDang** [comment]
No, the first param's type is defined in imgui, cannot change it to string here.

**Comment by gucio321** [comment]
@allenDang hmm, you're right
but is it possible to add ID method and us Push/PopID?
