### ISSUE TITLE
NewMasterWindow serialization

### ISSUE THREAD

**Issue by saucesaft** [AllenDang/giu#24]
Is there any possibility to Serialize the MasterWindow struct into a file, and then have other programs read the struct and have the capabilities of accesing giu functions as adding more windows inside the main window?
As like having a server/client architecture where the server creates the MasterWindow and writes the struct to a file while having the main window open. Then if i open the client app, it will read the struct from the file and manipulate the main window via the struct.
I don't know if i explained myself and what im trying to achieve, but is there any way of getting into what i have in mind? Thanks!

**Comment by saucesaft** [comment]
What i've been seeing is that i'll need to serialize the struct, but the struct fields are private. I made a fork and tried to change them into public by making the first letter upper case and changing other field references after but other problems came out. How can we easily make the MasterWindow struct public for easier Serialization?

**Comment by AllenDang** [comment]
A easy approach is create a Custom struct say "WindowParam", it contains all parameters to create a real master window.
And create a function to create master window like WindowBuilderFunction(param *WindowParam).

**Comment by saucesaft** [comment]
Hey, thanks for answering. You mean creating an identical struct to the MasterWindow struct? Could you develop a little more? or is there any possibility you could make the MasterWindow's fields public so that i could serialize them?
Thanks :)

**Comment by AllenDang** [comment]
```
type WindowParam struct {
  Title string
  Width, Height float32
  // whatever param of the window you need
}

func WindowBuilder(param *WindowParam) {
  wnd := giu.NewMasterWindow(param.Title, param.Width, param.Height, ...)
  ...
}
```

And I don't think make the internal param of MasterWindwo is a good idea, because changing those param will bring unnecessary risks for users.

**Comment by saucesaft** [comment]
Yeah, i understand the risk of making those fields public. But how could I export the MainWindow struct so that external programs could draw into the main window. By serializing and deserializing the main window struct. Regarding your example, I see how it could work but to assign the values to the custom struct there's need to have access to the main window struct fields so that I can assign them.
Do you have anything in mind?

**Comment by AllenDang** [comment]
@saucesaft Sorry, I don't quite understand what are you trying to do here. Can you describe more specific about the scenario?

**Comment by saucesaft** [comment]
Dont worry, let me explain more detailed.
I have 2 programs, one server and one client.
If i run the server program, it will launch a MasterWindow, with no giu/imgui subwindows inside.
If i run the client program after the server, it will open a giu/imgui subwindow inside the MasterWindow.

This is basically my idea, and i tried to implement by making the server expose the MasterWindow struct and let client programs have access to it, so the client program can open more giu/imgui window. Is there any possibility that this could be done? Thanks :)

**Comment by AllenDang** [comment]
@saucesaft It sounds like a classic Browser/Server structure. Treat your server as Browser and client as Server. Is there any special reason that you cannot simply write a http server application?

**Comment by saucesaft** [comment]
The thing is that i would like to program a DAW (Digital Audio Workstation), where there would be one big main window with many subwindows inside. I would like to have an external programs that if runned would open a subwindow inside the big main window. Kind of like a unix-philosophy DAW, where every thing should be handled by different mini programs. For example, lets say i run the file-selector app, and it will open the file-selector sub-window in the main big window, i could pipe the output of that sub-window into another sub-window lets say to modify the audio file.
The thing is that the browser isn't a viable option at the time of making DAWs, dou you have any idea of how to make this work? Also, if noting comes up, would you help me to fork the repo and modifying the MainWindow struct for making the fields public?
Thanks.

**Comment by AllenDang** [comment]
@saucesaft Base on your description, I don't think make MainWindow fields public will do any help.
Because the content of MasterWindow is created by loop function and in that function, you don't need to access any of the fieds MasterWindow has.
Here is few solutions comes to my mind.

1. MasterWindow is responsible to show giu.Layout passed from client, handle user event (button click, combo selection changed and etc...), pass the event name to client and display event processing result returned from client.

This solution provides maximum freedom to client, but the event handling mechanism is a little bit complex.

2. MasterWindow has few predefined UI block, say file-selector as example. Client only tells what UI block should be displayed and accept related data from it.

This solution is suitable if the business logic is fixed and may not change too much in future.

**Comment by saucesaft** [comment]
Really thank you for helping me.
Regarding your previous comment, i think i have some implementation ideas and seen how it could work.
For the solution 1 you shared i have the idea of having a "null" giu.Layout. But then lets say i use some ipc magic and make a request to the main program from a client. The client could have its own giu.Layout function as a variable and send it to the main program. Where it would grab the variable and use the function in the main program MainWindow's loop.
The 2 solution could be a lot easier to implement.
I have 2 last questions, one is regarding the next screenshot:
![Screenshot from 2020-02-11 23-02-23](https://user-images.githubusercontent.com/22535853/74304465-ae7ee500-4d22-11ea-8bec-31b757be6f66.png)
Instead of running the SingleWindow() function for opening just a big window i run the normal Window() function. But the weird thing is that i can't drag the window to resize or move it? Is this a bug or something.
My last question is if i can use normal imgui functions as IsItemHovered(), etc with this library?
Thanks a lot for helping! :)

**Comment by AllenDang** [comment]
@saucesaft giu.Window has a flag to indicate it's not movable, you could use giu.WindowV and specify any costom window flags you need.

And yes, giu wraps some of the event handling functions, you could find them in Events.go.

**Comment by saucesaft** [comment]
Ok I got it. Thanks a lot for helping me! :grinning:
