### ISSUE TITLE
how can I make custom widget occupying some width/height

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#240]
I have viewed examples/customwidget.go. If I commented out two lines. It will see picture below.

So it's g.InvisibleButton who make this custom widget moved the CursorPos.

There is g.GetCursorPos() to get canvas cursor position. But we have no g.SetCursorPos() to set cursor position.

My question is: if I create a chart, how can I make my widget occupying some width/height?

```go
	// Place a invisible button to be a placeholder for events
	// buttonWidth := float32(radius) * 2
	// g.InvisibleButton(c.id).Size(buttonWidth, buttonWidth).OnClick(c.clicked).Build()
```

![782BBCDE-5BD5-4F47-A95F-AE529BC0F343](https://user-images.githubusercontent.com/163152/127303568-3bbb9690-7f56-45c3-8486-0fb28f6405c9.png)

Thanks.

**Comment by daiwhea** [comment]
And I see if I commented out those two lines. The code below won't catch hover.

So my next question is: How can I use keyboard/mouse event in custom widget?

eg. If I draw a list of stock exchange bars. When mouse hover or click on one bar, I wish to know it's which bar.

```go
	// If button is hovered
	drawActive := g.IsItemHovered()
```

**Comment by daiwhea** [comment]
And I see if I commented out those two lines. The code below won't catch hover.

So my next question is: How can I use keyboard/mouse event in custom widget?

eg. If I draw a list of stock exchange bars. When mouse hover or click on one bar, I wish to know it's which bar.

```go
	// If button is hovered
	drawActive := g.IsItemHovered()
```

**Comment by AllenDang** [comment]
@daiwhea Update giu to newest version you will see g.SetCursorPos :P

**Comment by daiwhea** [comment]
> @daiwhea Update giu to newest version you will see g.SetCursorPos
> Use InvisibleButton to receive events and occupy widget height/width.

Thanks @AllenDang . You mean, no matter what I'm drawing, I should use InvisibleButton to receive events?

**Comment by AllenDang** [comment]
@daiwhea Use master branch, just get the newest code. And yes, once you will dealing with events, use InvisibleButton to catch them.

**Comment by daiwhea** [comment]
@AllenDang Thanks. I can get mouse position via g.GetMousePos().

But I can not see g.SetCursorPos()

my go.mod is 
```
	github.com/AllenDang/giu v0.5.4
	github.com/AllenDang/imgui-go v1.12.1-0.20210509113325-c0e4c78e7a88
```

**Comment by AllenDang** [comment]
@daiwhea Run `go get github.com/AllenDang/giu@master`

**Comment by daiwhea** [comment]
> @daiwhea Run `go get github.com/AllenDang/giu@master`

Thanks @AllenDang . I'm a beginner, but I do think immediate mode is great. I can make custom widget quickly. And I still has some beginner questions. Would you please have a comment?

1. If I want a window without padding for my chart, how to set it?
2. In react, we use react-router to navigate to other pages. Is there any best practice in ImGui? I use a big switch to do the work. I'm not sure is there any other wonderful methods?
3. When I use @master branch. Where is the loadFont in g.NewMasterWindow("GoStock", 600, 400, 0, loadFont)? I can't find it now. And I can't start examples/multiplefonts.go now
4. Where is g.GetAvaiableRegion() ? 

Thanks.

**Comment by daiwhea** [comment]
Great, Chinese can displayed without any settings. But I want to know, if I want to use another font, for example, a bigger font size or another color, how can I do that in the newly @master branch? Seems many examples are broken now.

![78F2EF01-9CDE-45E7-A67C-BFD5B69A756D](https://user-images.githubusercontent.com/163152/127414043-48898197-6a44-460a-b771-52ff30a0fb39.png)

**Comment by daiwhea** [comment]
```
g.GetAvaiableRegion()
g.GetAvailableRegion()
```

Ok, it should be GetAvailableRegion().

**Comment by AllenDang** [comment]
@daiwhea All examples should work. Can you tell me which example doesn't work?

**Comment by daiwhea** [comment]
> @daiwhea All examples should work. Can you tell me which example doesn't work?

Sorry, I made a mistake. I just run the copied the examples for 0.5.4 . It's ok for 0.5.5. I'll read your codes first. Thanks @AllenDang

**Comment by daiwhea** [comment]
@AllenDang Two beginner questions:

1. If I want a window without padding for my chart, how to set it?
2. Can we use system menu in macosx?

![51CBAE58-7352-42C2-956E-1F7B9847110E](https://user-images.githubusercontent.com/163152/127728220-e9965815-6fd8-4913-98b6-7bb26e3f62aa.png)

Thanks. I just dive into ImGui for days. Don't know well the best practices for it. Thanks again for your time.

**Comment by AllenDang** [comment]
@daiwhea 
1. Set the width of plot to -1, means to use available width -1 px. 
2. No, cannot use system menu.

**Comment by daiwhea** [comment]
> @daiwhea
> 
> 1. Set the width of plot to -1, means to use available width -1 px.
> 2. No, cannot use system menu.

Thanks @AllenDang 

I'm sorry, how can I set the width of plot to -1? I didn't use g.Plot("Plot Bars").Size(500, 250). I write my KChart widget. 

So the question may become, for custom widget, how can we set it's size?

```go
package kchart

import (
	"fmt"

	"daiwhea.com/gostock/stockserver/stock"
	g "github.com/AllenDang/giu"
)

const defaultBarWidth = 3
const defaultBarMargin = 1

type KChartWidget struct {
	scode         stock.Scode
	compareScode  stock.Scode
	klines        []stock.KLINE
	visibleKlines []stock.KLINE
	compareKlines []stock.KLINE
	leftIndex     int
	currentIndex  int
	rightIndex    int
	width         float32
	height        float32
	// 我们将bar宽度和间隔写到KChartWidget，这样以后可以在一个页面显示多个KChart的时候使用不同的bar宽度
	barWidth  int
	barMargin int
	barChart  *BarChartWidget
	split     float32
	dirty     bool
}

func KChart(
	scode, compareScode stock.Scode,
	klines, compareKlines []stock.KLINE,
) *KChartWidget {
	rightIndex := len(klines)
	return &KChartWidget{
		scode:         scode,
		compareScode:  compareScode,
		klines:        klines,
		compareKlines: compareKlines,
		//width:         width,
		//height:        height,
		//leftIndex:    leftIndex,
		currentIndex: -1,
		rightIndex:   rightIndex,
		barWidth:     defaultBarWidth,
		barMargin:    defaultBarMargin,
		split:        0.75, // 价格部分所占比例
	}
}

func (kc *KChartWidget) onUp() {
	if kc.barMargin == 0 {
		kc.barMargin = 1
	} else {
		kc.barWidth += 2
	}
	kc.dirty = true
}
func (kc *KChartWidget) onDown() {
	if kc.barMargin > 0 {
		if kc.barWidth > 1 {
			kc.barWidth -= 2
		} else {
			kc.barMargin = 0
		}
		kc.dirty = true
	}
}
func (kc *KChartWidget) onLeft() {

}
func (c *KChartWidget) onRight() {

}
func (c *KChartWidget) onEscape() {

}
func (c *KChartWidget) onBlank() {

}

func (c *KChartWidget) Build() {
	if c == nil || len(c.klines) == 0 {
		fmt.Println("no klines for kchart")
		return
	}
	if g.IsKeyPressed(g.KeyDown) {
		fmt.Println("KeyDown")
		c.onDown()
	} else if g.IsKeyPressed(g.KeyUp) {
		fmt.Println("KeyUp")
		c.onUp()
	} else if g.IsKeyPressed(g.KeyLeft) {
		fmt.Println("KeyLeft")
		c.onLeft()
	} else if g.IsKeyPressed(g.KeyRight) {
		fmt.Println("KeyRight")
		c.onRight()
	} else if g.IsKeyPressed(g.KeyEscape) {
		fmt.Println("KeyEscape")
		c.onEscape()
	}
	g.Layout{
		g.Custom(func() {
			width, height := g.GetAvailableRegion()
			// resize
			if c.dirty || width != c.width || height != c.height {
				leftIndex := len(c.klines) - int(width)/(c.barMargin+c.barWidth)
				visibleKlines := c.klines[leftIndex:c.rightIndex]
				// 缓存数据
				c.width = width
				c.height = height
				c.leftIndex = leftIndex
				c.visibleKlines = visibleKlines
				// 生成 barchart
				if c.barChart == nil {
					c.barChart = BarChart()
				}
				visibleBars := ComputeBars(visibleKlines, c.barWidth, c.barMargin, width, height, c.split)
				c.barChart.SetKlines(visibleBars, c.barWidth, c.barMargin).Size(width, height)
			}
			// keyboard events
			g.Layout{
				c.barChart,
			}.Build()
		}),
	}.Build()
	c.dirty = false
}

```

**Comment by AllenDang** [comment]
@daiwhea Basically, the widget creation in giu is just drawing something at some position. For custom widget, here is the logic going on internally:
1. Invoke canvas api to draw anything at anywhere.
2. Use InvisibleButton to tell giu what's the size and position of your custom widget, and handle user events.

To your question, how to set size of a custom widget, answer is set the size of a InvisibleButton.

**Comment by daiwhea** [comment]
@AllenDang Thanks. I add a InvisibleButton. But it seems there are some default padding in window. Please have a look at the screenshot below.

If I want my window has no padding, how to set this?

![54013E99-71D0-4A8E-8F2D-E499A1E98920](https://user-images.githubusercontent.com/163152/127735805-3ea278e7-d99f-48eb-9d21-2e351c4830a2.png)

**Comment by AllenDang** [comment]
@daiwhea I just created a quick demo, and I didn't find any padding.
```go
package main

import (
	"image"
	"image/color"

	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow().Layout(
		g.Label("Hello world from giu"),
		g.Custom(func() {
			width, height := g.GetAvailableRegion()

			pos := g.GetCursorPos()

			canvas := g.GetCanvas()
			canvas.AddRectFilled(pos, pos.Add(image.Pt(int(width), int(height))), color.RGBA{12, 12, 200, 255}, 0, g.DrawFlagsClosed)
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by daiwhea** [comment]
@AllenDang Thanks, let me try it and feed back asap. Thanks. ^_^

**Comment by AllenDang** [comment]
@daiwhea If you are saying that you don't want any border padding, just increase the size any you like
```go
package main

import (
	"image"
	"image/color"

	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow().Layout(
		g.Label("Hello world from giu"),
		g.Custom(func() {
			width, height := g.GetAvailableRegion()

			pos := g.GetCursorPos()

			// Increase size as you need
			ptMin := pos.Sub(image.Pt(8, 0))
			ptMax := pos.Add(image.Pt(int(width)+8, int(height)))

			canvas := g.GetCanvas()
			canvas.AddRectFilled(ptMin, ptMax, color.RGBA{12, 12, 200, 255}, 0, g.DrawFlagsClosed)
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by daiwhea** [comment]
No, it doesn't work. I change your code +- 80px, And it still not work as wanted.

![DB7802BF-2889-4AE6-A0E4-0718B93311BF](https://user-images.githubusercontent.com/163152/127737569-dd359f7d-b26f-4949-b724-17a1b7a28fc6.png)

**Comment by daiwhea** [comment]
> If you found some part of your plot is in-complete, check the coordiate calculation part, I think the position is mis-calced.

yes, I should use pos.Add() to get position properly.

**Comment by AllenDang** [comment]
@daiwhea So you don't want any padding at all. This is impossible, and frankly I think it's not reasonable. Why you need to avoid window padding at all? If just for visual consistance, change the background color of MasterWindow to the same with your plot.

**Comment by daiwhea** [comment]
I see. In some windows app, there is no any padding. So I want to know whether giu can do it or not. Currently this is acceptable. Thank you @AllenDang . You are really helpful!
