### ISSUE TITLE
RegisterKeyboardShortcuts for two InputText?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#241]
I have two InputText, and I wish it will copy/paste string in it. I see there is a giu.RegisterKeyboardShortcuts for a window. But I only want that KeyC/KeyV for InputText, if I use RegisterKeyboardShortcuts for window, how can I know which InputText was focused?

Thanks.

**Comment by AllenDang** [comment]
@daiwhea Can you explain more detail about the usage scenario?

**Comment by daiwhea** [comment]
sure, let me make a simple demo for it.

**Comment by daiwhea** [comment]
Should we change the title to "**[Request] Support other keyboard layout well**" ?

**Comment by AllenDang** [comment]
@daiwhea Easy way to do this is handle Ctrl+I, read content from clipboard and set to inputext.

**Comment by daiwhea** [comment]
> @daiwhea Easy way to do this is handle Ctrl+I, read content from clipboard and set to inputext.

Sorry, I want to say, giu hasn't process ShortCuts well. When I use Programmer Dvorak keyboard layout it's Ctrl+I, when I use default keyboard layout it's Ctrl+C. Then if some other layouts was used, it's some other Ctrl+? . 

So, my question is:

Can giu's detect current keyboard layout and use ShortCuts for that keyboard layout?

**Comment by AllenDang** [comment]
@daiwhea This is more complex than you think. Not just keyboard layout, but also different OS, and even need to process different keyboard remapping. I think this will have low priority right now.

**Comment by daiwhea** [comment]
> @daiwhea This is more complex than you think. Not just keyboard layout, but also different OS, and even need to process different keyboard remapping. I think this will have low priority right now.

Yes, it can work. So let's close it, if you have time for it, we can reopen it.

Thanks @AllenDang giu is really charming! Thanks for your time.
