### ISSUE TITLE
generate ui script get error

### ISSUE THREAD

**Issue by runsys** [AllenDang/giu#242]
code:
package main

import (
	g "github.com/AllenDang/giu"
	lua "github.com/yuin/gopher-lua"
	luar "layeh.com/gopher-luar"
)

// Define a simple plugin struct
type LuaPlugin struct {
	Name   string
	Layout g.Layout
}

// Genreate a string pointer for lua
func GStrPtr() *string {
	var str string
	return &str
}

// Receive string value from pointer
func ToStr(str *string) string {
	return *str
}

var luaPlugin LuaPlugin

func onRunScript() {
	luaPlugin.Name = ""
	luaPlugin.Layout = g.Layout{}

	luaState := lua.NewState()
	defer luaState.Close()

	// Pass luaPlugin into lua VM.
	luaState.SetGlobal("luaPlugin", luar.New(luaState, &luaPlugin))

	// Register some method (giu widget creator)
	luaState.SetGlobal("GStrPtr", luar.New(luaState, GStrPtr))
	luaState.SetGlobal("ToStr", luar.New(luaState, ToStr))

	luaState.SetGlobal("Label", luar.New(luaState, g.Label))
	luaState.SetGlobal("Button", luar.New(luaState, g.Button))
	luaState.SetGlobal("InputText", luar.New(luaState, g.InputText))

	// Simple lua code
	luaCode := `
    luaPlugin.Name = "test"

    name = GStrPtr()
    
    function onGreeting()
	  print(string.format("Greeting %s", ToStr(name)))
    end
    
    luaPlugin.Layout = {
      Label("Label from lua, tell me your name"),
      InputText("##name", 200, name),
      Button("Greeting", onGreeting),
    }
  `

	// Run lua script
	if err := luaState.DoString(luaCode); err != nil {
		panic(err)
	}
}

func loop() {
	g.SingleWindow().Layout(
		g.Button("Load from lua").OnClick(onRunScript),
	)
}

func main() {
	wnd := g.NewMasterWindow("Lua test", 400, 300, 0)
	wnd.Run(loop)
}

**Comment by AllenDang** [comment]
@runsys I don't understand your question here... What are you intend to do? What error message you got?
