### ISSUE TITLE
Handle Closing MasterWindow?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#245]
Hi, is there a way to disable the user from closing the master window? For example, I don't want a user to be able to close my program when it's encrypting a file, as it would cause a lot of issues with temporary files. I checked MasterWindow.go as well as Events.go, but I haven't found anything like it. Ideally, it would be used like:

```go
window := giu.NewMasterWindow("Picocrypt",480,502,giu.MasterWindowFlagsNotResizable)
window.SetOnCloseCallback(func(){
    if working{
        return false;
    }
    return true;
})
```
Thank you very much!

**Comment by AllenDang** [comment]
@HACKERALERT It's done. MasterWindow.SetCloseCallback is added.

**Comment by HACKERALERT** [comment]
Oh wow, @AllenDang you work very fast. Many thanks!
