### ISSUE TITLE
A strange issue for Chinese characters. How to show Chinese character correctly with canvas.AddText()?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#246]
I add one line code to rewrite canvas example. I want to display some Chinese characters with canvas.AddText(). 

1. If I canvas.AddText() without Chinese characters in Label, it will be displayed as ????
![A6DE92B2-F93E-4B45-B175-9D76A8CE7EC9](https://user-images.githubusercontent.com/163152/127764045-0179f0d5-ec88-44bc-b10e-87f9c95cdec1.png)

2. If I add the **same Chinese character** in one label before canvas.AddText(), both the Chinese will be displayed correctly.
![44721DED-D4C1-4F12-909C-3D7B6A68B912](https://user-images.githubusercontent.com/163152/127764130-80df009a-d81a-4a8e-909e-9d95b2aa2f67.png)

3. If I add different Chinese character in label and AddText(). Only the Chinese character in Label can be displayed correctly.
![32E5090A-4FF1-4C79-9985-3FF0335C5726](https://user-images.githubusercontent.com/163152/127764212-e8a7c9d5-7433-4ee6-836f-98a3d07322fb.png)

So, how can we display Chinese character with canvas.AddText()? I do read g.Label() codes. Here is a tStr(label). What is tStr? I don't see the define of it.

```go
func (i *InputTextMultilineWidget) Label(label string) *InputTextMultilineWidget {
	i.label = tStr(label)
	return i
}
```

Thanks.

**Comment by AllenDang** [comment]
@daiwhea It is fixed. tStr is a internal method to register characters which will be displayed and build font atlas for rendering.

**Comment by daiwhea** [comment]
@AllenDang Great! It's ok now. Thanks a lot.
