### ISSUE TITLE
How to update g.Label() properly? When to use g.Update()?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#248]
I have a g.Label() to display some msg. And the msg will be changed after some seconds. So I want my changed msg displayed properly. But if I don't move mouse and don't press any keys. I can see the timer did fired, but the msg not visible. If I moved mouse or pressed keyboard, the new msg displayed.

I know there is a g.Update() in timer can make this msg displayed immediately. But I'm not sure, when and why should we call g.Update()? 

Thanks.

https://user-images.githubusercontent.com/163152/127956132-14925d2b-d2df-4c73-9d25-3c2426a9ff37.mp4

**Comment by AllenDang** [comment]
@daiwhea Giu will stop drawing process if there is no user action has been made to save CPU usage. So if you want to update anything, call giu.Update to inform a refresh.

**Comment by daiwhea** [comment]
> @daiwhea Giu will stop drawing process if there is no user action has been made to save CPU usage. So if you want to update anything, call giu.Update to inform a refresh.

I see. Thanks for your comment.
