### ISSUE TITLE
Redraw with 'external' event

### ISSUE THREAD

**Issue by r00tc0d3** [AllenDang/giu#250]
Hi,

I am implementing a application using giu. Great stuff by the way. 

In my application the data in a widget may change any moment, without a keyboard or mouse event. Your current implementation does not redraw the window, as you have mentioned in the README. However I would like to redraw the windows when data changes. This is live data and in future there will also be plot with live data or streaming data.
What do you think is the best approach here? Add a manual update event would be nice but where to implement it? In imgui-go platform or in giu? Some kind of flagging should me enough.

Im am willing to implement it, but it would be nice if it is inline with your thoughts.

**Comment by daiwhea** [comment]
Have you tried g.Update() when your data changed?

**Comment by r00tc0d3** [comment]
Thanks @daiwhea I mist that one.
