### ISSUE TITLE
Table is invisible when there is no rows

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#252]
When a Table widget contains no rows, the whole table is invisible, including the Columns and Border.
![table](https://user-images.githubusercontent.com/4710875/128767966-bd2eb780-0043-4bb6-80cb-8a15c16d2d2d.png)

Possible to always show the table?

**Comment by r00tc0d3** [comment]
I don't know if this is how it should be but it works. Table with header without data.

``` golang
	giu.SingleWindow().Layout(
		giu.Table().Columns(
			giu.TableColumn("name"),
			giu.TableColumn("age"),
		).Rows(giu.TableRow()),
	)
```

**Comment by aj3423** [comment]
Thanks. That's it.
