### ISSUE TITLE
How to set window min size?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#255]
My use case is:

I wish window resizable, but I want it force a min size. How to achieve this?

Thanks.

**Comment by AllenDang** [comment]
@daiwhea I just added MasterWindow.SetSizeLimits, try it :P

**Comment by daiwhea** [comment]
> @daiwhea I just added MasterWindow.SetSizeLimits, try it :P

@AllenDang Thanks. It's what I want. Thanks for you speedy fix. ^_^
