### ISSUE TITLE
Possible to support more "Language Definition" for CodeEditor ?

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#256]
I need to show json strings, and xml in the future, I found CodeEditor is a good choice, but currently there are only 4 types of language definitions:  sql / c / cpp / lua.  

Is it possible to support them ? Or maybe allow user provide some custom syntax regex, so it can fit any kind of text ?

**Comment by AllenDang** [comment]
@aj3423 Yeah, I would like to do that also. But code editor is a little bit complex, may need some time.

**Comment by gucio321** [comment]
@aj3423 this might be a bit late, but #902 adds JSON support. There is no xml yet.

**Comment by gucio321** [comment]
well, I've checked out source code of ColorTextEdit and there is no possibility to add custom syntax highlighting so I think this should be added there first. Let me close this for now.
