### ISSUE TITLE
How to specify percentage in SplitLayout

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#258]
How to build a SplitLayout that contains two Label, and keeps both percentage when resizing the main window?

My code:

```golang
package main

import (
	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Row(
			giu.SplitLayout(giu.DirectionHorizontal, false, 0,
				giu.Label("aaaa"),
				giu.Label("bbbb"),
			),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("app", 400, 200, 0)
	wnd.Run(loop)
}

```

On startup, the left label occupies the whole window, after adjusting the split bar to the middle then it works fine.

I tried set the `sashPos` like `giu.SplitLayout(giu.DirectionHorizontal, false, 200, ...`, it seems fine on startup, but left width is fixed even when resizing the main window.

**Comment by AllenDang** [comment]
@aj3423 There is no automatic way to do that, but you could calcuate sashPos when resizing window.

**Comment by aj3423** [comment]
Got it. Thanks.
