### ISSUE TITLE
CodeEditer input Chinese hint at the bottom of the screen

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#262]
Please have a look at the screenshot. When I want to input Chinese at position A, the input hints was displayed at position B, which is the bottom of the screen. It's hard to input. Can we display input hints B near A?

Thanks.

![E23B1068-7712-48A9-9E5F-6BF0E6BFD88B](https://user-images.githubusercontent.com/163152/129431731-477d80aa-3538-4d07-aa2d-a7b80b79a0cd.png)

**Comment by AllenDang** [comment]
@daiwhea Create a app bundle by using `gmdeploy` could solve this. Launch GUI from terminal in macOS will have this issue.

**Comment by daiwhea** [comment]
> @daiwhea Create a app bundle by using `gmdeploy` could solve this. Launch GUI from terminal in macOS will have this issue.

Ok, thanks @AllenDang .

**Comment by daiwhea** [comment]
> @daiwhea Create a app bundle by using `gmdeploy` could solve this. Launch GUI from terminal in macOS will have this issue.

@AllenDang Sorry, would you please show me a demo cmd for this? I tried cmd below but the runnable app still act the same as go run xxx.go. Thanks.

`go build -ldflags "-s -w" .`

**Comment by AllenDang** [comment]
@daiwhea First of all, gmdeploy is located at `giu/cmd/gmdeploy/`, go to that dir, run `go build .`, copy executable to `$GOPATH\bin`.
Then in your project root, run `gmdeploy -upx -icon ./res/app_icon.icns`, of cause `-icon` and `-upx` is optional.
You could found the app bundle at `./build/darwin`.

**Comment by daiwhea** [comment]
Thanks @AllenDang . with gmdeploy still not works as expected. Maybe because my os is too old for giu. My os is 10.13.6. If it works well in some modern macos, please let it be. Thanks.

```
172-11-2-103:ImStock daiwhea$ gmdeploy
ImStock.app is generated at /Users/daiwhea/myworks/daiwhea/ImStock/build/darwin/
```

![B442409F-745C-44B0-9FED-C1F18D9353B6](https://user-images.githubusercontent.com/163152/129440868-53d118a5-3960-4d3a-9fae-f6079c9098b2.png)

**Comment by AllenDang** [comment]
@daiwhea I just checked this with a chinese IME and found out this issue remains even in app bundle. Looks like it's an issue related to upstream imgui. So this may not be fixed soon on my side. Because IME support cross various OS is a lot of works.

**Comment by daiwhea** [comment]
> @daiwhea I just checked this with a chinese IME and found out this issue remains even in app bundle. Looks like it's an issue related to upstream imgui. So this may not be fixed soon on my side. Because IME support cross various OS is a lot of works.

@AllenDang I see. It's workable and acceptable ^_^... Thanks.

**Comment by kesuskim** [comment]
Maybe we could look into this link:

https://github.com/ocornut/imgui/issues/1807#issuecomment-394383995

**Comment by kesuskim** [comment]
Not sure what to do with macOS as the link seems to deal only with Windows.
