### ISSUE TITLE
Question about the padding between two widgets

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#263]
I want to create some Toggle buttons, and I wish I can make them side by side more closely. Can we change the padding between two widgets? Or is it fixed if we use g.InvisibleButton?

![383FE390-7F23-4551-909C-6E432D24C631](https://user-images.githubusercontent.com/163152/129440257-4e5ac690-d1c0-4776-81cb-5d50ae94ac9a.png)

**Comment by AllenDang** [comment]
@daiwhea Use `giu.Style().Set...` to set style for any layout. To understand what style id works, try below steps.
1. Navigate to `examples/imguidemo/imguidemo.go`.
2. Run it.
3. Open `Style Editor`.
![截屏2021-08-14 下午4 53 31](https://user-images.githubusercontent.com/18550/129440714-16fe5a9a-b421-41a5-ac1e-e64fad21dd4b.png)
4. Open tree node `Widgets/Basic`.
![截屏2021-08-14 下午4 54 35](https://user-images.githubusercontent.com/18550/129440757-fa64accb-19f5-4392-8ae9-11e39740c1d6.png)
5. Tweak styles as you like and you will see what's going on.
6. Find related StyleID, set it using `giu.Style().SetStyle(...)`.

**Comment by daiwhea** [comment]
@AllenDang Thanks, I'll try it. You're really helpful!
