### ISSUE TITLE
How to close the master window from code?

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#264]
I want to close the main window by Ctrl+W,  can't find any API about it. I tried:
```golang
	wnd := giu.NewMasterWindow("", 1200, 500, 0).
		RegisterKeyboardShortcuts(
			giu.WindowShortcut{
				Key:      giu.KeyW,
				Modifier: giu.ModControl,
				Callback: func() { giu.Context.GetPlatform().Dispose() },
			},
		)
```

It does quit the window...  by a "panic".  What's the correct way?

**Comment by AllenDang** [comment]
In the callback, invoke `os.Exit(0)`

**Comment by aj3423** [comment]
Possible to only close the Master window and let application continue running?  Like close the "x" button. Maybe post a close event ?

**Comment by AllenDang** [comment]
@aj3423 I think what you need is "minimize" master window.

**Comment by aj3423** [comment]
The code logic looks like 
```golang
func main() {
  load_ini()
  load_resource()
  load_....

  wnd.Run(loop)

  save_ini()
  free_resource()
  save_....
}
```

There are several places can trigger quitting the application like  Menu, Hotkey, 'x' button, some trick can be used to solve the problem like use a cleaner function to do all the clean up and call it everywhere, but maybe let the window break from message loop is better,  if possible...

**Comment by gucio321** [comment]
@aj3423 use `defer`
like:
`golang
func main() {
   loadSoething()
   defe saveSomething
   wnd.Run(loop)
}
```

**Comment by aj3423** [comment]
@gucio321 The `defer` not executed when app exited with panic, the panic is caused by ` giu.Context.GetPlatform().Dispose()`, there seems no other way to close the main window.

**Comment by gucio321** [comment]
> @gucio321 The defer not executed when app exited with panic
I suppose, it does. please try this code
```golang
package main

import (
        "fmt"

        "github.com/AllenDang/giu"
)

func main() {
        wnd := giu.NewMasterWindow("mw", 640, 480, 0)
        defer fmt.Println("execute defer")
        wnd.Run(func() {
                giu.Context.GetPlatform().Dispose()
        })
}
```

Here is a workaround for you:
```golang
package main

import (
	"fmt"
	"os"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Button("close the window").OnClick(quit),
	)
}

func main() {
	wnd := giu.NewMasterWindow("mw", 640, 480, 0).
		RegisterKeyboardShortcuts(giu.WindowShortcut{
			Key:      giu.KeyQ,
			Modifier: giu.ModControl,
			Callback: quit,
		})
	defer quit()

	wnd.Run(loop)
}

func quit() {
	fmt.Println("free resources; save state")
	os.Exit(0)
}
```

but it'd be easier to add `MasterWindow.Close(...)` to do so :grinning:

**Comment by aj3423** [comment]
@gucio321 Thanks. it does work, my miss understood, and a `MasterWindow.Close(...)` would be nice  grinning

**Comment by AllenDang** [comment]
@aj3423 Invoke `os.Exit(0)` will trigger the defer fn for main function. This could do what you need. Even if we have a MasterWindow.Close(), it also just a simple wrapper for os.Exit().

**Comment by gucio321** [comment]
> Even if we have a MasterWindow.Close(), it also just a simple wrapper for os.Exit().

@AllenDang what if I want to continue executing code after closing main window?

**Comment by aj3423** [comment]
> > Even if we have a MasterWindow.Close(), it also just a simple wrapper for os.Exit().
> 
> @AllenDang what if I want to continue executing code after closing main window?

Agree, maybe a  `PostMessage(WM_CLOSE)` will do the job(win32), is it exist in the imgui c layer ?

**Comment by AllenDang** [comment]
@aj3423 Why bother to find another solution? Why os.Exit not good enough?
