### ISSUE TITLE
Vertical SplitLayout doesn't work together with other widget

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#265]
I want a layout like this:
1. left side: a Table
2. right side:  a SplitLayout (vertical)

The code:
```golang
package main

import (
	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Row(
			giu.Table().Size(200, 0).Columns(giu.TableColumn(`col`)).Rows(giu.TableRow()),
			//giu.Label("left"),

			giu.SplitLayout(giu.DirectionVertical, true, 50,
				giu.Label("label a"),
				giu.Label("label b"),
			),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("app", 400, 200, 0)
	wnd.Run(loop)
}

```
it looks like 
![giu](https://user-images.githubusercontent.com/4710875/129448308-daa8ed9c-2aa5-4f8f-9433-41882723429a.png)

Not only Table, same problem with other widgets like Label,  but it works fine with Horizontal SplitLayout.

**Comment by AllenDang** [comment]
@aj3423 It is fixed. Thanks to report this.
