### ISSUE TITLE
How to modify master window title

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#268]
I have a use case. There are many pages for different content in my app. In some pages, I want to display some useful message on the window title bar. I know I can display these messages in the content area. But it will be more acceptable displaying it on title bar.

```go
var wnd *g.MasterWindow
func setWindowTitle(t string) {
	//wnd.SetTitle(t) // ???
}
func main() {
	wnd = g.NewMasterWindow("GoStock", 800, 600, 0)
	wnd.SetSizeLimits(800, 600, g.DontCare, g.DontCare)
	wnd.Run(loop)
}
```

![8A536A0D-39C3-4E24-A43F-327A1A5391FE](https://user-images.githubusercontent.com/163152/129498373-2522d906-3d2e-49e6-827e-a6514b66c463.png)

Thanks.

**Comment by AllenDang** [comment]
@daiwhea I added MasterWindow.SetTitle :P

**Comment by daiwhea** [comment]
> @daiwhea I added MasterWindow.SetTitle :P

Thanks. You're so helpful.
