### ISSUE TITLE
Issue on macOS with an external monitor

### ISSUE THREAD

**Issue by remeh** [AllenDang/giu#27]
While running the `widgets` example, I can't click or interact with anything in the window if I'm using an external monitor with a Mac having the lid closed. Hopefully, it works if the lid is opened (on both the Mac screen and on the external monitor).

Something that may be interesting is that I can interact with the inputs (editfield and button) in the `loadimage`,  `simple` and `helloworld` examples, but not in others (i.e. `splitter`,  `customwidget`, `widgets`).

**Comment by AllenDang** [comment]
@remeh This is really weired. I'll check it out. May I ask what lid stands for?

**Comment by remeh** [comment]
I've used "lid" to speak about the Mac screen. I'm using my Mac with its screen closed, connected to an external monitor.

**Comment by AllenDang** [comment]
@remeh I see, my macbook is not by my side now. I will return to office at about 5 days. Sorry cannot test and solve it now. :P

**Comment by remeh** [comment]
Sure, no rush :)

**Comment by remeh** [comment]
Fixed, more infos in #29
Thank you @AllenDang !
