### ISSUE TITLE
Can we add OnDClick() to g.InvisibleButton?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#274]
When customize a widget, we use g.InvisibleButton() to get mouse click events. But sometimes our customized widget need to listen DoubleClick events. So maybe it's good to add g.InvisibleButton.OnDClick(func)?

Thanks.

By the way. How can we set WindowPadding to a Window. I know we can use g.Style().SetStyle(xxx, x, y).To(g.Layout{}). But seems it cannot be used to Window.

Thanks again.

**Comment by AllenDang** [comment]
@daiwhea You could detect any event manually by put the detecting code below any widget. No need to wait the pr.
```go
giu.AnyWidget(...),
giu.Custom(func() {
  if giu.IsItemActive() && giu.IsMouseDoubleClicked(...) {
    // add event handling logic here.
  }
})
```

**Comment by daiwhea** [comment]
Thanks @gucio321

Thanks, @AllenDang I should remind giu.IsMouseDoubleClicked(...)
