### ISSUE TITLE
docs: add FAQ?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#276]
Hi there,
what about adding a special section of readme for `frequently asked questions` to avoid issues like: `How to detect double-click event` or `how to open popup modal`

**Comment by AllenDang** [comment]
Yeah, let's make it happen.

**Comment by AllenDang** [comment]
There are two things hover in my mind all the time:
1. How to write tests, increase the coverage and add giu to awesome go list.
2. Find a way to create a good code editor with syntax highlight (integrate with treesitter maybe...).

**Comment by daiwhea** [comment]
Please say something about style...

**Comment by phorcys420** [comment]
> Please say something about style...

And examples of basic components, how to do specific things such as centering up, in the middle, down, on the sides, EVERYWHERE ! centering is weird for most people and I think having a cheat sheet with ready examples could help.

Do you plan using GitHub's wiki feature? I know I personally prefer seing stuff there (having a "Wiki" tab just lets you know there's docs before looking at anything else)

**Comment by gucio321** [comment]
Feel free to post here anything, you want to see in [FAQ page on our wiki](https://github.com/AllenDang/giu/wiki/FAQ)

**Comment by gucio321** [comment]
some FAQ in  #625

**Comment by gucio321** [comment]
-[ ] https://github.com/AllenDang/giu/issues/820

**Comment by gucio321** [comment]
- https://github.com/AllenDang/giu/issues/565

**Comment by Ralphbow** [comment]
> Please say something about style...
> 

Hello 👋

**Comment by gucio321** [comment]
> > Please say something about style...
> > 
> 
> Hello 👋

https://github.com/AllenDang/giu/wiki#style-related here is all we already have, what questions would you like to have answers for?
