### ISSUE TITLE
examples: language testing example?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#278]
hi there,
It would be cool to add some code, which allows to check what languages does our OS support, and how does it change after adding some default font.
it could be useful to complete a set of default fonts.

**Comment by AllenDang** [comment]
This is super useful, super, super... But I'm not sure we could cover that much OS...

**Comment by HACKERALERT** [comment]
@AllenDang Really easy, I happen to have done the heavy-lifting and you can detect system language like this:

```go
package main

import (
    "fmt"
    "github.com/HACKERALERT/jibber_jabber"
)

func main(){
    d,_ := jibber_jabber.DetectIETF()
    fmt.Println(d) // en-CA for me (Canadian English)
}
```

It's cross-platform too :)

**Comment by gucio321** [comment]
> But I'm not sure we could cover that much OS...

I meant to add a code (like a set of labels using as much as possible `foreign` characters) so we users can see which characters (fonts) are missing in his OS and make it easier to  `Need your help to add more language support by creating a PR or telling me the OS default font name for your language.`

**Comment by phorcys420** [comment]
> hi there, It would be cool to add some code, which allows to check what languages does our OS support, and how does it change after adding some default font. it could be useful to complete a set of default fonts.

On Windows, might that checking work using OS language packs ? Doesn't installing an additional system locale also add the required fonts ?

Even though that would remove the possibility that the user has a font that supports chinese (or anything else) but doesn't have the language pack installed.

You could also loop over the fonts in the system font store to check if they have glyphs for specific character ranges.
https://docs.microsoft.com/en-us/typography/opentype/spec/cmap

**Comment by phorcys420** [comment]
https://github.com/ocornut/imgui/issues/2403
