### ISSUE TITLE
How to check key pressed from a-z or 0-1?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#279]
Hi there. I'm trying to check whether user pressed keyboard from 'A'-'Z' or '0'-'1'. Is there any simply way? Or I must write codes like these? Thanks.

```go
if g.IsKeyPressed(g.Key0) || ... || g.IsKeyPressed(g.Key9) || g.IsKeyPressed(g.KeyA) || ... || g.IsKeyPressed(g.KeyZ) {
    // do sth. here...
}
```

**Comment by daiwhea** [comment]
And I need to know which key was pressed, so I can feed it in a InputText field. But I won't display InputText before key pressed. When user pressed key, I display a InputText, then set the char pressed into this InputText. How can I do it?

**Comment by AllenDang** [comment]
@daiwhea Key question here is where do you want to detect the key pressed event? Window? Any widget? A InputText?

**Comment by daiwhea** [comment]
@AllenDang best in window, or place in the loop() is also ok.

**Comment by AllenDang** [comment]
By checking the definition of Key enum, we could know it is a one-on-one mapping for glfw.Key whose base type is int.
So check a range of key pressing could be done easily by:
```go
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	keyMap = map[int]string{
		48: "0",
	}
	content string
)

func detectKeyAndShowInput(i int) {
	if v, ok := keyMap[i]; ok {
		content = v
	}
}

func loop() {
	g.SingleWindow().Layout(
		g.Custom(func() {
			// Detect 0-9
			for i := 48; i <= 57; i++ {
				if g.IsKeyPressed(g.Key(i)) {
					detectKeyAndShowInput(i)
				}
			}

			// Detect a-z
			for i := 65; i <= 90; i++ {
				if g.IsKeyPressed(g.Key(i)) {
					detectKeyAndShowInput(i)
				}
			}

			if len(content) > 0 {
				g.InputText(&content).Build()
				g.SetKeyboardFocusHere()
			}
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}

```

**Comment by daiwhea** [comment]
@AllenDang Thanks, I'll try it and feed back asap. ^_^

**Comment by daiwhea** [comment]
@AllenDang Thanks, it works.
