### ISSUE TITLE
Inputtext GenAutoID

### ISSUE THREAD

**Issue by r00tc0d3** [AllenDang/giu#281]
Hi,

Is there a reason why the InputText widget has an exception on an empty label to use the GenAutoID?
I would prefer if this is always done like the buttonWidgets and most other widgets.  

```golang
func (i *InputTextWidget) Build() {
    if len(i.label) == 0 {
        i.label = GenAutoID(i.label)
    }
```

I have input texts with the same label so I would like to have them unique with GenAutoID, like the other widgets.

**Comment by AllenDang** [comment]
@r00tc0d3 Yes, there is a reason, either don't control id at all , otherwise have a full control. It could be very helpful in some special case.

**Comment by r00tc0d3** [comment]
I still don't see the special case and why is InputTextWidget different than other.
But when having 2 inputtext's with the same name and e.g. text is select in one input it is also selected in the other etc. They mirror each other. But if that the special case then I will work around it. No problem.

**Comment by AllenDang** [comment]
There are several special widgets (TabBar, TabItem, InputText, etc...), current AutoID implementation is not perfect. Like if the UI is dynamically generated, there could be unknown number of buttons before input text widget, the id of intput text will be changed during different frame, and the callback state will be messed up, result in event detection will become unexpectable.

**Comment by r00tc0d3** [comment]
Than I will take control :)
