### ISSUE TITLE
Automatic Dummy Size?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#283]
Is there a way for a Dummy to automatically take up all space, but take into account widgets after it? Current, I've hardcoded some Dummy values which works for the first screenshot, but once I change the text, the hardcoded values don't work:

![Screenshot (159)](https://user-images.githubusercontent.com/48808396/130155157-46782fda-3c8c-412d-a73a-cf6702cad563.png)
![Screenshot (160)](https://user-images.githubusercontent.com/48808396/130155159-70ce2e0c-1edb-498d-acf9-e902733ede1e.png)

Here's the code for the widgets in my screenshots:
```go// MD5
giu.Row(
	giu.Checkbox("MD5:",&md5_selected),
	giu.Dummy(-58,0),
	giu.Button("Copy##md5").Size(50,0).OnClick(func(){
		clipboard.WriteAll(cs_md5)
	}),
),
giu.Style().SetColor(giu.StyleColorBorder,md5_color).To(
	giu.InputText(&cs_md5).Size(-0.0000001).Flags(giu.InputTextFlagsReadOnly),
),
```

Maybe something like `giu.Dummy(giu.Smart,0)` or something like that. I've already tried giu.CalcTextSize, but it doesn't seem to be consistent and the layout changes with different string lengths.

Also, congrats on 1k stars! giu has come a long way and my projects wouldn't be the same without it.

**Comment by AllenDang** [comment]
@HACKERALERT giu.CalcTextSize could tell you the length of given text, then use it to calc dummy width.

**Comment by daiwhea** [comment]
Wish this will help a little.

```go
package main

import (
	"fmt"

	g "github.com/AllenDang/giu"
	"github.com/AllenDang/imgui-go"
)

var md5_selected = false
var btnTxt = "Copy Long"

func loop() {
	g.SingleWindow().Layout(
		g.Row(
			g.Checkbox("MD5:", &md5_selected),
			g.Dummy(50, 0),
			g.Button("Copy##md5").Size(50, 0).OnClick(func() {
				fmt.Println("guga")
			}),
		),
		g.Custom(
			func() {
				g.Checkbox("MD5:", &md5_selected).Build()
				imgui.SameLine()
				w, _ := g.GetAvailableRegion()
				bw, _ := g.CalcTextSize(btnTxt)
				padding, _ := g.GetWindowPadding()
				bw += 2 * padding
				size := w - bw - padding
				g.Dummy(size, 0).Build()
				imgui.SameLine()

				g.Button(btnTxt).Size(bw, 0).OnClick(func() {
					fmt.Println("guga")
				}).Build()

			},
		),
	)
}
func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 100, 0)

	wnd.Run(loop)
}

```

![97101E1C-B300-4C68-9DA4-533967B29A5D](https://user-images.githubusercontent.com/163152/130174177-b6e66eed-f0e7-4c7c-a23d-7e83e68eccd1.png)

![853CFACB-23E1-4F2D-92EB-4D30D327F9DD](https://user-images.githubusercontent.com/163152/130174480-bb2d02fd-8f82-4799-a8f9-73f4c546f044.png)

**Comment by HACKERALERT** [comment]
@daiwhea You are a genius! Thank you so much for this clever solution!
