### ISSUE TITLE
How to focus a InputText ?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#285]
My use case is:

When user pressed some char key[a-z,0-1], I'll popup a panel and display a InputText, and make the InputText focused, then user can keep typing to filter some strings.

But I don't know how to make the InputText focused.

Any suggestion? Thanks

**Comment by daiwhea** [comment]
Sorry I searched one solution, but it raises another question:

```go
g.InputText(&inputTxt).Size(-1),
g.Custom(func() { g.SetKeyboardFocusHere() }),
```

This did work. But the first time focused the InputText, the content string was focused and selected. So if user keep typing, the first char will be lost. 

How can I focus a InputText and don't select the string content?

**Comment by AllenDang** [comment]
@daiwhea Currently no ways to select a input text without select all it's content. I've tried few options, none of them works.

**Comment by daiwhea** [comment]
@AllenDang Ok, it doesn't matter. Thanks. ^_^
