### ISSUE TITLE
table: width of column

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#286]
hi,
I'm trying to run this code:
```golang
package main

import (
        "strconv"

        "github.com/AllenDang/giu"
)

func loop() {
        const numCols = 64

        rowItems := make([]giu.Widget, numCols)
        for i := range rowItems {
                rowItems[i] = giu.Label(strconv.Itoa(i))
        }
        row := giu.TableRow(rowItems...)

        giu.Window("wnd").Layout(
                giu.Table().FastMode(false).Rows(row),
        )
}

func main() {
        wnd := giu.NewMasterWindow("table", 640, 480, 0)
        wnd.Run(loop)
}
```
with the following result:
![image](https://user-images.githubusercontent.com/73652197/130288182-b1e4ab31-43f7-45f7-8c1c-36fa24fea2b9.png)

the problem is, that i'm unable to scroll to further columns and unable to change column width.

**Comment by daiwhea** [comment]
Please try this. Flags(giu.TableFlagsScrollX)

giu.Table().Flags(giu.TableFlagsScrollX).Size(-1, 60).FastMode(false).Rows(row),

![B8F57FCD-25DA-4DCF-8855-A6A022BB1F5A](https://user-images.githubusercontent.com/163152/130308949-f24b4e16-ad2f-4a88-b78b-cfe492c70335.png)

**Comment by gucio321** [comment]
it works! thank you very much
