### ISSUE TITLE
How to use Colorful Glyphs/Emojis

### ISSUE THREAD

**Issue by yibana** [AllenDang/giu#293]
How  display colored emoticons like this

[https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#using-colorful-glyphsemojis](url)
![image](https://user-images.githubusercontent.com/26332832/130387974-2d3ce21e-df68-4f3b-8fe0-b75a64a572f9.png)

```
io.Fonts->AddFontFromFileTTF("../../../imgui_dev/data/fonts/NotoSans-Regular.ttf", 16.0f);
static ImWchar ranges[] = { 0x1, 0x1FFFF, 0 };
static ImFontConfig cfg;
cfg.OversampleH = cfg.OversampleV = 1;
cfg.MergeMode = true;
cfg.FontBuilderFlags |= ImGuiFreeTypeBuilderFlags_LoadColor;
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\seguiemj.ttf", 16.0f, &cfg, ranges);
```

**Comment by AllenDang** [comment]
@yibana I have tried, but doesn't work so far...

**Comment by phorcys420** [comment]
this might come handy -> https://github.com/inkyblackness/imgui-go/issues/6#issuecomment-427059409
will test l8r

**Comment by gucio321** [comment]
@yibana take a look at #561
