### ISSUE TITLE
style: set font size

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#294]
hi there,
I need to set font size by style setter

**Comment by AllenDang** [comment]
Yeah, I konw, I need it too. But this may take a while cause it's not easy. I also need to set font style.

**Comment by gucio321** [comment]
@AllenDang maybe adding GetDefaultFont method could be enough for now?
I just need to change default font's size, so e.g.:
```golang
Style.SetFont(AddFont(GetDefaultFont(), 28)).To(/*my leayout*/)
```

**Comment by AllenDang** [comment]
@gucio321 I imaging we need to set font size temporarily like `g.Style().SetFontSize(13).To(...)`. But yes to add default font could partially solve this, not perfect but could work.
