### ISSUE TITLE
Trouble setting background color after upgrade to v0.5.6

### ISSUE THREAD

**Issue by macbutch** [AllenDang/giu#298]
I was previously using v0.5.4 (and I can downgrade again) I've got a fully themed UI (based on the Nord colours) which is (imo) looks pretty great for the most part.

I have one small part of the UI in a Column inside a SplitLayout which is not themed. Digging into code for SplitLayout I notice that there is a colour that appears to be hardcoded:

```
func (s *SplitLayoutWidget) restoreItemSpacing(layout Widget) Layout {
	return Layout{
		Custom(func() {
			PushItemSpacing(s.originItemSpacingX, s.originItemSpacingY)
			PushFramePadding(s.originFramePaddingX, s.originFramePaddingY)
			// Restore Child bg color
			PushStyleColor(StyleColorChildBg, color.RGBA{R: 0x26, G: 0x2e, B: 0x38, A: 0xff})
		}),
		layout,
		Custom(func() {
			PopStyleColor()
			PopStyleV(2)
		}),
	}
}

// Build Child panel. If layout is a SplitLayout, set the frame padding to zero.
func (s *SplitLayoutWidget) buildChild(width, height float32, layout Widget) Widget {
	_, isSplitLayoutWidget := layout.(*SplitLayoutWidget)

	return Layout{
		Custom(func() {
			if isSplitLayoutWidget || !s.border {
				PushFramePadding(0, 0)
			}
		}),
		Style().SetColor(StyleColorChildBg, color.RGBA{R: 0x1c, G: 0x26, B: 0x2b, A: 0xff}).To(
			Child().Border(!isSplitLayoutWidget && s.border).Size(width, height).Layout(s.restoreItemSpacing(layout)),
		),
		Custom(func() {
			if isSplitLayoutWidget || !s.border {
				PopStyle()
			}
		}),
	}
}
```

Any suggestions on what I might be doing wrong would be really appreciated.

**Comment by AllenDang** [comment]
@macbutch Sorry to take so long to reply. There are two approaches I've used the most.
1. Occationaly set style for few widgets.
```go
g.Style().Set...To(
  g.Label(..)
)
```
2. Create a new widget with new style and use it everywhere.
```go
func TitleLabel(..) g.Widget {
  return g.Style().Set...To(
    g.Label(...)
  )
}
```

**Comment by macbutch** [comment]
Thanks @AllenDan . It took me a little bit longer to figure out what was going wrong. The original code worked fine so long as I don't call this on my StyleSetter before using it:

    SetStyle(g.StyleVarFramePadding, 10, 6)

I can work around that pretty easily but I don't think it should crash. It's certainly not obvious to me why it does. This is the relevant code from Style.go:

```
		for k, v := range ss.styles {
			imgui.PushStyleVarVec2(imgui.StyleVarID(k), v) // crash here
		}
```

Anyway, I'm going to close this because the original issue is resolved.
