### ISSUE TITLE
CPU load > 10%

### ISSUE THREAD

**Issue by r00tc0d3** [AllenDang/giu#299]
Hi,

I noticed an increase in CPU load using master branch, it is most of the time larger than 10%. When I checkout v0.5.6 it is less than 1%.
Using the widgets example with go v1.17 on macOS Big Sur

**Comment by HACKERALERT** [comment]
Seems to be the same case for me... Not sure what the issue is. Perhaps a bug is causing the UI to constantly be redrawn?

**Comment by AllenDang** [comment]
@r00tc0d3 @HACKERALERT It is fixed! The root cause is after upgraded to imgui 1.84, the flag value of power-saving mode is changed.

**Comment by HACKERALERT** [comment]
Awesome, thanks!

**Comment by r00tc0d3** [comment]
That did the trick. Thanks!
