### ISSUE TITLE
global keyboard listener how to check current focus is input or not?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#303]
My use case is like this:

I have a global keyboard listener which will listen to char or digital key press and popup a keyboard genius. It did work. But there are some InputTexts. When I type keys in these InputTexts, I don't want the global keyboard listener popup keyboard genius.

So I want the global listener can check current focus is InputText or not. If focused a InputText, it will keep silence.

Is there any api to check current focused object? 

And I don't see OnFocused/OnFocusLost api for InputText. So I don't know how to do this.

Thanks for your time. ^_^

**Comment by AllenDang** [comment]
@daiwhea Currently, we have this.
```go
g.InputText(..)
g.Custom(func() {
  if g.IsItemActive() {
    // Here means upper InputText got focus
  }
})
```

**Comment by daiwhea** [comment]
Thanks @AllenDang . So there is no api for InputText focusLost?

**Comment by AllenDang** [comment]
@daiwhea No, giu doesn't have focus lost event. Here is a draft solution:
1. Define a int to store focus index.
2. Define a method to set the focus index, and callback when index was changed.
3. Invoke set focus index at everywhere you need to detect focus lost.

**Comment by daiwhea** [comment]
Thanks @AllenDang . I used a string for InputText. It's working. Thanks.

**Comment by daiwhea** [comment]
@AllenDang .When I try to update master, there're some errors.

```
go get github.com/AllenDang/giu@master
# github.com/AllenDang/giu
../../../go/pkg/mod/github.com/!allen!dang/giu@v0.5.7-0.20210903120418-a990dfa5f699/Widgets.go:239:21: undefined: fmt.SPrintf
../../../go/pkg/mod/github.com/!allen!dang/giu@v0.5.7-0.20210903120418-a990dfa5f699/Widgets.go:1439:49: undefined: MenuWIdget
../../../go/pkg/mod/github.com/!allen!dang/giu@v0.5.7-0.20210903120418-a990dfa5f699/Widgets.go:1571:31: undefined: overlay
../../../go/pkg/mod/github.com/!allen!dang/giu@v0.5.7-0.20210903120418-a990dfa5f699/Widgets.go:1600:55: undefined: SelectableWIdget
../../../go/pkg/mod/github.com/!allen!dang/giu@v0.5.7-0.20210903120418-a990dfa5f699/Widgets.go:2414:17: undefined: fmt.SPrintf
```

I made a PR for this. Would you please have a check for it? Thanks
