### ISSUE TITLE
Disable PopupModal From Moving?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#304]
Is there a way to prevent a PopupModal from being able to be dragged around? When I hold my mouse on the top section of a PopupModal, I can drag it around, however, I would like to prevent this. Is it possible? Thank you!

**Comment by AllenDang** [comment]
```go
		g.Button("Open popup").OnClick(func() {
			g.OpenPopup("Test")
		}),
		g.PopupModal("Test").Flags(g.WindowFlagsNoMove).Layout(
			g.Label("Me not move"),
			g.Button("Close").OnClick(func() {
				g.CloseCurrentPopup()
			}),
		),

```

**Comment by AllenDang** [comment]
@HACKERALERT If you need to know whether something is feasible, check the Flags.

**Comment by HACKERALERT** [comment]
Thank you!
