### ISSUE TITLE
wiki: update event handling section

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#305]
hi!
as of https://github.com/AllenDang/giu/pull/297 the event handlling section of wiki is out of data:
![image](https://user-images.githubusercontent.com/73652197/131849348-b7a6d1cb-aed3-43eb-b007-409918109371.png)

**Comment by AllenDang** [comment]
Can wiki accpet PR?

**Comment by gucio321** [comment]
https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github
if you don't want to allow everyone on gh to edit your wikis, sadly there is no way to pull request it.

**Comment by AllenDang** [comment]
Sign, ok, let me update it.

**Comment by AllenDang** [comment]
@gucio321 It's done.

**Comment by gucio321** [comment]
@AllenDang iirc OnActivate is like `onFocus` (it might be the better name). The better example for button could be OnHover, or OnDoubleClick
```
// Create a button
giu.Button("Click Me")
// Place the event handling APIs right after the button to capture key/mouse events.
giu.Event().OnActivate(func() {
    // Do event handling here. 
}).OnDeactivate(func() {})
```

**Comment by AllenDang** [comment]
@gucio321 Done!

**Comment by gucio321** [comment]
ok, thanx
