### ISSUE TITLE
Multiple windows?

### ISSUE THREAD

**Issue by bfreis** [AllenDang/giu#31]
Hello,

Is there a way to open multiple windows?

Thanks

**Comment by AllenDang** [comment]
Currently no, but I'm considering to add this feature. May I ask what's your use case?

**Comment by pztrn** [comment]
I can say mine - dialog windows (about, settings and so on) in more familiar manner, as separate windows.

**Comment by AllenDang** [comment]
@pztrn Sure. I will add this in the plan.

**Comment by bfreis** [comment]
I'm ingesting a ton of real time data from some financial markets, running
a bunch of calculations, and want to display quite a lot of information in
some very custom ways. I'd like to be able to have separate windows for
different pieces of data, so that I can freely move them around and put
them next to other windows from other software. Hope this is clear! Thanks

**Comment by AllenDang** [comment]
@bfreis Got it. I will work it out at this weekend.

**Comment by AllenDang** [comment]
To implement multiple OS window is more complicate than I thought...
Need more time to figure it out. Sorry about that.

**Comment by bfreis** [comment]
No worries, I did some more research and also found it to be considerably
more complex than I initially thought!

FWIW, I found a solution that works for me (but may not work for others).
I'll summarize it here in case anyone may find it useful. Also, please note
that I haven't ever used Dear Imgui before, so I may be using wrong
terminology.

It seems like Dear Imgui (or its Golang bindings, dunno) can only have one
"context" per running process, or maybe it can only be executed from the
main goroutine, not sure. But all my attempts to have multiple instances of
MasterWindow failed.

So what I ended up doing was a simple check on my main() function that
decides what to do based on which os.Args are passed. Without anything, it
runs my "main window". When that main window needs to open another window,
I use the standard exec package to launch my binary again as a separate
process, and I pass an argument to tell it which window I need - the main()
function then invokes the code for a different window. The main window and
the child window communicate via stdin and stdout. Works like a charm!

As you can see, it's not something trivial, but it does what I need. While
I don't think it's something that would fit inside of giu, as there are
tons of architectural choices that can't easily be adapted, it may be
useful to others.

Thanks for the great work!

Cheers

**Comment by AllenDang** [comment]
@bfreis This is certainly a workaround to launch multiple processes instead of create multiple os windows.
BTW, I noticed that imgui already implemented this feature (I mean create multiple os windows) in it's viewport branch. And this is possible to do it from the document I found for GLFW.
I need to read more about OpenGL context.
Glad to hear that your problem is solved!
I will keep looking for a solution. :)

**Comment by saucesaft** [comment]
If this helps, the imgui implementation in rust has the option of multiple windows.

**Comment by AllenDang** [comment]
@saucesaft Thanks, I'll check it out.

**Comment by RostMyr** [comment]
@AllenDang Hey Allen! Thanks for looking into this. I see that you closed it a year ago. Was this implemented? grep viewport doesn’t seems to be returning anything.
