### ISSUE TITLE
Texture loading: app hangs on when loading texture in main thread

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#316]
It may be related with #111 ?...
when calling `NewTextureFromRgba` in main thread (e.g. in giu.Custom) the app stops rendering and gots stuck
here is a demo code:
```golang
package main

import (
	"fmt"
	"image"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Custom(func() {
			fmt.Println("ping")
			rgba := image.NewRGBA(image.Rect(0, 0, 10, 10))
			giu.NewTextureFromRgba(rgba)
			fmt.Println("pong")
		}),
	)
}

func main() {
	wnd := giu.NewMasterWindow("App crash on loading textures [Demo]", 640, 480, 0)
	wnd.Run(loop)
}
```

**Comment by AllenDang** [comment]
@gucio321 NewTextureFromRgba has to be invoked from another thread.

**Comment by gucio321** [comment]
@AllenDang what about doing it automatically?
```golang
func NewTextureFromRgba(rgba image.Image, cb func(*Texture)) {...}
```

**Comment by AllenDang** [comment]
@gucio321 Aha, it's a good idea! In that way user could never met the block anymore. Can you make a PR? I think it should under your name.

**Comment by gucio321** [comment]
sure, I'll write something

**Comment by NetForces** [comment]
@AllenDang @gucio321 I'm hitting this exact usecase right now... I';m not sure I understand the change that got merged and how to use it...

**Comment by gucio321** [comment]
@NetForces lets say, that you have a global variable `myTexture` and you want to fill it with texture of image, you've recently saved in `myImage` variable, so:
```golang
// somewhere in your loop
giu.Custom(func() {
      if myTexture != nil { return }
      giu.NewTextureFromRgba(myImage, func(t *giu.Texture) {
            myTexture = t
      }),
}),
```
_I'm sorry if the code doesn't compile, but I wrote it from-scratch_

it allows you to don't care when the texture will be loaded and the app will continue working and displaying `nil` texture until it is done.
BTW I'd suggest to use ImageWIthRGBA/ImageButtonWithRGBA instead
