### ISSUE TITLE
Programmatically resizing windows at runtime?

### ISSUE THREAD

**Issue by Kindred87** [AllenDang/giu#317]
My goal is to adjust the size of windows if and when the OS window's size is adjusted, to maintain scale.

As a basic measure, I expect the following code to adjust the size of fooWindow as the OS window size is adjusted.  However, it does not.

``` Go
var (
	masterWindow  *g.MasterWindow
)

func loop() {
	fooWindow := g.Window("Foo")

        x, y := masterWindow.GetSize()

	fooWindow.Size(0.5*float32(x), 0.3*float32(y))

	fooWindow.Pos(0, 50) 

        fooWindow.Layout(
		g.Button("Foo button"),
	)

}

func main() {
	masterWindow = g.NewMasterWindow("Foo", 400, 200, g.MasterWindowFlagsMaximized)
	masterWindow.Run(loop)

}
```

I initially thought that I might require a separate callback or func.  Though I noticed that I'm able to change fooWindow's flags at runtime within loop() in separate testing.

**Comment by AllenDang** [comment]
@Kindred87 You need to set the flags of window to NoMove | NoResize to make it's pos and size fully controlled by code, otherwise it will maintained by it's own context.
```go
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	wnd *g.MasterWindow
)

func loop() {
	x, y := wnd.GetSize()
	g.Window("Foo").Flags(g.WindowFlagsNoMove|g.WindowFlagsNoResize).Size(0.5*float32(x), 0.3*float32(y)).Pos(0, 50).Layout(
		g.Button("Foo button"),
	)
}

func main() {
	wnd = g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}

```

**Comment by Kindred87** [comment]
That makes a lot of sense, and it works as expected now.

It may be worthwhile to specify this in the comments for the flags, though I will leave that to your discretion.

Thank you!
