### ISSUE TITLE
ImPlot: plot to y-Axis 2 / 3

### ISSUE THREAD

**Issue by francmarx** [AllenDang/giu#330]
how to plot to y-axis 2 and 3 ?
can't find info/help to select y-axis 2/3 for plotting, maybe not implemented yet?
(context menu already show y-aixs 2/3)

**Comment by AllenDang** [comment]
@francmarx Maybe implot itself has that and I missed to port them into giu. Can you help to show me the usage guide from C++ side? Here is the repo for implot C++ version (https://github.com/epezent/implot)

**Comment by AllenDang** [comment]
@francmarx I've added PlotLine.SetPlotYAxis, pls have a try.

**Comment by francmarx** [comment]
@AllenDang  it works fine :) thank you

**Comment by francmarx** [comment]
@AllenDang multi y-axis for PlotLine**XY**Widgets would be very nice :)

**Comment by AllenDang** [comment]
@francmarx What API you are refering? And a demo code from CPP should help me understand which api needs to port.

**Comment by francmarx** [comment]
changes you did for PlotLine (you added PlotLine.SetPlotYAxis) are needed for PlotLineXY

**Comment by francmarx** [comment]
@AllenDang changes you did for PlotLine (you added PlotLine.SetPlotYAxis) are needed for PlotLineXY

**Comment by AllenDang** [comment]
@francmarx It's done.
