### ISSUE TITLE
Row() bug when using Custom() as the last widget

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#345]
For widgets in a Row(), if the last one is a Custom(), the next row will show at the same row.

```goalng
package main

import (
	"github.com/AllenDang/giu"
)

var filter string

func loop() {
	giu.SingleWindow().Layout(
		giu.Row(
			giu.InputText(&filter).Label(`row 1`).Size(200),
			giu.Custom(func() {
				giu.SetKeyboardFocusHere()
			}),
		),
		giu.Row(
			giu.Label("row 2"),
		),
	)
}

func main() {
	master := giu.NewMasterWindow("", 400, 200, 0)

	master.Run(loop)
}
```
![row](https://user-images.githubusercontent.com/4710875/134309343-df9d1fca-9135-4784-9628-d48acbeb2200.png)

**Comment by AllenDang** [comment]
@aj3423 This is a design trade off. Idealy, custom widget should be a widget, so row will treat it like a widget, in your case, you need to wrap InputText into custom as it is a custom InputText which has a initial keyboard focus.

**Comment by aj3423** [comment]
Thanks, it works.
