### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by stigok** [AllenDang/giu#35]
Thanks for an interesting project! I'm getting to know it right now for a vending machine project I'm working on.
I see that you jumped version numbers, from 0.3 to 0.31 and 0.32. Please note, that according to semantic versioning, a future version 0.4 will *not* be a later version than 0.31 as the version numbers are commonly separated by punctuations `.` as in `<Major>.<Minor>.<Patch>`.

A way out of this now could be to issue next patch as 0.33.1 or next minor as 0.34.0. See https://semver.org/ for better information about this subject :)

**Comment by AllenDang** [comment]
@stigok Thanks very much for reminding me this! I'll check it out.

**Comment by AllenDang** [comment]
@stigok I'd have to remove all existing branches and release a new v0.4.

**Comment by stigok** [comment]
Yeah, but that could make problems for those who are already using the repo. There's nothing wrong in doing next version as 0.34.0, and starting fresh from there.

**Comment by AllenDang** [comment]
@stigok My bad....
