### ISSUE TITLE
TabBar loses "current tab" focus when menu is opened

### ISSUE THREAD

**Issue by snhmibby** [AllenDang/giu#351]
Hello,

in the sample program below, when I select the 2nd tabitem and then open the menu, the 1st tab item is displayed. When the menu closes, the 2nd tabitem will display again.
This seems to be a bug in giu? The example code (example/widget) in the repository has the same behaviour.
The expected behaviour would be that item2 would show while the menu is open.

```
package main

import (
	G "github.com/AllenDang/giu"
)

func mkMenu() *G.MenuBarWidget {
	return G.MenuBar().Layout(
		G.Menu("Test").Layout(
			G.MenuItem("Foo"),
		),
	)
}

func draw() {
	G.SingleWindowWithMenuBar().Layout(
		mkMenu(),
		G.TabBar().TabItems(
			G.TabItem("Item 1").Layout(
				G.Label("Label for Item 1"),
			),
			G.TabItem("Item 2").Layout(
				G.Label("Label for Item 2"),
			),
		),
	)
}

func main() {
	w := G.NewMasterWindow("tab-test", 400, 400, 0)
	w.Run(draw)
}

```

**Comment by AllenDang** [comment]
@snhmibby I ran your demo code with newest code from master branch, and cannot reproduce your issue.
Can you make sure you are using the newest code?

**Comment by snhmibby** [comment]
I am not sure how to do that (sorry, I am pretty unfamiliar with go / the go toolchain).
What i did was "go mod tidy -compat=1.17" (otherwise i get error related to giu using older versions) and then "go get ." which gives me version 0.5.6, the latest release.

**Comment by gucio321** [comment]
@snhmibby to update some of your dependencies you need to run `go get -u ropo@version(branch/commit hash)`.
so to update giu: `go get -u github.com/AllenDang/giu@master`
or, (to avoid some gh api delay) `go get -u github.com/AllenDang/giu@2a792dae8138f4596d6e621f28c6cf3e511aab89`

**Comment by snhmibby** [comment]
You are right, when i copy my file into a clone of the repo, the issue isn't there.
Good to know that in a future release it is fixed already, so i can focus on other things now :)

**Comment by snhmibby** [comment]
> @snhmibby to update some of your dependencies you need to run `go get -u ropo@version(branch/commit hash)`.
> so to update giu: `go get -u github.com/AllenDang/giu@master`
> or, (to avoid some gh api delay) `go get -u github.com/AllenDang/giu@2a792dae8138f4596d6e621f28c6cf3e511aab89`

Cool thanks! I tried '@latest' but i guess i have to use the github branch name? (i thought 'latest' was some kind of go-get keyword)

**Comment by gucio321** [comment]
iirc `latest` is a tag name, so you're getting the latest release tag (v0.5.6)

**Comment by snhmibby** [comment]
Thanks a lot! The TabBar problem is solved now :)
