### ISSUE TITLE
Bug: PlotAxisFlags enums not consistent

### ISSUE THREAD

**Issue by francmarx** [AllenDang/giu#353]
in implot.h line "ImPlotAxisFlags_Foreground = 1 << 4" was inserted, enums not consistent anymore

Flags.go:

```
const (
	// default
	PlotAxisFlagsNone PlotAxisFlags = 0
	// the axis label will not be displayed (axis labels also hidden if the supplied string name is NULL)
	PlotAxisFlagsNoLabel PlotAxisFlags = 1 << 0
	// the axis grid lines will not be displayed
	PlotAxisFlagsNoGridLines PlotAxisFlags = 1 << 1
	// the axis tick marks will not be displayed
	PlotAxisFlagsNoTickMarks PlotAxisFlags = 1 << 2
	// the axis tick labels will not be displayed
	PlotAxisFlagsNoTickLabels PlotAxisFlags = 1 << 3
	// a logartithmic (base 10) axis scale will be used (mutually exclusive with PlotAxisFlagsTime)
	PlotAxisFlagsLogScale PlotAxisFlags = 1 << 4
	// axis will display date/time formatted labels (mutually exclusive with PlotAxisFlagsLogScale)
	PlotAxisFlagsTime PlotAxisFlags = 1 << 5
	// the axis will be inverted
	PlotAxisFlagsInvert PlotAxisFlags = 1 << 6
	// the axis minimum value will be locked when panning/zooming
	PlotAxisFlagsLockMin PlotAxisFlags = 1 << 7
	// the axis maximum value will be locked when panning/zooming
	PlotAxisFlagsLockMax       PlotAxisFlags = 1 << 8
	PlotAxisFlagsLock          PlotAxisFlags = PlotAxisFlagsLockMin | PlotAxisFlagsLockMax
	PlotAxisFlagsNoDecorations PlotAxisFlags = PlotAxisFlagsNoLabel | PlotAxisFlagsNoGridLines |
		PlotAxisFlagsNoTickMarks | PlotAxisFlagsNoTickLabels
)
```

implot.h:
```
enum ImPlotAxisFlags_ {
    ImPlotAxisFlags_None          = 0,       // default
    ImPlotAxisFlags_NoLabel       = 1 << 0,  // the axis label will not be displayed (axis labels also hidden if the supplied string name is NULL)
    ImPlotAxisFlags_NoGridLines   = 1 << 1,  // no grid lines will be displayed
    ImPlotAxisFlags_NoTickMarks   = 1 << 2,  // no tick marks will be displayed
    ImPlotAxisFlags_NoTickLabels  = 1 << 3,  // no text labels will be displayed
=>  ImPlotAxisFlags_Foreground    = 1 << 4,  // grid lines will be displayed in the foreground (i.e. on top of data) in stead of the background
    ImPlotAxisFlags_LogScale      = 1 << 5,  // a logartithmic (base 10) axis scale will be used (mutually exclusive with ImPlotAxisFlags_Time)
    ImPlotAxisFlags_Time          = 1 << 6,  // axis will display date/time formatted labels (mutually exclusive with ImPlotAxisFlags_LogScale)
    ImPlotAxisFlags_Invert        = 1 << 7,  // the axis will be inverted
    ImPlotAxisFlags_NoInitialFit  = 1 << 8,  // axis will not be initially fit to data extents on the first rendered frame (also the case if SetNextPlotLimits explicitly called)
    ImPlotAxisFlags_AutoFit       = 1 << 9,  // axis will be auto-fitting to data extents
    ImPlotAxisFlags_RangeFit      = 1 << 10, // axis will only fit points if the point is in the visible range of the **orthoganol** axis
    ImPlotAxisFlags_LockMin       = 1 << 11, // the axis minimum value will be locked when panning/zooming
    ImPlotAxisFlags_LockMax       = 1 << 12, // the axis maximum value will be locked when panning/zooming
    ImPlotAxisFlags_Lock          = ImPlotAxisFlags_LockMin | ImPlotAxisFlags_LockMax,
    ImPlotAxisFlags_NoDecorations = ImPlotAxisFlags_NoLabel | ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels
};
```

**Comment by gucio321** [comment]
@AllenDang I'd really suggest to reffer in these constants to values in imgui-go.
e.g.
```golang
type PlotAxisFlags imgui.PlotAxisFlags
const (
      PlotAxisFlagsNone PlotAxisFlags = imgui.PlotAxisFlags_None
      // ...
)

**Comment by AllenDang** [comment]
@gucio321 Agree. I'll do that.

**Comment by AllenDang** [comment]
@francmarx It's fixed. Pls try newest code from master branch.

**Comment by francmarx** [comment]
@AllenDang with newest code from master:

github.com/AllenDang/giu v0.5.7-0.20210929061837-010d8ec313bc
github.com/AllenDang/imgui-go v1.12.1-0.20210927080912-46269bd8d896

I tried "XAxeFlags(g.PlotAxisFlagsTime)" 
=> it makes a log scale instead of Time scale (like PlotAxisFlagsLogScale would do)

**Comment by francmarx** [comment]
@AllenDang 

github.com/epezent/implot/blob/master/implot.h differs from implot.go

----------------
github.com/epezent/implot/blob/master/implot.h

// Options for plot axes (see BeginPlot).
enum ImPlotAxisFlags_ {
    ImPlotAxisFlags_None          = 0,       // default
    ImPlotAxisFlags_NoLabel       = 1 << 0,  // the axis label will not be displayed (axis labels also hidden if the supplied string name is NULL)
    ImPlotAxisFlags_NoGridLines   = 1 << 1,  // no grid lines will be displayed
    ImPlotAxisFlags_NoTickMarks   = 1 << 2,  // no tick marks will be displayed
    ImPlotAxisFlags_NoTickLabels  = 1 << 3,  // no text labels will be displayed
    ImPlotAxisFlags_Foreground    = 1 << 4,  // grid lines will be displayed in the foreground (i.e. on top of data) in stead of the background
    ImPlotAxisFlags_LogScale      = 1 << 5,  // a logartithmic (base 10) axis scale will be used (mutually exclusive with ImPlotAxisFlags_Time)
    ImPlotAxisFlags_Time          = 1 << 6,  // axis will display date/time formatted labels (mutually exclusive with ImPlotAxisFlags_LogScale)
    ImPlotAxisFlags_Invert        = 1 << 7,  // the axis will be inverted
    ImPlotAxisFlags_NoInitialFit  = 1 << 8,  // axis will not be initially fit to data extents on the first rendered frame (also the case if SetNextPlotLimits explicitly called)
    ImPlotAxisFlags_AutoFit       = 1 << 9,  // axis will be auto-fitting to data extents
    ImPlotAxisFlags_RangeFit      = 1 << 10, // axis will only fit points if the point is in the visible range of the **orthoganol** axis
    ImPlotAxisFlags_LockMin       = 1 << 11, // the axis minimum value will be locked when panning/zooming
    ImPlotAxisFlags_LockMax       = 1 << 12, // the axis maximum value will be locked when panning/zooming
    ImPlotAxisFlags_Lock          = ImPlotAxisFlags_LockMin | ImPlotAxisFlags_LockMax,
    ImPlotAxisFlags_NoDecorations = ImPlotAxisFlags_NoLabel | ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels
};

------------------------
implot.go

const (
	ImPlotAxisFlags_None          ImPlotAxisFlags = 0      // default
	ImPlotAxisFlags_NoLabel       ImPlotAxisFlags = 1 << 0 // the axis label will not be displayed (axis labels also hidden if the supplied string name is NULL)
	ImPlotAxisFlags_NoGridLines   ImPlotAxisFlags = 1 << 1 // the axis grid lines will not be displayed
	ImPlotAxisFlags_NoTickMarks   ImPlotAxisFlags = 1 << 2 // the axis tick marks will not be displayed
	ImPlotAxisFlags_NoTickLabels  ImPlotAxisFlags = 1 << 3 // the axis tick labels will not be displayed
	ImPlotAxisFlags_LogScale      ImPlotAxisFlags = 1 << 4 // a logartithmic (base 10) axis scale will be used (mutually exclusive with ImPlotAxisFlags_Time)
	ImPlotAxisFlags_Time          ImPlotAxisFlags = 1 << 5 // axis will display date/time formatted labels (mutually exclusive with ImPlotAxisFlags_LogScale)
	ImPlotAxisFlags_Invert        ImPlotAxisFlags = 1 << 6 // the axis will be inverted
	ImPlotAxisFlags_LockMin       ImPlotAxisFlags = 1 << 7 // the axis minimum value will be locked when panning/zooming
	ImPlotAxisFlags_LockMax       ImPlotAxisFlags = 1 << 8 // the axis maximum value will be locked when panning/zooming
	ImPlotAxisFlags_Lock          ImPlotAxisFlags = ImPlotAxisFlags_LockMin | ImPlotAxisFlags_LockMax
	ImPlotAxisFlags_NoDecorations ImPlotAxisFlags = ImPlotAxisFlags_NoLabel | ImPlotAxisFlags_NoGridLines | ImPlotAxisFlags_NoTickMarks | ImPlotAxisFlags_NoTickLabels
)

**Comment by AllenDang** [comment]
@francmarx Thanks for pointing that out. I've synced the PlotAxisFlags. Pls try again.

**Comment by francmarx** [comment]
@AllenDang now it works fine, perfect :)
