### ISSUE TITLE
ListClipper malfunctions an big lists

### ISSUE THREAD

**Issue by snhmibby** [AllenDang/giu#354]
If I try to use a ListClipper on a decent sized list, listClipper behaves weird when scrolling down a substantial amount. 
I.e. on the following program, scrolling down will eventually give the message:
```
listclippertest: imgui.cpp:2407: bool ImGuiListClipper::Step(): Assertion `ItemsHeight > 0.0f && "Unable to calculate item height! First item hasn't moved the cursor vertically!"' failed.
SIGABRT: abort
```

```
package main

import (
	"fmt"

	G "github.com/AllenDang/giu"
	I "github.com/AllenDang/imgui-go"
)

func draw() {
	G.SingleWindow().Layout(
		G.Child().Layout(G.Custom(func() {
			var clip I.ListClipper
			clip.Begin(100000000)
			for clip.Step() {
				for i := clip.DisplayStart; i < clip.DisplayEnd; i++ {
					fmt.Printf("i = %d\n", i)
					G.Label(fmt.Sprintf("Line %d", i)).Build()
				}
			}
			clip.End()
		})),
	)
}

func main() {
	w := G.NewMasterWindow("clipper-test", 400, 400, 0)
	w.Run(draw)
}

```

**Comment by gucio321** [comment]
hmm, @snhmibby this works for me with list up to 10<sup>7</sup> items and I can't imagine why would you need something larger...
However if so, thats rather a bug inside of native [Dear ImGui](https://github.com/ocornut/imgui) so you may need to open an issue there.

**Comment by snhmibby** [comment]
I'm trying to display (index) a hex dump for big files, say up several GB, a TB @ 16/32 bytes per line, you get over that amount.
I wanted to use listclipper because it automatically makes a scrollbar, and i couldn't find how to easily make a scrollbar with giu

**Comment by gucio321** [comment]
hmm, well @snhmibby you need to ask for it Dear ImGui developers, because it isn't giu fault - the following C code fails too:
```c++
        {
                ImGui::Begin("window with clipped list");

                ImGuiListClipper clipper;
                clipper.Begin(pow(10, 8));
                while (clipper.Step()) {
                        for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++) {
                                std::string tmp = std::to_string(i);
                                char const *num_char = tmp.c_str();
                                ImGui::Text(num_char);
                        }
                }
                clipper.End();

                ImGui::End();
        }
```
(run it inside of some of imgui's demos)

**Comment by snhmibby** [comment]
Thanks I will do that!

**Comment by snhmibby** [comment]
Hey man!
I had dinner, looked around for DIY scrolling code and poked around imgui and made this, it fails in the same way. The issue is that pixels are represented by an int32 somewhere, and that ```lineheight_in_pixels * numlines``` becomes bigger than INT_MAX.

Which is unfortunate because i think it means i have to somehow make my own scrollbar if i want to support big files.

```
package main

import (
	"fmt"
	"image"

	G "github.com/AllenDang/giu"
	I "github.com/AllenDang/imgui-go"
)

const N = 110000000
//const N = 120000000

func draw() {

	H := I.TextLineHeightWithSpacing()
	fmt.Printf("H = %f, N*H = %f\n", H, N*H)
	G.SingleWindow().Layout(
		G.Child().Layout(G.Custom(func() {
			use_clipper := false
			if use_clipper {
				var clip I.ListClipper
				clip.BeginV(N, I.TextLineHeightWithSpacing())
				for clip.Step() {
					for i := clip.DisplayStart; i < clip.DisplayEnd; i++ {
						I.Text(fmt.Sprintf("Line %d", i))
						//G.Label(fmt.Sprintf("Line %d", i)).Build()
					}
				}
				clip.End()
			} else {
				//touch the 'end' line so that a correct scrollbar appears
				p := G.GetCursorPos()
				G.SetCursorPos(image.Pt(0, int(N*H)))
				I.Text(".")
				G.SetCursorPos(p)

				//get information to calculate visible lines
				scroll := I.ScrollY()
				_, h := G.GetAvailableRegion()

				//calculate visible lines
				startline := int(scroll / H)
				endline := int((scroll + h) / H)

				//print lines
				G.SetCursorPos(image.Pt(p.X, startline*int(H)))
				for i := startline; i <= endline; i++ {
					I.Text(fmt.Sprintf("Line %d", i))
				}

			}
		})),
	)
}

func main() {
	w := G.NewMasterWindow("tab-test", 400, 400, 0)
	w.Run(draw)
}
```

**Comment by AllenDang** [comment]
@snhmibby It's far more easier than you think to create a scroll bar in giu. 

Let's break the task into steps:
1. A scroll bar is a rectangle bg with a draggable handle rectangle.
2. Draw the rectangle bg.
3. Draw the draggable handle rectangle.
4. Detect mouse hover/down/up event, change handle rectangle's bg and position.
5. Report current position of handle rectangle on move.

That's it.
