### ISSUE TITLE
SplitLayout.go: SetStyleChildBG seems to be unnecessary

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#367]
Hi there,
what does exactly do this line?
```golang
                Style().SetColor(StyleColorChildBg, Vec4ToRGBA(imgui.CurrentStyle().GetColor(imgui.StyleColorChildBg))).To(
```
we can find it in SplitLayout.go: https://github.com/AllenDang/giu/blob/7a1a262cf0eb925dd66f6604d724506ba32023e0/SplitLayout.go#L78

**Comment by AllenDang** [comment]
It is used to reset the bg color of child to original value. I remember child bg color is set to other value out side somewhere.

**Comment by gucio321** [comment]
Ok, so let me close this
