### ISSUE TITLE
Question about color

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#372]
I use Lightpink := color.RGBA{255, 182, 193, 255} to define some colors. and use them to draw rectangles. But only red/green/blue color works as expected. Lightgreen/Lightgrey/Lightpink doesn't works. They looks like one color.

Is there something wrong in my code? 

my giu version:
```
	github.com/AllenDang/giu v0.5.7-0.20210930062057-7a1a262cf0eb
	github.com/AllenDang/imgui-go v1.12.1-0.20210929095526-68b309906bdc
```

Thanks for you time.

```go
package main

import (
	"image"
	"image/color"

	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow().Layout(
		g.Label("Canvas demo"),
		g.Custom(func() {
			canvas := g.GetCanvas()
			pos := g.GetCursorScreenPos()
			Lightgreen := color.RGBA{144, 238, 144, 255}
			Lightgrey := color.RGBA{211, 211, 211, 255}
			Lightpink := color.RGBA{255, 182, 193, 255}

			canvas.AddRectFilled(pos, pos.Add(image.Pt(100, 100)), Lightgreen, 0, 0)
			canvas.AddRectFilled(pos.Add(image.Pt(110, 0)), pos.Add(image.Pt(200, 100)), Lightgrey, 0, 0)
			canvas.AddRectFilled(pos.Add(image.Pt(220, 0)), pos.Add(image.Pt(320, 100)), Lightpink, 0, 0)

			red := color.RGBA{255, 0, 0, 255}
			blue := color.RGBA{0, 0, 255, 255}
			green := color.RGBA{0, 255, 0, 255}
			pos = pos.Add(image.Pt(0, 120))
			canvas.AddRectFilled(pos, pos.Add(image.Pt(100, 100)), red, 0, 0)
			canvas.AddRectFilled(pos.Add(image.Pt(110, 0)), pos.Add(image.Pt(200, 100)), blue, 0, 0)
			canvas.AddRectFilled(pos.Add(image.Pt(220, 0)), pos.Add(image.Pt(320, 100)), green, 0, 0)

		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Canvas", 600, 600, g.MasterWindowFlagsNotResizable)

	wnd.Run(loop)
}

```

![FC2A78B3-E385-4423-B65D-5167229A4CB9](https://user-images.githubusercontent.com/163152/135789757-fa38a5f0-399b-417f-af2f-72bf4800fe7d.png)

**Comment by daiwhea** [comment]
Lightgrey := color.RGBA{211, 211, 211, 255} did works in old version. I updated to the newest version, then I noticed some color doesn't work as expected now.

**Comment by gucio321** [comment]
oh, @daiwhea thanx for pointing this out. It seems that it is caused by my missunderstood of how color.Color interface works.
I just noticed: `Each value ranges within [0, 0xffff],` and in #362 I still divide each component by 255. will open a PR soon.

**Comment by daiwhea** [comment]
@gucio321 Thanks, wish it can be combined quickly. my chart is ugly to view. ^_^

**Comment by gucio321** [comment]
@daiwhea if you realllllly need it **now**, you can try something like this: `go mod edit --replace github.com/AllenDang/giu=github.com/gucio321/giu@00c323bfdb3d6fca1838f2d6b4d357bf5d48c1d0`
btw IDK if it will work like I suppose.

**Comment by daiwhea** [comment]
@gucio321 Thanks. it works. If I met anything, I can switch back to AllenDang version. ^_^
