### ISSUE TITLE
Make Chinese Font loading more fast

### ISSUE THREAD

**Issue by topxeq** [AllenDang/giu#39]
Now the loading duration of Chinese font is a little bit slow (using AddFontFromFileTTFV and builder.AddRanges(fonts.GlyphRangesChineseSimplifiedCommon()), if using GlyphRangesChineseFull, will be much more slower).

Could it be better to load Chinese font quickly(I need at least common Chinese characters, not only specific characters)? Thanks.

**Comment by AllenDang** [comment]
@topxeq This is a issue comes from the font atlas mechanism of imgui. I raise an issue about it. But it is not the high priority.
Currently, you could enable freetype. This is much faster.
To enable freetype, invoke imgui.EnableFreeType = true, and add use following cmd to build.
go build -tags imguifreetype .
You need msys2 to build it under Windows.
