### ISSUE TITLE
PopupModal closing unexpectedly

### ISSUE THREAD

**Issue by macbutch** [AllenDang/giu#390]
This is a follow up to my comment on #350 and affects the current master (not 0.5.6).

I have a modal popup over two list boxes. There is a button in the popup that is supposed to start some work --> this works but it also closes the Popup. This only seems to happen if the list boxes in the background (behind the Popup) are big/full, when there is only a few items behaviour is normal.

I'm debugging now but opening this in case it's an easy fix for someone else. I'll report back if/when I learn more.

**Comment by macbutch** [comment]
OK, so I've isolated the change that causes this to 0f72311a18527a015ed6a62c050a6001219dd1a1 which is part of the fix for #346. I don't have a clear id if the root cause is really my code or that change. 

I need to spend some time to understand what is happening here before I could think about submitting a fix. I'll dig in more but I'm out of time for now; will check in later.

Thanks again @AllenDang  for your hard work on this. It's a really nice library to work with.

**Comment by AllenDang** [comment]
@macbutch Thanks to report this. I'll check it also.

**Comment by macbutch** [comment]
Thanks @gucio321! This was enough for me to realise what I was doing wrong. I still don't understand exactly why it was a problem but I was calling `giu.PopupModal()` before `SingleWindow().Layout()` and saving the result to use later. Anyway, I've made my code more like yours and it works now.

Thanks @gucio321 and @AllenDang

**Comment by gucio321** [comment]
Yah, this mechanism isn't obvious, so thats why @AllenDang is going to refine popups logic https://github.com/AllenDang/giu/pull/301#issuecomment-908207317
