### ISSUE TITLE
[Feature Request] Support imgui_memory_editor

### ISSUE THREAD

**Issue by pokemium** [AllenDang/giu#393]
### Related problem

I'm developing a game emulator using giu!

I want to implement Memory Editor with [imgui_memory_editor](https://github.com/ocornut/imgui_club#imgui_memory_editor). 

However, the memory editor is not in the giu widget. I thought about wrapping it myself, but it looks difficult.

### Your request

Can giu support a memory editor?

### Alternative solution

Can you tell me how to wrap the imgui widgets so that I can use them in giu?

### Additional context

I'm not good at English, so I use DeepL. So I apologize if there is any strange English.

**Comment by AllenDang** [comment]
@pokemium I need to take a look at it, and feedback to you later. Roughly saying, it should not be hard, I might be able to integrate it.
