### ISSUE TITLE
InputText in TabItem not working.

### ISSUE THREAD

**Issue by bezrazli4n0** [AllenDang/giu#4]
Hi, i can provide simple code for demonstrate the problem:
```
var value string
func loop(w *giu.MasterWindow) {
	giu.SingleWindow(w, "test", giu.Layout{
		giu.TabBar("MainBar", []*giu.TabItemWidget{
			giu.TabItem("InputText", giu.Layout{
				giu.InputText("", &value, nil),
			}),
		}),
	})
}

**Comment by bezrazli4n0** [comment]
Ohh.., the problem is because InputText with empty 'label' property, i think this is a bug, if we change empty to space symbols all work correctly.
```var value string
func loop(w *giu.MasterWindow) {
	giu.SingleWindow(w, "test", giu.Layout{
		giu.TabBar("MainBar", []*giu.TabItemWidget{
			giu.TabItem("InputText", giu.Layout{
				giu.InputText(" ", &value, nil),
			}),
		}),
	})
}

**Comment by AllenDang** [comment]
It's not a bug, the reason is imgui will manage the inputtext's state by it's id...

**Comment by bezrazli4n0** [comment]
Ok, but how to hide this label next to widget?

**Comment by AllenDang** [comment]
@bezrazli4n0 Add "##" as prefix for the id. For example "##hiddenId".

**Comment by bezrazli4n0** [comment]
Oh thanks)
