### ISSUE TITLE
Support built-in styles

### ISSUE THREAD

**Issue by acisternino** [AllenDang/giu#40]
Hi,

Original Dear Imgui supports three built-in styles:

- Classic
- Dark
- Light

that are selectable using the three functions:

- `StyleColorsClassic()`
- `StyleColorsDark()`
- `StyleColorsLight()`

Unfortunately my not so young eyes are having increasing problems using dark themes with small fonts. It would be great if support for at least those three styles could be added to the library. Thanks.

**Comment by AllenDang** [comment]
@acisternino Fully understand. I'll add it.

**Comment by AllenDang** [comment]
@acisternino It's done. You could change style like this.

wnd := g.NewMasterWindow(...)
imgui.StyleColorsLight()
wnd.Main(loop)

**Comment by acisternino** [comment]
Works flawlessly!
Thanks a lot!
![giu-light](https://user-images.githubusercontent.com/475646/78914048-2ef36500-7a8a-11ea-8564-d75075200443.png)
