### ISSUE TITLE
[bug] Auto scroll when InputTextMultiline is disabled

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#406]
### What happend?

I use giu.Style().SetDisabled(true) to a giu.InputTextMultiline. In this case, since the user can't input anything, the input box should automatically scroll down when data is appended to the string variable. Currently, I have to manually scroll down to see logs, but it would be nice for it to auto scroll down. Any ideas? I checked Flags.go but I didn't seem to find any that applied to InputTextMultiline's. Thanks.

### Code example

<details><summary><code>main.go</code></summary>

```golang
var text string

giu.Style().SetDisabled(true).To(
    giu.InputTextMultiline(&text).Size(giu.Auto, 300),
)

go func(){
    for{
        text += "abcd\n"
    }
}()
```

</details>

### To Reproduce

Make a disabled InputTextMultiline, add a bunch of newlines to it dynamically from a goroutine.

### Version

v0.5.6 (latest)

### OS

Windows 10 Home 64-bit

**Comment by AllenDang** [comment]
I suggest to use a different approach to implement:

1. Use a child + label to display readonly log.
2. Scroll to last element once new entry is added.
3. Switch back to input multiline to edit.
