### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by Sacules** [AllenDang/giu#41]
Although there's plenty of info in the wiki, most of the types and functions don't show up any documentation when using godoc or pkg.go.dev. As someone unfamiliar with Dear Imgui it's not obvious at all what a `builder` is or what `NewGlyphRanges()` even does and why it's necessary to load fonts. So it'd be nice to have more information for all of them :)

**Comment by AllenDang** [comment]
@Sacules Sure thing. I'm working on it :)

**Comment by gucio321** [comment]
I'd suggest to enable `revive` linter. It'll point out any missings here. (revive is disabled atm, because else linter workflow would fail)

**Comment by AllenDang** [comment]
@gucio321 `revive` seems good, can you add it to CI?
