### ISSUE TITLE
More detailed crash logs

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#412]
### Related problem

when I use gmdeploy deployed my app, it works. But sometimes it will crash according to some user actions. In mac console app, I can only see some logs like below:

Nov 18 18:23:31 172-11-2-103 com.apple.xpc.launchd[1] (com.yourcompany.ImStock.142800.B51455B5-8491-4229-BACE-10E765B6C578[56465]): Service exited with abnormal code: 2

### Your request

I wish some more detailed logs can be collected.

**Comment by AllenDang** [comment]
@daiwhea First, don't use gmdeploy, it will strip all the debug info, use `go build .` instead, and there will be more logs.

**Comment by daiwhea** [comment]
@AllenDang Ok, I'll try it. Thanks. It's hard to reproduce this crash, so I need some more logs. Thanks again for your works. ^_^

**Comment by gucio321** [comment]
@daiwhea any updates here or we can close this?

**Comment by daiwhea** [comment]
> @daiwhea any updates here or we can close this?

Yes, please close it. Thanks for your works.
