### ISSUE TITLE
question: exposing `Widget` state of some types

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#417]
Hi!
I'm looking at the code and the following thing struck me:
There are many widgets e.g. `TabItem`, `TableRow` `TableColumn` that actually shouldn't be called "Widget" (shouldn't have public `Build` method) because they cannot be used alone.
What do you think about hidding `Build` methods (making them private - e.g. `build`) so that they still can be used by giu, but not by users?

**Comment by AllenDang** [comment]
@gucio321 Reason is, some widgets could only be used with certain container. Flexibility will lead to mistake and cause misunderstanding, like `why I cannot put button inside TabBar?`.

I think the best approach is `there is always one solution for one problem`.

Same issue happened again and again with `Popup` if you could recall. So many people met the issue `why popup doesn't appear?`.

**Comment by gucio321** [comment]
> @gucio321 Reason is, some widgets could only be used with certain container. Flexibility will lead to mistake and cause misunderstanding, like why I cannot put button inside TabBar?.

yah, thats what I mean. You cant for example do 
```golang
func loop() {
        giu.SingleWindow().Layout(
                giu.TabItem("tabitem"),
        )
}
```
because it'll panic. So u can go ahead and make it problem while compilation
```console
./test.go:12:14: cannot use giu.TabItem("tabitem") (type *giu.TabItemWidget) as type giu.Widget in argument to giu.SingleWindow().Layout
```

**Comment by AllenDang** [comment]
@gucio321 Sorry for my misunderstanding. I totally agree your point, :P

**Comment by gucio321** [comment]
@AllenDang do you think that these methods should be public anyway?
I mean that despite e.g. TabItemWidget isn't `giu.Widget` anymore, user could call `BuildTabItem` anyway (for custom cases)?

**Comment by AllenDang** [comment]
@gucio321 Yeah, it accually already happened for giu.Plot.
