### ISSUE TITLE
FontAtlas: store font atlas in Context

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#421]
IMO storing font atlas variables inside of some type in context may be more clear for users.

**Comment by AllenDang** [comment]
Agree.

Another thing I'm thinking is Auto-ID. It may not be a good idea, cause it will cause some `wired` issue if user doesn't familier with imgui, like `why the size or style setting doesn't work something?`.

**Comment by gucio321** [comment]
> Another thing I'm thinking is Auto-ID. It may not be a good idea, cause it will cause some wired issue if user doesn't familier with imgui, like why the size or style setting doesn't work something?.

hmm, in my opinion, AutoID is really useful feature (despite all the possible problems). I'd just suggest to add some section in readme (something like FAQ) when we can describe situations when imgui gets confused because of IDs + each widget should have `ID` method that allows to manually set its id.
