### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by phorcys420** [AllenDang/giu#424]
Was wondering if anyone ever did manage to compile a giu/imgui-go binary for linux with static-linking.
You can see the message I sent to one of my friends (of course they had no clue) (I was using imgui-go at the time but the "problem" is the same with giu):
```
trying to compile an imgui-go (https://github.com/inkyblackness/imgui-go/) project with static linking.
the normal command, go build -x -o dist/ src/main.go works fine.

imgui-go is go bindings for Dear ImGui, which of course needs to use CGO.
it depends on GLFW, Xrandr & some other GL stuff.

The following command is what I first tried to use:
go build -tags osusergo,netgo,static -ldflags="-linkmode external" -x -o dist/ src/main.go

it seems to work just fine on my machine, but when running it on another machine it just exits with "no such file or directory", so it seems that I am not properly doing the static linking, but how would I go on about doing that? 
```

I can say that both the machines run Linux distributions (compile machine is Fedora/Alpine and the other test machine is Artix).
They both have the same Go version (1.17.5) even though I know it has nothing to do with that dysfunction.

This is more of an "ask for help" than an "issue" to be honest, I just don't know where else to ask.

**Comment by gucio321** [comment]
@phorcys420 I'm running the following `go build -tags osusergo,netgo,static -ldflags="-linkmode external" -x -o dist.bin examples/widgets/widgets.go` in a giu dir on my fedora linux and it works fine

**Comment by phorcys420** [comment]
> @phorcys420 I'm running the following `go build -tags osusergo,netgo,static -ldflags="-linkmode external" -x -o dist.bin examples/widgets/widgets.go` in a giu dir on my fedora linux and it works fine

yes, but does it run properly on other machines ?

**Comment by phorcys420** [comment]
Built on alpine, ran on Artix:
```
phorcys@thinkbook Téléchargements]$ ./main 
bash: ./main: Aucun fichier ou dossier de ce type
[phorcys@thinkbook Téléchargements]$ ./nonexistingfile
bash: ./nonexistingfile: Aucun fichier ou dossier de ce type
```

"Aucun fichier ou dossier de ce type" translates to "No such file or directory" (`main` is the binary, `nonexistingfile` simply does not exist)

**Comment by gucio321** [comment]
thats strage... so your issue is that if you're running linux build on another linux machine it doesn't want to run?

(btw, you're sure that `main` really exists `stat main`?)

**Comment by phorcys420** [comment]
> thats strage... so your issue is that if you're running linux build on another linux machine it doesn't want to run?
> 
> (btw, you're sure that `main` really exists `stat main`?)
yes it does, I chmod +x'd it just before

**Comment by gucio321** [comment]
strange... sadly cannot test it on another linux platform...
@AllenDang maybe you have possibility to test it?

Including my local build for testing
https://drive.google.com/file/d/107OISX6LSf-EhP3FyVNZUGFD7yeVJ9tM/view?usp=sharing

**Comment by AllenDang** [comment]
@gucio321 I have zero linux experience...

**Comment by gucio321** [comment]
meh, so it may be a bit difficult to fix this issue... @phorcys420 does my binary from previous post work on any of your machines?

**Comment by HACKERALERT** [comment]
For Windows, `go build -ldflags="-s -w -H=windowsgui -extldflags=-static"` usually works for me. On macOS, I don't think you can statically link, and on Linux, it's somewhat difficult as well. You can, however, build a Snap for Linux that bundles dependencies with it, but that would require Snapcraft to be installed. That's what I've done to distribute my giu app for Linux. Just my 2 cents.

**Comment by phorcys420** [comment]
> meh, so it may be a bit difficult to fix this issue... @phorcys420 does my binary from previous post work on any of your machines?

![image](https://user-images.githubusercontent.com/57866459/147131702-0a95d4ad-f359-4d03-b561-40ba33a0c859.png)
hmm, you use the same build command as me ?



> you can, however, build a Snap for Linux that bundles dependencies with it, but that would require Snapcraft to be installed.

Snap is literal OS cancer and no one should ever have to use it.

**Comment by HACKERALERT** [comment]
Bro just giving a suggestion, there's no need to call something that works perfectly fine as "cancer".

**Comment by phorcys420** [comment]
I don't see myself forcing my users to use a "tool" that oversandboxes my software and shims down the user experience for the profit of developer experience. Snap has so many design flaws (e.g forced autoupdating, uses snapd to manage daemons, everything is isolated so are the logs, snapd just slows down my machines)

**Comment by HACKERALERT** [comment]
Alright, go as you wish. Just don't insult something that works fine for others, especially when it is just a suggestion trying to help you.

**Comment by phorcys420** [comment]
didn't mean it to look as an insult

**Comment by phorcys420** [comment]
@gucio321 I can see that your binaries are double the size of mine.
![image](https://user-images.githubusercontent.com/57866459/147139250-4db74d63-243a-4503-b974-731e6cdf7c1f.png)
So, there's likely something more in there ;)

**Comment by gucio321** [comment]
Hehe lol idk what happend iirc i used your build command to create this binarny. However i van rebuild IT obce agai tomorrow

**Comment by gucio321** [comment]
> @phorcys420 I'm running the following `go build -tags osusergo,netgo,static -ldflags="-linkmode external" -x -o dist.bin examples/widgets/widgets.go` in a giu dir on my fedora linux and it works fine

Maybe gry to build with this command?

**Comment by phorcys420** [comment]
> > @phorcys420 I'm running the following `go build -tags osusergo,netgo,static -ldflags="-linkmode external" -x -o dist.bin examples/widgets/widgets.go` in a giu dir on my fedora linux and it works fine
> 
> Maybe gry to build with this command?

it does double the size of my binary, but same end result...

**Comment by phorcys420** [comment]
![image](https://user-images.githubusercontent.com/57866459/147156292-900ac23e-f95a-4b1b-9b1d-c0ef3d8da038.png)

I do see some changes between our binaries, even though I use the same command... (`main` is mine and the .bin one is yours)

**Comment by phorcys420** [comment]
Compiled on Fedora:
```
dist/main: ELF 64-bit LSB executable
 x86-64
 version 1 (GNU/Linux)
 dynamically linked
 interpreter /lib64/ld-linux-x86-64.so.2
 BuildID[sha1]=5b46e629db7dce6208521d9888eca8b06461d934
 for GNU/Linux 3.2.0
 not stripped
```

Compiled on my Alpine build machine:
```
main: ELF 64-bit LSB executable
 x86-64
 version 1 (SYSV)
 dynamically linked
 interpreter /lib/ld-musl-x86_64.so.1
 Go BuildID=Ti5Y0zPfudi0NkqLPuC9/Ec7mlEoK_LJL5UNuBxc7/MiZnnAhU-WWTFt2kfD1g/1dIoRJyXHl8xrHm8BFih
 not stripped
```

Alpine uses MUSL ! and NOT glibc!

**Comment by phorcys420** [comment]
Switched over to a Debian CT for building, works like a charm !
WOOOOOOOOOOOOOOOOOOOOOOOOOOOO !

Remember to check that the libc is indeed the same...

![image](https://user-images.githubusercontent.com/57866459/147242629-5f90532c-31fb-4f65-b042-0d4ecc640449.png)
