### ISSUE TITLE
g.Update() calls loop() three times

### ISSUE THREAD

**Issue by francmarx** [AllenDang/giu#432]
### What happend?

g.Update() is triggered every 2 seconds, but each time loop() is called 3 times, why?

if you try very slow mouse mouse movement there will be only one loop call for each mouse event.

print output:

starting app: 0 1 2

after 2 sec: 0 1 2 3 4 5

after 4 sec: 0 1 2 3 4 5 6 7 8

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"fmt"
	"time"

	g "github.com/AllenDang/giu"
)

func main() {
	w := g.NewMasterWindow("testing", 200, 200, 0)
	go refresh()
	w.Run(loop)
}

func refresh() {
	ticker := time.NewTicker(2 * time.Second)

	for {
		g.Update()
		<-ticker.C
	}
}

var i int

func loop() {

	fmt.Printf("%d ", i)
	i = i + 1

	g.SingleWindow().Layout(
		g.Label("test"),
	)
}

```

</details>

### To Reproduce

1. Run my demo
2. watch print output

### Version

v0.5.6 (latest)

### OS

linux

**Comment by francmarx** [comment]
@AllenDang yes, invoking loop() scenarios are clear for me
but why loop() is called three times when I invoke it by giu.Update() ?

**Comment by AllenDang** [comment]
@francmarx I see. It is caused by the power-saving related functiuons. I've fixed it. Update to newest version and try again.
