### ISSUE TITLE
question: how invoke main loop defer function when pressing CTRL+C

### ISSUE THREAD

**Issue by francmarx** [AllenDang/giu#433]
When I close my app by clicking the gui exit/close button it works fine, defer func() is invoked :)
When I close by entering 'CTRL+C' in terminal, defer func() IS NOT invoked

Does somebody has an idea for this issue?

```
package main

import (
	"fmt"

	g "github.com/AllenDang/giu"
)

func main() {

	defer func() {
		fmt.Println("defer function")
	}()

	w := g.NewMasterWindow("testing", 200, 200, 0)
	w.Run(loop)
}

func loop() {
	g.SingleWindow().Layout(
		g.Label("test"),
	)
}
```

**Comment by gucio321** [comment]
@francmarx look at this one https://github.com/AllenDang/giu/issues/153
In last comment you should find what you're looking for (https://github.com/AllenDang/giu/issues/153#issuecomment-937969537)

**Comment by francmarx** [comment]
thank you, works fine :)
