### ISSUE TITLE
MasterWindow.SetSize() causes panic: mainthread: did not call Run

### ISSUE THREAD

**Issue by runrc** [AllenDang/giu#444]
### What happend?

Calling MasterWindow.SetSize() - fails with 'panic: mainthread: did not call Run'
Calling MasterWindow.SetPos() works as expected

### Code example

```golang
package main

import "github.com/AllenDang/giu"

func loop() {
	giu.Window("window").Layout(
		giu.Labelf("Hello!"),
	)
}

func main() {
	wnd := giu.NewMasterWindow("windows [DEMO]", 640, 480, 0)
	wnd.SetPos(100, 100)
	wnd.SetSize(1024, 640) // <== panic occurs here
	wnd.Run(loop)
}


### To Reproduce

1. Execute code example
2. See the crash


### Version

master

### OS

mac OSx

**Comment by AllenDang** [comment]
@runrc wnd.SetSize should be called after wnd.Run, normally you will call it when some event occurred.

**Comment by runrc** [comment]
@AllenDang Thank you for your response. I'll close this issue as I can size the window at start-up via the NewMasterWindow() method.
