### ISSUE TITLE
compile for windows user without any dev stuff?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#449]
Hi,
Just got a feedback from user who cannot run my app, I compiled for windows
my compile command was:
```sh
CGO_ENABLED="1" GOOS="windows"  CC="/usr/bin/x86_64-w64-mingw32-gcc" CXX="/usr/bin/x86_64-w64-mingw32-c++" go build -o gifviewer.exe .
```
the error is:
![image](https://user-images.githubusercontent.com/73652197/152566764-10a5b377-b957-4ee5-8263-3188e8557b3f.png)

is there any solution for that?

**Comment by gucio321** [comment]
oh, lol, it is in polish xd
the message says:
```txt
cannot continue executing code, because there is no libstdc++-6.dll object found. reinstalling application may solve this problemm.
```

**Comment by alchem1ster** [comment]
Try to add `-static-libgcc` and `-static-libstdc++`

**Comment by gucio321** [comment]
oke @alchem1ster thank you!, I'll check it.
on wine it doesn't work, but I need to ask someone with windows to check it.

**Comment by alchem1ster** [comment]
@gucio321 
The compilation instructions also mention [static linking with Windows](https://github.com/AllenDang/giu#build-windows-version-on-windows)

**Comment by gucio321** [comment]
hmm, okey, well, I'm doing this
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ HOST=x86_64-w64-mingw32 go build -ldflags "-s -w -H=windowsgui -extldflags=-static" -p 4 -v -o gifviewer.exe`
but getting error
```console
# github.com/AllenDang/giu/examples/gifdecode
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-g++ failed: exit status 1
/usr/lib/gcc/x86_64-w64-mingw32/10.3.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
```

**Comment by alchem1ster** [comment]
Seems you dont have libpthread libs. Try to install `mingw32-pthreads-w32` and/or `mingw64-winpthreads-static`

**Comment by gucio321** [comment]
@alchem1ster the library seems to be installed: `mingw32-winpthreads.noarch` or that's not the right one?

**Comment by alchem1ster** [comment]
Try to install `mingw64-winpthreads-static` via apt or dnf (idk what OS). For some reasons is weird behaviour. May you just use Windows VM for build?

**Comment by gucio321** [comment]
oh, @alchem1ster it works - `mingw64-winpthreads-static` package was missing :tada:
thank you once again ;-)
