### ISSUE TITLE
Clarify "based on ... golang binding imgui-go."

### ISSUE THREAD

**Issue by ryn1x** [AllenDang/giu#46]
Can you clarify how this project is related to imgui-go? Is it an abstraction or layer above imgui-go or does it extend that project with additional features?

**Comment by AllenDang** [comment]
@ryn1x This project is an abstraction layer above imgui-go with a lot of changes (more imgui APIs 
 are wrapped,  changes in Platform and Renderer and some API changes).

**Comment by ryn1x** [comment]
Thank you. This is a really great project. I started using it today!
