### ISSUE TITLE
[howTo] Respond to enter key in an input box

### ISSUE THREAD

**Issue by schabil** [AllenDang/giu#460]
### What happend?

Hey,

thanks a lot for your great work.

I am currently trying to respond to the "Enter" key in an input box. However, the combination of if g.IsKeyPressed(g.KeyEnter) && g.IsItemActive() does not work.

Enter makes the focus disappear from the item (which is ok) but at that moment the IF condition no longer applies. If I omit isItemActive all enter keys are taken into account, which I don't want.

### Code example

<details><summary><code>main.go</code></summary>

g.InputText(&doc_tags_test).AutoComplete(liste_tags),
			g.Custom(func() {
				if g.IsKeyPressed(g.KeyEnter) && g.IsItemActive() {
					fmt.Println("Enter")
				}
			}),

</details>

### To Reproduce

1. Run my demo

### Version

v0.6.1

### OS

Linux Manjaro

**Comment by gucio321** [comment]
@schabil I'd suggest you to try with `(*InputTextMultilineWidget).Callback(...)`
btw @AllenDang IMO `imgui.InputTextCallbackData` needs some API in giu

**Comment by gucio321** [comment]
it was resolved in #660
