### ISSUE TITLE
GetItemRect methods aren't in the bindings

### ISSUE THREAD

**Issue by JonSnowbd** [AllenDang/giu#47]
https://github.com/AllenDang/giu/blob/master/imgui/imgui.h#L686 

These 3 functions are pretty important for custom drawing, and I don't think the bindings include them.

**Comment by AllenDang** [comment]
@JonSnowbd Sure thing, I'll add them soon.

**Comment by JonSnowbd** [comment]
I appreciate it! Loving the framework

**Comment by AllenDang** [comment]
@JonSnowbd GetItemRectMin, GetItemRectMax and GetItemRectSize are wrapped. You could use them by invoking imgui.GetItemRectxxx

**Comment by JonSnowbd** [comment]
Thanks a lot, I appreciate it!
