### ISSUE TITLE
use a loop in layout (or explain how this can be done)

### ISSUE THREAD

**Issue by MarcelXia** [AllenDang/giu#471]
### Related problem

g.Layout{
	for key, record := range records  {
		g.Selectable(record.Name).OnClick(func() { fmt.Println(key) }),
	}
},

### Your request

The widget page only show "hard" ways of doing stuff, but for this, I want to see how this kind of things can be done.

**Comment by gucio321** [comment]
@MarcelXia you need to use `giu.Custom(func() {/*your for loop*/})`

**Comment by dqhieuu** [comment]
@MarcelXia You can use the `...` operator to unpack a slice into individual variables.

First create a slice of unpackable giu elements, in you case, `[]*g.Selectable`
```
var selectables []*g.Selectable{}
for key, record := range records {
   selectables = append(selectables, g.Selectable(record.Name).OnClick(func() { fmt.Println(key) }))
}
```
Then add the unpacked slice in the giu element like this
```
g.Layout{
  selectables...
}
```

**Comment by gucio321** [comment]
Yah and one more thing. Be aware that if the records variable is a map the iteration order will be different each frame!

**Comment by gucio321** [comment]
@MarcelXia any updates here?
