### ISSUE TITLE
Fonts - problem with latin extended

### ISSUE THREAD

**Issue by rjablecki** [AllenDang/giu#48]
Hello, I have problem with polish characters like `ąśćłóĄ` etc. My code below: 

`	fonts := g.Context.IO().Fonts()
	fontPath := "OpenSans-Regular.ttf"
	fonts.AddFontFromFileTTFV(fontPath, 16, imgui.DefaultFontConfig, fonts.GlyphRangesDefault())` 

Polish characters are replaced with ?. How to solve this problem ?

**Comment by AllenDang** [comment]
@rjablecki 
The fonts.GlyphRangesDefault controls what character will be displayed.
To display chinese, I will use GlyphRangesChineseCommon, so I guess latin works the same.
I think ImGUI should have latin glyph ranges defined. 
Sorry that I cannot give a direct answer, because I'm on the train.

**Comment by rjablecki** [comment]
I resolved my problem using that code:
`	fonts := g.Context.IO().Fonts()
	builder := imgui.NewFontGlyphRangesBuilder()
	ranges := imgui.NewGlyphRanges()
	builder.AddText("ęóąśłżźćńŁŻ")
	builder.AddRanges(fonts.GlyphRangesDefault())
	builder.BuildRanges(ranges)
	fontPath := "fonts/Lato-Regular.ttf"
	fonts.AddFontFromFileTTFV(fontPath, 14, imgui.DefaultFontConfig, ranges.Data())`
