### ISSUE TITLE
[Feature Request] SplitLayout needs access to sashPos position after dragging

### ISSUE THREAD

**Issue by rasteric** [AllenDang/giu#485]
### Related problem

I have a relatively complex desktop layout and SplitLayout has serious limitations. While the sashPos can be set when rendering/building the widget, it cannot be obtained after the user has dragged the divider. This is needed to store the splitter state and recall it later (e.g. after program restart).

### Your request

`SplitPos() float32` - return the splitter position

Or, even better, a way to set and get the position as a percentage of windows space available to the widget.

### Alternative solution

This has no workaround, since sashPos is private.

### Additional context

![layout](https://user-images.githubusercontent.com/29521722/160153999-178a519b-688a-44b9-bbf4-0bc97b4b3b17.png)

**Comment by gucio321** [comment]
well, you're right, sashPos argument should be a pointer that you can edit.
see #486
