### ISSUE TITLE
Auto-Center a WindowFlagsAlwaysAutoResize PopupModal

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#488]
I have a PopupModal, in which the contents are rendered dynamically. I have the WindowFlagsAlwaysAutoResize flag so the popup will resize to fit the contents, however, the popup itself is not auto-centering itself after resizing. Is there a "WindowFlagsAlwaysAutoCenter" flag or something like that? Thank you.
![Screenshot (287)](https://user-images.githubusercontent.com/48808396/160320751-d52d13b9-5149-4bc9-ae85-02dd1e3dadea.png)
![Screenshot (288)](https://user-images.githubusercontent.com/48808396/160320761-c72c8b2d-49d9-4b96-99c5-1ef0ca59f354.png)

**Comment by AllenDang** [comment]
@HACKERALERT Popup with same ID will be located at same position. So there are two approaches here:
1. Use a different ID each time when open a popup.
2. Calculate the window position and set it directly via `SetNextWindowPostision`.

**Comment by HACKERALERT** [comment]
How interesting... Thanks!
