### ISSUE TITLE
Can't always get correct size of content region

### ISSUE THREAD

**Issue by ryn1x** [AllenDang/giu#49]
Sometimes when I call `imgui.ContentRegionAvail()` I get the current size of the content region, but other times I do not.

For example, in the following snippet I display an image and a histogram in a split layout. The histogram correctly fills it's content area, but the image does not. If I instead use -1 as the image width and height it does fill the area, but as far as I can tell that just eventually calls `imgui.ContentRegionAvail()`. The reason I cannot use -1 for width and height is because I need to pass the width to my own function `getScaledHeight()` that will return a height, based on the current width, that maintains the image's original aspect ratio.

example:
```go
func loop() {
	g.SingleWindow("main", g.Layout{
		g.SplitLayout("image/hist split", g.DirectionVertical, true, 800,
			g.Layout{
				g.Label(imageName),
				g.Image(imgT, imgui.ContentRegionAvail().X, getScaledHeight(imgui.ContentRegionAvail().X)),
			},
			g.Layout{
				g.Custom(func() {
					if len(image32) > 0 {
						imgui.PlotHistogramV("", image32, 0, "", math.MaxFloat32, math.MaxFloat32, imgui.Vec2{X: imgui.ContentRegionAvail().X, Y: imgui.ContentRegionAvail().Y})
					}
				}),
			}),
	})
}
```

**Comment by AllenDang** [comment]
@ryn1x The reason you feel the ContentRegionAvail doesn't work is, when you call it in g.Image, the split layout doesn't really be created, so at the moment available region is the whole window.

Because g.Layout is a struct, it will be created BEFORE the actual imgui widgets creation.

To get the expected content region, create g.Image inside g.Custom like below.

```
g.Custom(func() {
  w, _ := g.GetAvaiableRegion()
  g.Image(imgT, w, getScaledHeight(w)).Build()
})
```

**Comment by ryn1x** [comment]
Thanks! This works. I get a feedback loop now because my height depends on width and the vertical scroll bar is flashing on and off. Is there a way to just permanently enable the vertical scrollbar in just this split? Or find the width of the scroll bar to offset by?

**Comment by ryn1x** [comment]
I have found "WindowFlagsAlwaysVerticalScrollbar", but no examples use WindowFlags, only MasterWindowFlags.

**Comment by ryn1x** [comment]
Not sure if it is the best way (got the idea from some C++ code), but I got it working with:
```
g.Custom(func() {
	w, h := g.GetAvaiableRegion()
	imgui.BeginChildV("always vert scrollbar", imgui.Vec2{X: w, Y: h}, false, imgui.WindowFlagsAlwaysVerticalScrollbar)
	g.Image(imgT, w, getScaledHeight(w)).Build()
	imgui.EndChild()
})
```

**Comment by AllenDang** [comment]
@ryn1x That's the correct way to do it. But you could simply use g.Child to wrap up the code.

**Comment by ryn1x** [comment]
Ah ok. Thank you so much! What an awesome job you have done with this project!
