### ISSUE TITLE
Possible Bug with ImageWidget for displaying parts of images

### ISSUE THREAD

**Issue by Geo5** [AllenDang/giu#490]
Hi,
I think there may be a bug/limitation in the giu wrapper for the image widget:
The uv0 and uv1 fields are of type `Point{ int , int} `in giu
https://github.com/AllenDang/giu/blob/a85dc093a122dd17d7c31bb57107f61546906cf8/ImageWidgets.go#L24
but to my understanding they represent the fraction of the image to be shown (between 0.0 and 1.0) in imgui itself.
The int values get converted to floats later, in `ToVec2`:
https://github.com/AllenDang/giu/blob/a85dc093a122dd17d7c31bb57107f61546906cf8/ImageWidgets.go#L101

So at the moment it is not possible to only show a partial area of an image like in the original imgui demo (the tooltip shows a zoomed in part of the image):
https://github.com/ocornut/imgui/blob/88fbc31ee08238750ed1070ca5181fb2d67d0927/imgui_demo.cpp#L1044

**Comment by gucio321** [comment]
you may be right. @AllenDang shouldn't this be divided by 255 in order to convert intagers into 0-1 float?
```golang
// ToVec2 converts image.Point to imgui.Vec2.
func ToVec2(pt image.Point) imgui.Vec2 {
        return imgui.Vec2{
                X: float32(pt.X),
                Y: float32(pt.Y),
        }
}
```

```golang
// ToVec2 converts image.Point to imgui.Vec2.
func ToVec2(pt image.Point) imgui.Vec2 {
        return imgui.Vec2{
                X: float32(pt.X)/255,
                Y: float32(pt.Y)/255,
        }
}
```

**Comment by gucio321** [comment]
@AllenDang sure, I can open a PR, but.... how to change Point ( struct {int,int} ) to float? do you mean imgui.Vector2 or just 4 float arguments?

**Comment by AllenDang** [comment]
@gucio321 4 float arguments should do the trick.
