### ISSUE TITLE
[Feature Request] Add rotation for textures and widgets

### ISSUE THREAD

**Issue by VityaSchel** [AllenDang/giu#493]
### Your request

Add rotation property to AddImage method in https://github.com/AllenDang/giu/blob/a85dc093a122dd17d7c31bb57107f61546906cf8/Canvas.go#L150

**Comment by gucio321** [comment]
@VityaSchel maybe try to ask in ocornut/imgui first.

**Comment by VityaSchel** [comment]
> @VityaSchel maybe try to ask in ocornut/imgui first.

I opened https://github.com/inkyblackness/imgui-go/issues/181

**Comment by gucio321** [comment]
@VityaSchel  I've analyzed the issue in imgui-go and:
As far as i understand giu.Cancas is missing AddImageQuad right?

**Comment by gucio321** [comment]
fix comming :smile:
