### ISSUE TITLE
[bug] SplitLayout (DirectionHorizontal == Vertical?) & (DirectionVertical == Horizontal?)

### ISSUE THREAD

**Issue by gadmin88** [AllenDang/giu#496]
### What happend?

![image](https://user-images.githubusercontent.com/61587283/161964076-0b392362-3615-4588-94c2-07daac68797e.png)

Vertical and Horizontal turned around in wrong direction

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	showWindow2 bool
	checked     bool
)

func onShowWindow2() {
	showWindow2 = true
}
func onHideWindow2() {
	showWindow2 = false
}

func loop() {

	// Bug
	g.Window("DirectionHorizontal").Pos(300, 23).Size(100, 400).Layout(
		g.SplitLayout(g.DirectionHorizontal, 50,
			g.Layout{
				g.Label("Horizontal 1"),
			},
			g.Layout{
				g.Label("Horizontal 2"),
			},
		),
	)
	// Bug
	g.Window("DirectionVertical").Pos(500, 23).Size(100, 400).Layout(
		g.SplitLayout(g.DirectionVertical, 50,
			g.Layout{
				g.Label("Vertical 1"),
			},
			g.Layout{
				g.Label("Vertical 2"),
			},
		),
	)

	g.Window("Window 1").Pos(2, 23).Size(250, 400).Layout(
		g.Row(
			g.Label("-------"),
		),

		g.Label("I'm a label in window 1"),
		g.Button("Show Window 2").OnClick(onShowWindow2),
	)

	if showWindow2 {
		g.Window("Window 2").IsOpen(&showWindow2).Flags(g.WindowFlagsNone).Pos(254, 23).Size(500, 200).Layout(
			g.Label("I'm a label in window 2"),
			g.Button("Hide me").OnClick(onHideWindow2),
		)
	}
}

func main() {
	wnd := g.NewMasterWindow("Multi sub window demo", 600, 400, 0)
	wnd.Run(loop)
}

```

</details>

### To Reproduce

1. Run my demo
2. will see the error

### Version

v0.6.2

### OS

Windows 10 x64

**Comment by gucio321** [comment]
I think that `DirectionHorizontal` and `DirectionVertical` means that the area is getting splitted horizontally/vertically rather, than the line is horizontal/vertical

It depends on how did you understand the idea, names DirectionHorizontal/Vertical are comming from. In both cases it could be correct :grinning:

**Comment by gucio321** [comment]
oh, yah, I can see, you mean that the comments are wrong?
![image](https://user-images.githubusercontent.com/73652197/161996188-d7cccaf2-1a1b-46ce-9e84-639aced04160.png)

**Comment by gadmin88** [comment]
Did anybody can climb a ladder up horizontally? - just ask for a friend (smile)

**Comment by gucio321** [comment]
well, let @AllenDang decide if we should change this, thats just variables naming, so it shouldn't be a big deal.
also @gadmin88 if you're so kind to open a PR, your contribution is very welcome!

**Comment by gadmin88** [comment]
well, i look what i can do, but i am not rly active on github, as i am more gitlab friend 👍

just renaming variables did not work, just tested it.

**Comment by gadmin88** [comment]
Okay, i got it working

![image](https://user-images.githubusercontent.com/61587283/162034194-9d525fa6-dd42-48bb-82b2-d06784e26316.png)

Changes in SplitLayout.go from Master 

**Horizontal:**
![image](https://user-images.githubusercontent.com/61587283/162035086-7a413c2d-a8c5-4656-80a8-862e6028a7bf.png)

**Vertically:**
![image](https://user-images.githubusercontent.com/61587283/162035257-74c083b1-cb87-4317-8769-0379d4f1b9b4.png)

**Comment by gadmin88** [comment]
> well, let @AllenDang decide if we should change this, thats just variables naming, so it shouldn't be a big deal. also @gadmin88 if you're so kind to open a PR, your contribution is very welcome!

PR done 👍 -
