### ISSUE TITLE
Widget rendering by condition.

### ISSUE THREAD

**Issue by bezrazli4n0** [AllenDang/giu#5]
Hi, how i can render widgets by conditions with new layout system?, for ex. if true => render button. With previous layout system it's will possible.

**Comment by AllenDang** [comment]
@bezrazli4n0 Thanks for your usage for giu. I redesigned several times of the layout system recently, I hope it doesn't waste too much of your time to refine the existing code.
With the latest version, I add back the Custom widget, which you could use it as before. And I also added a new widget called Condition which aims to your case, try it out.
