### ISSUE TITLE
[Feature Request] Global key press event

### ISSUE THREAD

**Issue by aj3423** [AllenDang/giu#501]
### Related problem

I'm writing a debugger, there is an `giu.InputText` for typing commands. It isn't always focused because user may click somewhere else, I want to auto-focus the input when user start typing commands, instead of clicking it to gain focus manually.

I see `giu.Event().OnKeyPressed()` and `giu.IsKeyPressed()`, they both require a specific key code. Possible to monitor key event globally?

### Your request

.

**Comment by gucio321** [comment]
Thats only my suppose:
maybe Dear ImGUI will handle something like:
```golang
KeyAny = KayA| KeyB | KeyC // etc
```

**Comment by gucio321** [comment]
well, @aj3423 I've solved this. please take a look on https://github.com/AllenDang/giu/pull/504

**Comment by aj3423** [comment]
@gucio321 Thanks. it still need some "adjustment", but works now.
```go
package main

import (
	"fmt"
	"strings"

	g "github.com/AllenDang/giu"
)

var input string

var focused bool
var should_focus bool

func loop() {
	g.SingleWindow().Layout(
		g.Custom(func() {
			if should_focus {
				should_focus = true
				focused = true
				g.SetKeyboardFocusHere()
			}
			g.InputText(&input).Build()
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("", 400, 300, 0)

	wnd.SetAdditionalInputHandlerCallback(func(key g.Key, mod g.Modifier, act g.Action) {
		if !focused && act == g.Press {
			input += strings.ToLower(string([]byte{byte(key)}))
			should_focus = true
		}
		fmt.Println(key, mod, act)
	})
	wnd.Run(loop)
}
```

**Comment by gucio321** [comment]
@aj3423 I did an example for that issue here: https://github.com/AllenDang/giu/blob/9e3f60abdd963f8e7da62133b2d9a2b3c1459356/examples/issue-501/main.go it should be what you're looking for
