### ISSUE TITLE
Is it possible to dynamically title a TabItem using an InputText within the tab

### ISSUE THREAD

**Issue by blindraccoon** [AllenDang/giu#503]
I'd like to be able to dynamically change the TabItem text while editing a text field within said tab.  When I execute the following when I press a key in the InputText it seems the focus changes away to somewhere and I must click back into the text input field to continue.  Even if I clone the string used in the TabItem and use that it does not work as I expected.

Am I out of luck or more likely just not doing it correctly.

```go
package main

import (
	"strings"
	"github.com/AllenDang/giu"
)

var name string = "value"
var test string

func loop() {
	test = strings.Clone(name)
	giu.SingleWindow().Layout(
		giu.TabBar().TabItems(
			giu.TabItem("Tab Title " + name).Layout(
				giu.InputText(&name),
			),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("tab issue", 640, 480, 0)
	wnd.Run(loop)
}
```

**Comment by gucio321** [comment]
Yah, I can imagine why this occure.
when you're changing TabItem's title, its ID is getting changed as well, so , technically, your layout is becoming completly another one for imgui. So the text field, you've edited in the previous frame doesn't exist anymore and you're editing another one.
I dont have any idea for now to workaround it...

**Comment by blindraccoon** [comment]
Okay, with your explanation and some more paying around it makes sense now.  I'll work around this not-really-very-big issue another way.  No problem.

Thanks for the response and explanation.
