### ISSUE TITLE
[Feature Request] Expose tStr() or equivalent functionality to programmer

### ISSUE THREAD

**Issue by rasteric** [AllenDang/giu#507]
### Related problem

Currently, display strings font atlas processing is all internal and `tStr()` is not available outside the Giu package. This makes it harder to write custom widgets. (Or, I'm wrong about this and there a better way to do it. In that case, please let me know and close the issue.)

### Your request

Add a function `TStr()` or one with more informative name such as `RegisterStr()` to `Utils.go` that wraps ` tStr()`, to make it easier to create widgets that have to register label strings in the font atlas cache and trigger a recomputation in `FontAtlasProsessor.go` [sic]. Or, just rename all instance of `tStr()` to `TStr()`.

### Alternative solution

Maybe I'm wrong but it seems that registering with `tStr` is needed to display all glyphs correctly. A workaround would be to use an invisible control that does register the string internally.

### Additional context

The problem occurred when I tried to make my own `SliderDurationWidget` based on taking `SliderFloatWidget` as example. It uses `tStr()` in a call to `imgui.SliderFloatV`.

**Comment by gucio321** [comment]
sound fair enough to me
