### ISSUE TITLE
[Feature Request]How do I get clipboard content

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/giu#511]
### Your request

How do I get clipboard content

**Comment by sgosiaco** [comment]
You can do something along the lines of
```go
package main

import g "github.com/AllenDang/giu"

var (
	input  = ""
	output = ""
)

func getClipboard() {
	output = g.Context.GetPlatform().GetClipboard()
}

func setClipboard() {
	g.Context.GetPlatform().SetClipboard(input)
}

func loop() {
	g.SingleWindow().Layout(
		g.Row(
			g.Label("Input: "),
			g.InputText(&input).Size(200),
			g.Button("Set Clipboard").OnClick(setClipboard),
		),
		g.Row(
			g.Labelf("Output: %s", output),
			g.Button("Get Clipboard").OnClick(getClipboard),
		),
	)
}

func main() {
	wnd := g.NewMasterWindow("Clipboard Demo", 400, 200, g.MasterWindowFlagsNotResizable)
	wnd.Run(loop)
}
```
Where the main two functions for interacting with the clipboard are
```go
g.Context.GetPlatform().GetClipboard()
g.Context.GetPlatform().SetClipboard(input)
```

**Comment by lzytaro** [comment]
> You can do something along the lines of
> 
> ```go
> package main
> 
> import g "github.com/AllenDang/giu"
> 
> var (
> 	input  = ""
> 	output = ""
> )
> 
> func getClipboard() {
> 	output = g.Context.GetPlatform().GetClipboard()
> }
> 
> func setClipboard() {
> 	g.Context.GetPlatform().SetClipboard(input)
> }
> 
> func loop() {
> 	g.SingleWindow().Layout(
> 		g.Row(
> 			g.Label("Input: "),
> 			g.InputText(&input).Size(200),
> 			g.Button("Set Clipboard").OnClick(setClipboard),
> 		),
> 		g.Row(
> 			g.Labelf("Output: %s", output),
> 			g.Button("Get Clipboard").OnClick(getClipboard),
> 		),
> 	)
> }
> 
> func main() {
> 	wnd := g.NewMasterWindow("Clipboard Demo", 400, 200, g.MasterWindowFlagsNotResizable)
> 	wnd.Run(loop)
> }
> ```
> 
> Where the main two functions for interacting with the clipboard are
> 
> ```go
> g.Context.GetPlatform().GetClipboard()
> g.Context.GetPlatform().SetClipboard(input)
> ```

thank u very much
