### ISSUE TITLE
[Feature Request] Docking

### ISSUE THREAD

**Issue by bandithedoge** [AllenDang/giu#512]
### Your request

There is a [fork](https://github.com/ptxmac/imgui-go/tree/docking) of imgui-go that uses the `docking` branch of Dear ImGui. Would it be possible to use docking in `giu`?

**Comment by AllenDang** [comment]
@bandithedoge Yes, it is possible, just need time to rewrite the platformer and renderer. It's on my list, and will do it soon.

**Comment by gucio321** [comment]
@AllenDang any updates?

**Comment by AllenDang** [comment]
@gucio321 Doing...

**Comment by Aronii** [comment]
Hey @AllenDang,
are there any new or an eta on this?

**Comment by AllenDang** [comment]
@Aronii I'm changing the upstream imgui from imgui-go to auto-generated cimgui-go, and I did get some progress, you could try docking branch, note I'm still working on it, some features may not ready at this point.
