### ISSUE TITLE
more effective state system

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#517]
### Related problem

writing state system impl takes always a lot of time, like:
- implement widgetState struct
- implement constructor for it
these points are constant, however, I need to write as well:
- getState method that gets state from giu, runs constructor if it is nil or does tpecasting if it isn't

### Your request

Context.GetState returns Disposable but now, when generics are on, it could return the exact type right?

**Comment by AllenDang** [comment]
@gucio321 Agree, it's better to return actural type rather then interface.

**Comment by gucio321** [comment]
meh, unfortunetly, method cannot have type parameter :-(
```console
./Context.go:108:27: syntax error: method must have no type parameters
```
so it isn't possible yet or I'm doing something wrong
![image](https://user-images.githubusercontent.com/73652197/172198619-e1592a3a-4f27-46d1-aea6-3baca41c9a05.png)

**Comment by gucio321** [comment]
it is fixed
