### ISSUE TITLE
Use existing *glfw.Window?

### ISSUE THREAD

**Issue by Sann0** [AllenDang/giu#52]
Im trying to integrate giu with github.com/faiface/pixel. Since pixel is using glfw aswell is there a way to draw a giu SingleWindow into a existing *glfw.Window?

I also want to ask how I could manually quit the giu mainloop since I'm using the frameless window flag.

**Comment by AllenDang** [comment]
@Sann0 Sorry for the late response. I'm not very familiar with opengl, but inside giu, it uses opengl as render and glfw as platfomer. Theoretically it can be integrated into your engine with different platformer implementation.
