### ISSUE TITLE
Integration with game libraries?

### ISSUE THREAD

**Issue by 0Alireza-Ta0** [AllenDang/giu#527]
### Your request

Hello

Is there a way to use this package with game related packages like ebiten or raylib-go?

Thanks!

**Comment by AllenDang** [comment]
@0Alireza-Ta0 You will need to write your own platformer and renderer. You could check the implementation in github.com/AllenDang/imgui-go, should be very straight forward.

**Comment by gucio321** [comment]
So in order to do so we at least need to export (or even add) SetPlatform method

**Comment by gucio321** [comment]
@0Alireza-Ta0 may we close this issue?

**Comment by gucio321** [comment]
Closing as likely fixed. Feel free to ping me if you think it should be re-opened.
