### ISSUE TITLE
[bug]can not input chinses in InputText

### ISSUE THREAD

**Issue by bobxiao163** [AllenDang/giu#543]
### What happend?

When run sample of widgets, i cannot input chinese in the InputText widget.

golang 1.18

### Code example

examples/widgets/widgets.go
		g.InputText(&name).Label("Input text with auto complete, input hw and press enter").Size(300).AutoComplete(autoCompleteCandidates),

### To Reproduce

1. Run my demo
2. will see the bug...

### Version

(latest)

### OS

MacOS Montery 12.5.1

**Comment by AllenDang** [comment]
I just tested with newest master, I could input chinese text

**Comment by AllenDang** [comment]
![截屏2022-08-29 13 44 17](https://user-images.githubusercontent.com/18550/187131013-011f6acb-1fb1-43a7-9a1d-3e862b5702e6.png)

**Comment by bobxiao163** [comment]
thank for your reply.

I test again, and found QingG is not supported, but built-in input method is supported
