### ISSUE TITLE
[Feature Request]When i input chinese, it desplay as "????"

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/giu#545]
### Related problem

![image](https://user-images.githubusercontent.com/62502682/187388092-cb219fef-a0e5-4599-96d6-f8f8de7efac9.png)

### Your request

My InputTextMultiline cannt input chinese, all dispaly as "????"

**Comment by AllenDang** [comment]
It's means giu cannot find default chinese font on your system. Check `FontAtlasProcessor.go, you will see there are a list of fonts be added to support various languages.

**Comment by lzytaro** [comment]
> 

like this? it seems dont work

func main() {
	g.SetDefaultFont("STHeiti", 13)
	wnd := g.NewMasterWindow("Hello World", 400, 200, 0)
	wnd.Run(loop)
}`

**Comment by lzytaro** [comment]
> It's means giu cannot find default chinese font on your system. Check `FontAtlasProcessor.go, you will see there are a list of fonts be added to support various languages.

oh, i found it. when i define s as global variable, it works. its amazing ! why?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/62502682/187450131-c7bb9793-907d-48b0-8f05-67c90925c908.png">

**Comment by AllenDang** [comment]
@lzytaro 'loop' function's name tells the reason, it will be called 60 times per second to draw the UI, if you define variable inside it, meaans it's value will be reset before a draw call.
So, rule is simple, dont define any varialbe inside the loop.

**Comment by lzytaro** [comment]
> @lzytaro'loop'函数的名字说明了原因，它每秒会被调用60次来绘制UI，如果你在里面定义了变量，意味着它的值将在绘制调用之前被重置。 所以，规则很简单，不要在循环内定义任何变量。

thanks very much!
