### ISSUE TITLE
[bug] Binary program icon

### ISSUE THREAD

**Issue by caitou2019** [AllenDang/giu#546]
### What happend?

<img width="430" alt="image" src="https://user-images.githubusercontent.com/47804016/187879595-7d21bbbc-daea-41f6-a225-5faf4b36225a.png">

Hi, I have a problem.
Binary program icon is not displayed

### Code example

<details><summary><code>main.go</code></summary>

```golang
func main() {
	wnd = g.NewMasterWindow("GO", 640, 280, 0)
	box := packr.New("res", ".\\res")
	bt, err := box.Find("gopher.png")
	if err != nil {
		fmt.Println(err.Error())
	} else {
		if img, _, err := image.Decode(bytes.NewReader(bt)); err == nil {
			wnd.SetIcon([]image.Image{img})
		} else {
			fmt.Println(err.Error())
		}
	}

	wnd.Run(loop)
}
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

(latest)

### OS

win10

**Comment by AllenDang** [comment]
Set icon to MasterWindow only affects the runtime windows icon, not the binary icon. You should google how to set icon to binary. And there is a tool inside giu which could help, check 'cmd/gmdeploy'.

**Comment by caitou2019** [comment]
OK, thank you for your reply
