### ISSUE TITLE
[Feature Request]how to show the real line value when my mouse move on the line

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/giu#550]
### Your request

how can i display the value when the cursor move to the line
![image](https://user-images.githubusercontent.com/62502682/189319660-7dbe8b17-5d78-4d5c-8318-a4b975c6dd46.png)

**Comment by lzytaro** [comment]
like this, any solution?
![image](https://user-images.githubusercontent.com/62502682/191149510-631b2d4b-fe16-4d8f-9d41-ad341ff26be3.png)

**Comment by lzytaro** [comment]
like this, any solution?
![83978117-db36b800-a922-11ea-8ad1-79c1dcabc867](https://user-images.githubusercontent.com/62502682/191149658-40292f0c-97bb-44ef-a734-1d74dcab5aa3.gif)

**Comment by gucio321** [comment]
@lzytaro as far as I can see [Implot](https://github.com/epezent/implot) doesn't support this feature yet.

**Comment by gucio321** [comment]
I'm sorry for late reply :cry:
I have to send you to https://github.com/epezent/implot.
I've opened `imgui.PlotShowDemoWindow`. There is one plot with tooltips but not really similar to this one you posted in your video.
I'll close this for now. Let me know if you still need help.
