### ISSUE TITLE
Combo: combo widget in table is sized incorrectly

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#566]
### What happend?

I'm putting ComboWidget inside the table cell. I've noticed that width of the widget is incorrect (much smaller than the column)

![image](https://user-images.githubusercontent.com/73652197/194709999-fb718780-ce3d-4e7b-846e-c8117984bb3b.png)

Calling `.Size(giu.Auto)` doesn't help (it did for InputText widget)

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import "github.com/AllenDang/giu"

var (
	value int32
	list  []string = []string{"1", "2", "3"}
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Table().Columns(
			giu.TableColumn("Column 1"),
			giu.TableColumn("Column 2"),
		).Rows(
			giu.TableRow(
				giu.Combo("##my combo", list[value], list, &value),
				giu.Label("<- why is there so large padding?"),
			),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("X padding in table cells [issue]", 640, 480, 0)
	wnd.Run(loop)
}

```

</details>

### To Reproduce

1. Run my demo
2. you'll see the bug described above

### Version

master

### OS

Fedora 36

**Comment by AllenDang** [comment]
@gucio321 It's really strange. Combo's width even doesn't work when it's not in table. Might be a bug inside imgui.

**Comment by gucio321** [comment]
@AllenDang I didn't test in tables but they work now in normal conditions perfectly in plain cimgui:
```c++ 
           ImVec2* size = new ImVec2(200, 80);
            if (ImGui::Button("I'm 100 size", *size)) {}

            int currentItem;
            ImGui::PushItemWidth(200);
            if (ImGui::Combo("##combo", &currentItem, "item0i", 2)) {}
            ImGui::PopItemWidth();
```

![image](https://github.com/AllenDang/giu/assets/73652197/3deb63ab-a0d4-4dc9-a81f-8ef532ef94f7)

**Comment by AllenDang** [comment]
@gucio321 Seems it's a upstream issue and has been solved.
