### ISSUE TITLE
Mouse events can affect the triggering of keyboard events

### ISSUE THREAD

**Issue by SuperLiveYou** [AllenDang/giu#571]
### What happend?

When capturing keyboard events, clicking the left mouse button will cause serious delay in calling keyboard events (After testing, only the left mouse button will cause delay, and there will be no problem with mouse movement and right button)

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"fmt"
	g "github.com/AllenDang/giu"
)

var b = 0

func loop() {
	g.SingleWindow().Layout(
		g.Child().Size(-1, -1),
		g.Event().OnKeyPressed(g.KeyS, func() {
			b++
			fmt.Println(b)
		}),
	)
}
func main() {
	wnd := g.NewMasterWindow("TestWindow", 800, 480, 0)
	wnd.Run(loop)
}

```

</details>

### To Reproduce

1. Run my demo
2. Now, long press the S key, and then click the left mouse button continuously. You can see the delay very clearly (see Output Number)

### Version

master

### OS

windows 11

**Comment by AllenDang** [comment]
@SuperLiveYou It's a backend issue. It is fixed on `docking` branch of giu which uses the newest imgui backend. I'm migrating functions from `master` to `docking`, current progress is about 80%.
