### ISSUE TITLE
Row widget: strange behaviour when using CustomWidget

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#572]
### What happend?

when using CustomWidget inside RowWidget (especially as a last of the widgets), imgui.SameLine() is called incorrectly.

### Code example

<details><summary><code>main.go</code></summary>

```golang
giu.Row(
   giu.Label("Hi!"),
   giu.Custom(func() { fmt.Println("Hello world!") }),
),
giu.Label("I'll be next to Hi label... - it shouldn't happen"),
```

</details>

### To Reproduce

1. Run my demo
2. You'll see that both labels are in the same line

### Version

(latest)

### OS

fedora workstation 36

**Comment by gucio321** [comment]
@AllenDang what do you think about the following solution, I've tought about:
in (*RowWidget).Build:
- before rendering widget save giu.GetCursorPos()
- render widget
- check if new CursorPos is diffrent and (if so) call imgui.Sameline

sadly, it could affect performency... maybe add something like giu.Row(...).AutoDetectCursorMove(true)?

**Comment by AllenDang** [comment]
@gucio321 RowWidget has a list of types inside to decide whether to call SameLine or not, I think this is the best solution right now to leverage performance.

**Comment by gucio321** [comment]
I think we can close this.
