### ISSUE TITLE
Enabling INI Support

### ISSUE THREAD

**Issue by kettek** [AllenDang/giu#58]
Is there any particular reason that the [MasterWindow disables imgui's INI system](https://github.com/AllenDang/giu/blob/862cb808a74133aac9e3483b7dfdd5be82b3aa8e/MasterWindow.go#L45)? Perhaps MasterWindow should take an additional parameter or expose a func that uses IO's `SetIniFilename`.

I am currently enabling INI support by calling `imgui.CurrentIO().SetIniFilename("...")`, though it'd be more in the spirit of giu not to reach into imgui's IO, imo.

**Comment by AllenDang** [comment]
@kettek The reason why disable INI support is multi-sub-window scenario is not common in desktop application development. Unlike the original usage for imgui in game engine.
You could enable it by using this ```g.Context.IO().SetIniFilename("...")```.

**Comment by kettek** [comment]
Fair enough, closing issue.
