### ISSUE TITLE
Plot: missleading type's names

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#584]
### What happend?

names of plot's elements are really missleading.
e.g. PlotBar**Widget** suggest that it should be used as always (e.g. like Label(...))
However it should be used inside Plot().Plots(...)
Maybe naming convention should be `PlotBarPlot` or something

### Code example

N/A

### To Reproduce

N/A

### Version

master

### OS

N/A

**Comment by AllenDang** [comment]
Agree, do you have time to make a PR?

**Comment by gucio321** [comment]
ok, will do later (probably when I'll need to work with plots again so really soon)
