### ISSUE TITLE
govet alert: copylocks

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#588]
Hi!
I was working on #587 and noticed the following govet's alerts:
```console
TextWidgets.go:231:38: copylocks: call of GetState[inputTextState] copies lock value: github.com/AllenDang/giu.context contains sync.Map contains sync.Mutex (govet)
	if state = GetState[inputTextState](Context, i.label); state == nil {
```

it seems serious - may cause unexpected panics imo

**Comment by asmaloney** [comment]
Yes, it is serious. It's copying mutex locks which is a no-no.

I have fixed it - I am just waiting for [#606](https://github.com/AllenDang/giu/pull/606) to be merged so I can avoid conflicts.
