### ISSUE TITLE
[bug] How to use Flags and Style functions on docking branch

### ISSUE THREAD

**Issue by SeyRyuu** [AllenDang/giu#589]
### What happend?

Hey,

I tried out the docking branch a bit further and I noticed that for example the window flags are not available when using the docking branch. Also for example, the Style function, all StyleVars and so on are not available. See the code below for some examples on this.

Are these functions still missing? Or are they available with other names or only through another package and not just giu alone like before?

I just run "go get github.com/AllenDang/giu@docking" with an empty project and go.mod file to compile/use the docking branch.

Kind regards

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"image/color"

	g "github.com/AllenDang/giu"
)


func test() {
	//Just sample code, no real function!

	//This code is no problem with the master branch of giu.
	//However, if you change to the docking branch instead, these functions/flags are not available

	g.Window("Test").Flags(g.WindowFlagsNoScrollWithMouse).Layout( //Missing g.WindowFlagsNoScrollWithMouse (window flags in general)
		g.Style().SetStyle(g.StyleVarScrollbarSize, 10, 10), //Everything missing
		g.Style().SetColor(g.StyleColorText, color.RGBA{}), //Everything missing, except color.RGBA
	)
}

```

</details>

### To Reproduce

1. Paste my demo into your IDE
2. Import giu@docking (will download cimgui, ...)
3. You will see the missing functions when using giu@docking

### Version

giu@docking (latest)

### OS

Linux, Windows, MacOS

**Comment by AllenDang** [comment]
Style setting is not yet be ported to docking branch. You could use Push/PopStyle APIs from imgui directly for now.

**Comment by gucio321** [comment]
@SeyRyuu see #593 
you can use my fork until the PR is open
`go mod edit -replace github.com/AllenDang/giu=github.com/gucio321/giu@docking`

**Comment by SeyRyuu** [comment]
Hey @gucio321 
cool, thank you. Works nicely. Makes more fun than using Push/Pop directly ^^, but still thanks for this solution @AllenDang , worked fine too.
