### ISSUE TITLE
Component sizing and default background

### ISSUE THREAD

**Issue by Esword618** [AllenDang/giu#590]
### Related problem

Giu is really surprised at me. It is very good. Its functions are very comprehensive. But I think its default background color is too dark. I suggest you give more choices. I hope the size of the component can be adjusted. The component is a little too small.

### Your request

It is recommended to add the function of component adjustment, and the function of background color adjustment,

**Comment by AllenDang** [comment]
@Esword618 Thanks! You could refer MasterWindow.go to see how the style is set and you could also change background color anytime.

**Comment by Esword618** [comment]
okay, thank you.
