### ISSUE TITLE
[bug] AlignCenter

### ISSUE THREAD

**Issue by fyw2020** [AllenDang/giu#596]
### What happend?

when use AlignCenter,button1 can not hover right, click invoke button2

### Code example

<details><summary><code>main.go</code></summary>

giu.Align(giu.AlignCenter).To(
			giu.Row(
				giu.Button("button 1"),
				giu.Button("button 2"),
			),
		),

</details>

### To Reproduce

1. Run align.go demo can see

### Version

(latest)

### OS

windows 2012 server

**Comment by gucio321** [comment]
I'll take a look

I suppose i've an idea! I can set rendering cursor's position when measuring widget's width to something completly outside the window and it will stil!

**Comment by fyw2020** [comment]
@AllenDang I use master github.com/AllenDang/giu v0.6.2.

**Comment by fyw2020** [comment]
I've go get github.com/AllenDang/giu@master ,the version update 0.6.2->0.6.3,the problem still exists.

**Comment by fyw2020** [comment]
I've go get github.com/AllenDang/giu@master ,the version update 0.6.2->0.6.3,the problem still exists.

**Comment by gucio321** [comment]
@fyw2020 it should be fixed now
could you try `go get github.com/AllenDang/giu@93764f0bddceea3aa29ef843a95e643f866541bf`

**Comment by fyw2020** [comment]
The alignment is correct after the update.Thank u.
