### ISSUE TITLE
installation/import problem

### ISSUE THREAD

**Issue by Esword618** [AllenDang/giu#597]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/73058062/203599384-74c187bf-0e7a-4fb1-8ed9-c7305cade5d9.png">

I'm confused about why I can't install package successfully when I install it like this. What should I do.

**Comment by Esword618** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/73058062/203606684-db911d11-13cb-4d22-884a-8baae38db9ad.png">
There are also problems with this installation. I can't always install it. I encountered this problem when running the transparent example.

**Comment by gucio321** [comment]
@Esword618 could you try to run the demo in terminal and show what does it say?

**Comment by Esword618** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/73058062/203677346-96e983d5-299f-45d1-a9a7-876f36dac771.png">

This is the result after I run it.

**Comment by gucio321** [comment]
very strange...

may I ask about a few more things:

0. close your IDE; open terminal and cd into giu/examples/transparent
1. output of `git diff` (it is possible that your IDE did something strange with example file)
2. if output isn't empty, run `git stash` to remove all the changes and then try `go mod tidy`
3. run `go run .` again and check what happens
4. if the problemm still exist, please tell me what is your version of giu (first line of `git log` or just `git log |head -n1`)

**Comment by gucio321** [comment]
@Esword618 any updates here?
