### ISSUE TITLE
Is there any way to implement a "select all" check box in table?[Feature Request]

### ISSUE THREAD

**Issue by fyw2020** [AllenDang/giu#599]
### Related problem

In the table demo and api,I can't found any method to implement a "select all" check box in the header row in a table.

Currently giu's table header row defined by g.TableColumn,it can not be customed.

### Your request

Is there any convenient way to achieve this effect?It's a common requirement

**Comment by fyw2020** [comment]
For example,the first column has only checkbox widget,and the checkbox in the header row effects as "select all" switch.

**Comment by AllenDang** [comment]
The check status is controlled by your bool variables, so to check any number of checkbox, just change the value of your bool variables.

**Comment by fyw2020** [comment]
Yes,I know.But where I can put the 'select all' checkbox,now I just can put it outside table .

**Comment by fyw2020** [comment]
If g.TableColumn can accept a widget ,not just a label?

**Comment by fyw2020** [comment]
In the imguidemowindow,I see a "Custom headers" Demo show but don't know how to implement by giu.

**Comment by AllenDang** [comment]
You can use a row as column by freeze it.

**Comment by fyw2020** [comment]
Good idea,tks!
