### ISSUE TITLE
[bug] go.mod imgui-go version incorrect

### ISSUE THREAD

**Issue by asmaloney** [AllenDang/giu#601]
### What happend?

In the go.mod file:

```
github.com/AllenDang/imgui-go v1.12.1-0.20220322114136-499bbf6a42ad
```

This is looking for version 1.12.1 of imgui-go which doesn't seem to exist, and commit hash [499bbf6a42ad](https://github.com/AllenDang/imgui-go/commit/499bbf6a42adab8262be85512f8328a1ebf325ee) refers to a commit on the master branch, so this seems to be incorrect.

So, I see two possibilities:

- If it's supposed to be tied to v1.12.0 (and I don't think it is), then that's the tag it should use and all imports should refer to `github.com/AllenDang/imgui-go/v1` instead of just `github.com/AllenDang/imgui-go`.
- If it's supposed to be on master at that commit, then the reference should be `github.com/AllenDang/imgui-go v0.0.0-20220322114136-499bbf6a42ad` and the imports can continue to use `github.com/AllenDang/imgui-go`.

### Code example

n/a

### To Reproduce

n/a

### Version

master

### OS

macOS

**Comment by gucio321** [comment]
@asmaloney this file is auto-generatet by go, so we can't controll them. Note that these hashes are not equivalents of git commits/tags

**Comment by asmaloney** [comment]
I know go generates these, but my guess is that it was generated with some other branch that no longer exists.

When I read this file, I see that "imgui-go is based on 1.12.1 and is at git hash 499bbf6a42ad on that branch". Which is clearly wrong.

> Note that these hashes are not equivalents of git commits/tags

In fact they are (otherwise humans would find this file pretty useless). From t[he docs](https://go.dev/doc/modules/version-numbers):

* **baseVersionPrefix** (vX.0.0 or vX.Y.Z-0) is a value derived either from a semantic version tag that precedes the revision or from vX.0.0 if there is no such tag.
* **timestamp** (yymmddhhmmss) is the UTC time the revision was created. In Git, this is the commit time, not the author time.
* **revisionIdentifier** (abcdefabcdef) is a 12-character prefix of the commit hash, or in Subversion, a zero-padded revision number.

Based on the go docs, it is incorrect.

**Comment by gucio321** [comment]
Well so my guess is, that go (for some reason) does not recognized the latest tag in allendang's repo as a "semantic versioning" and as a result it uses v1.12 (the tag that was latest one in inkyblackness's upstream at the time when Allen created his fork (changed module name))

Anyway, does this hash code cause any issue?

**Comment by asmaloney** [comment]
> does not recognized the latest tag in allendang's repo as a "semantic versioning"

It _should_ be v0.0.0 like all the others that are pinned to a specific commit without using proper versioning which is why this is perplexing.

I'm not sure where it's getting 1.12.1 since 1.12.1 clearly doesn't exist anywhere (this repo or the original).

> Anyway, does this hash code cause any issue?

Unclear. I got here because I was having issues with the linting stuff & thought it might be related to this incorrect versioning. I still haven't sorted that out yet. It's also - as I mentioned - misleading for humans reading this file.

I have used forks in other go.mod files and I don't recall ever having an issue like this.

Maybe a `go` bug? Or maybe they've done something else like the `go vendor` problem that they "won't fix" 😆

**Comment by gucio321** [comment]
I don't really care about this file as long as everything works fine tbh.

> It should be v0.0.0 like all the others that are pinned to a specific commit without using proper versioning which is why this is perplexing.

you're right, it'd be better to see it v0.0, but GO for some reasons doesn't thing so :smile:

> Maybe a go bug? Or maybe they've done something else like the go vendor problem that they "won't fix" laughing

very likely.

**Comment by L1ghtingBolt** [comment]
I can't even import the package due to this

**Comment by gucio321** [comment]
@L1ghtingBolt you need to remove your `vendor` directory for now
