### ISSUE TITLE
Is there any way to manual trigger interface refresh?

### ISSUE THREAD

**Issue by fyw2020** [AllenDang/giu#605]
The ui keeps unchanged if I do nothing with mouse or keyboard.

In some cases, I may just stare at the interface without any action，eg.Monitoring software interface

Then how can I manual trigger interface refresh?

**Comment by fyw2020** [comment]
wnd.Run(loop) seems that the interface refresh will not be triggered, as long as the mouse or keyboard has actions

**Comment by AllenDang** [comment]
Invoke giu.Update
