### ISSUE TITLE
How to drag a frameless window or get the monitor size?

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#607]
Sorry, this is not a bug. My issue is:

I need a narrow frameless window which just take a little part of screen, and I wish put it on the top center. or I can drag it to some place.

But I don't find a method to get the monitor size to make window center. Or how to drag a frameless window.

Thanks for your time. s^_^s

**Comment by gucio321** [comment]
For monitor size - neigher giu nor imgui-go share methods to do this. You can check in go-gl/glfw or google for module providing such a system info
for dragging window - it is most likely feature from docing branch

**Comment by damntourists** [comment]
Is there a plan or timeline for when the docking code might be merged?

**Comment by gucio321** [comment]
See #628

**Comment by gucio321** [comment]
```go
package main

import (
	"image/color"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.Window("I'm a window").Layout(
		giu.Label("Hello World"),
	)
}

func main() {
	wnd := giu.NewMasterWindow("Frameless window", 640, 480, giu.MasterWindowFlagsFrameless|giu.MasterWindowFlagsTransparent|giu.MasterWindowFlagsMaximized)
	wnd.SetBgColor(color.RGBA{255, 0, 0, 0})
	wnd.Run(loop)
}
```
this (or some variant of this :smile:) should help

**Comment by gucio321** [comment]
lmk if you still need help
