### ISSUE TITLE
[bug] Missing MouseButton function for ContextMenu on docking branch

### ISSUE THREAD

**Issue by SeyRyuu** [AllenDang/giu#609]
### What happend?

I just wanted to use the MouseButton func of the ContextMenu widget on the docking branch and noticed that this function is missing. Did the way of using the ContextMenu changed, or is this function missing in the docking branch?

The code example below works fine when using master branch instead.

Kind regards

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

func main() {
	wnd := g.NewMasterWindow("Testing", 600, 400, 0)
	wnd.Run(loop)
}

func loop() {
	g.SingleWindow().Layout(
		g.Label("Click here"),

		//".MouseButton(...)" is missing
		//"g.MouseButtonLeft" can be replaced with "cimgui.ImGuiMouseButton_Left" on docking)
		g.ContextMenu().MouseButton(g.MouseButtonLeft).Layout(
			g.Label("I'm a context menu"),
		),
	)
}
```

</details>

### To Reproduce

1. Switch to docking branch
2. Run my demo
3. Your IDE or at last your compiler will show you the missing .MouseButton(...) part

### Version

docking

### OS

Windows 11 x64, Ubuntu x64

**Comment by SeyRyuu** [comment]
Hey @gucio321 
thanks for the quick PR to fix this issue and the migration of more stuff ^^

**Comment by SeyRyuu** [comment]
Hey @gucio321 
working fine now, thank you. Also to @AllenDang for quick merging!

**Comment by SeyRyuu** [comment]
Hey @gucio321 
hehe, need to go one step back ^^. I just wanted to use the ContextMenu with func `.MouseButton(g.MouseButtonLeft)` and it won't work with the left mouse button, you need to press the right one.

Is this problem because of these lines?
https://github.com/AllenDang/giu/pull/610/files#diff-af8cfbd7fe7309c86f3dc1bd92d3342dac333f1342117db6f14b0e9a1b4a5b33R248-R249

**Comment by gucio321** [comment]
oh, yah, sorry, forgot about changing it there :smile:

**Comment by SeyRyuu** [comment]
Hey @gucio321 
thanks for the hint, using `g.ContextMenu().Flags(cimgui.ImGuiPopupFlags_MouseButtonLeft)` for example works fine.

But, i would say that the `.MouseButton(...)` fuction is the more easier way than using the flags and also the same way to change the mouse button in master-branch, but let this @AllenDang decide.

**Comment by AllenDang** [comment]
@gucio321 i think mousebutton function is better.
