### ISSUE TITLE
[bug]编译后在新的机器根本无法使用程序闪退

### ISSUE THREAD

**Issue by 1370339317** [AllenDang/giu#618]
### What happend?

在开发环境编译后，exe程序在新的机器无法打开，瞬间崩溃

### Code example

<details><summary><code>main.go</code></summary>

```golang
// put your code here!
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...
无需操作

### Version

(latest)

### OS

win10

**Comment by gucio321** [comment]
@1370339317 I'd suggest you speaking english. It seems to be commonly used language on GitHub :sweat_smile:

**Comment by gucio321** [comment]
@1370339317 ?
