### ISSUE TITLE
No way to close Window from Button

### ISSUE THREAD

**Issue by mlohstroh** [AllenDang/giu#62]
I love the library and the ability to create quick GUI's on the fly with this. 

However, I've run into an issue where I want to essentially stop the event loop because I don't need to maintain a window anymore, but want to run a process in the background. I don't see any way to close the window via a function that I can do via button press?

It looks like all I'd need to do there is stop the Main loop from running, but I can't seem to find a way to do that.

Is this possible or will something have to be built in?

**Comment by AllenDang** [comment]
@mlohstroh 
Close main window will result in quit the application. Can I know more about what are you going to archive?

**Comment by mlohstroh** [comment]
The UI is a very small part of the application. I use it to prompt the user for a username and password before running the rest of the application. It's essentially a log collector, which doesn't really need any information.

I figured whenever I needed to revalidate credentials, I could just open and close that authentication window on the demand, but the hooks for managing that lifecycle do not seem to be there.

**Comment by AllenDang** [comment]
A quick think solution is:
1. Separate the console and GUI into two applications.
2. Use RPC to communicate.
3. Launch GUI application whenever the console needs user input.

**Comment by mlohstroh** [comment]
I could certainly redo my architecture do make it work. I was hoping that this could be a library that I could just use a GUI on demand inside the same process. That's fine if that's not the purpose.

Are there any reasons to avoid adding a way to stop the main loop due to OS handling?

**Comment by AllenDang** [comment]
The major purpose of this package is to be a handy toolkit to create GUI desktop application, not GUI part of a terminal application.

**Comment by mlohstroh** [comment]
I understand. Thank you for the replies.
