### ISSUE TITLE
[bug]After compiling, the program cannot be used on other machine bases to crash

### ISSUE THREAD

**Issue by 1370339317** [AllenDang/giu#620]
### What happend?

go build -ldflags "-s -w -H=windowsgui -extldflags=-static" After being generated under the windows system, the machine in the development environment runs normally. I put the xxx.exe file on the new machine for use. After running, there is no Any interface, checked that the machine has opengl32.dll

### Code example

anlyone

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

(latest)

### OS

win10

**Comment by AllenDang** [comment]
Giu version (master branch? docking branch?) ? Go version? Your OS version and target OS version?

**Comment by 1370339317** [comment]
osversion: winserver 2016   nt:10.0.14393

**Comment by AllenDang** [comment]
@1370339317 Good to know it is solved.
