### ISSUE TITLE
Any way disable Selectable color?

### ISSUE THREAD

**Issue by fyw2020** [AllenDang/giu#622]
How to disable the selectable widget's hovered color and selected color change.It can't meet demand.

By default the selectable widget will change its own bgColor when mouse hovers and row selects. 

I want to change bgColor by table row's BgColor function in specific case.

**Comment by fyw2020** [comment]
I just want to know whick row is clicked or double clicked, then set bgColor of it.
I just to take advantage of the function of receiving event by selectable widget.
I don't want to the selectable widget change the hovered bgColor and selected color.

I want to set more than one bgColor of table row, the selectable widget can't do like this.

**Comment by AllenDang** [comment]
@gucio321 You are soooooo quick man!

**Comment by fyw2020** [comment]
@gucio321 I can't find giu.StyleColorSelectedBg, just find StyleColorTextSelectedBg, it has no effect.
go get github.com/AllenDang/giu v0.6.3-0.20221130011301-66e8a00b96ca

And also how to change selectable widget's mouse hovered bgColor?

Thank u for your help!

**Comment by fyw2020** [comment]
@gucio321 I can't find giu.StyleColorSelectedBg, just find StyleColorTextSelectedBg, it has no effect.
go get github.com/AllenDang/giu v0.6.3-0.20221130011301-66e8a00b96ca

And also how to change selectable widget's mouse hovered bgColor?

Thank u for your help!

**Comment by AllenDang** [comment]
@fyw2020 Run `imguidemo`, find `style tool` from menu, and you could easily found out which color works for what aspect.

**Comment by fyw2020** [comment]
It's global change. I have to leave this alone
