### ISSUE TITLE
docking: migration strategy

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#624]
Hi @AllenDang !
I have some toughts about migrating to cimgui-go, I'd like to discuss with you:
in my opinion, right now, master and docking are getting a diff on their content. Some bugs, has been fixed on master, but they still exists on docking. This hole is going to grow more an dmore in my opinion, so I see 2 solutions:
- stop developing docking branch and focus on cimgui-go first (as far as I can see, everything in that repo is still changing - including naming convention e.t.c.) so working on docking now is Sisyphean work.  Over that, many things (imo) to migrate to cimgui-go, could be done simply by using Regular Expressions, so we can simply write them down somewhere (e.g. in this issue) and simply use `sed` to apply them
- tag current master, drop docking, and start "live-migration" on master branch.

**Comment by AllenDang** [comment]
> stop developing docking branch and focus on cimgui-go first

Agree.

> tag current master, drop docking, and start "live-migration" on master branch.

Branching is born to situation like this, we could freeze mater branch until docking is ready and merged, you think?
 

> many things (imo) to migrate to cimgui-go, could be done simply by using Regular Expressions

Might not be that easy, but we could fix som corner cases later.

**Comment by gucio321** [comment]
sorry, I'm back :smile:

> Branching is born to situation like this, we could freeze mater branch until docking is ready and merged, you think?

Sadly, I suppose we need to start migration from scratch, since the hole between the two branches might be too big now and we can miss some stuff

> Might not be that easy, but we could fix som corner cases later.

IMO regexp is quit nice tought. I did some work [here in my repo](https://github.com/gucio321/giu/tree/migration).
This branch, could be clearly rebased onto master!
