### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by mdotv** [AllenDang/giu#625]
Hi! I have some questions, sorry if I missed something in docs and examples.
1. Is there a way to have two native windows in one program?
2. How to apply ContextMenu for the whole layout (not only for content in it)?

I want to achieve this:
![image](https://user-images.githubusercontent.com/65403437/205637437-e367f62b-51f6-4304-8b92-3035c496bd90.png)

I have done it using this code, but it only works for last layout in SplitLayout. I would like to apply it for the left layout:
```
return g.Layout{
		g.MenuBar().Layout(a.catalog.MenuBar()),
		g.SplitLayout(g.DirectionHorizontal, 340, a.catalog.Layout(), a.order.Layout()),
		g.ContextMenu().Layout(
			g.Selectable("Context menu 1").OnClick(nil),
			g.Selectable("Context menu 2").OnClick(nil),
		),
	}
```

**Comment by gucio321** [comment]
@mdotv I'm sorry, I had to miss this issue somehow...

> Is there a way to have two native windows in one program?

No, it is not possible yet

> How to apply ContextMenu for the whole layout (not only for content in it)?

you can make this a ChildWidget and apply context menu to it

**Comment by gucio321** [comment]
Closing as likely fixed. Feel free to ping me if you think it should be re-opened.
