### ISSUE TITLE
[bug]  does not contain package github.com/go-gl/gl/v3.2-core/gl

### ISSUE THREAD

**Issue by L1ghtingBolt** [AllenDang/giu#626]
### What happend?

When trying even the repo example, and trying to get dependencies, this error pops up
```
go: finding module for package github.com/go-gl/gl/v3.2-core/gl
forkerion/tasklist imports
        github.com/AllenDang/giu imports
        github.com/AllenDang/imgui-go imports
        github.com/go-gl/gl/v3.2-core/gl: module github.com/go-gl/gl@latest found (v0.0.0-20211210172815-726fda9656d6), but does not contain package github.com/go-gl/gl/v3.2-core/gl
```

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"fmt"

	g "github.com/AllenDang/giu"
)

func onClickMe() {
	fmt.Println("Hello world!")
}

func onImSoCute() {
	fmt.Println("Im sooooooo cute!!")
}

func loop() {
	g.SingleWindow().Layout(
		g.Label("Hello world from giu"),
		g.Row(
			g.Button("Click Me").OnClick(onClickMe),
			g.Button("I'm so cute").OnClick(onImSoCute),
		),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable)
	wnd.Run(loop)
}
```

</details>

### To Reproduce

1. go mod tidy
2. error appears

### Version

master

### OS

Windows 11

**Comment by gucio321** [comment]
really strange... could you run `go clean -modcache` and try again?

**Comment by gucio321** [comment]
end (if doesn't work), please ensure, your running on clean (not modified) working tree of giu repo
an next, pleas show me `go env`
I'm sure there is something wrong with your go setup, since it works on my linux machine just perfectly

**Comment by gucio321** [comment]
Since it seems to be fixed I think it could be closed. Feel free to ping me for any details!
