### ISSUE TITLE
[bug] data race on Context.isRunning

### ISSUE THREAD

**Issue by wxdyhj** [AllenDang/giu#627]
### What happend?

[whoareyou@giu-demo]$ go version
go version go1.18.6 darwin/amd64
[whoareyou@giu-demo]$ go run -race main.go
==================
WARNING: DATA RACE
Write at 0x000004763690 by goroutine 8:
  github.com/AllenDang/giu.(*MasterWindow).Run.func1()
      /Users/whoareyou/code/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:316 +0x98
  github.com/faiface/mainthread.Run.func1()
      /Users/whoareyou/code/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x39

Previous read at 0x000004763690 by goroutine 7:
  github.com/AllenDang/giu.Update()
      /Users/whoareyou/code/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Utils.go:88 +0x38
  main.main.func1()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:19 +0x2c

Goroutine 8 (running) created at:
  github.com/faiface/mainthread.Run()
      /Users/whoareyou/code/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0x15a
  github.com/AllenDang/giu.(*MasterWindow).Run()
      /Users/whoareyou/code/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:312 +0xd6
  main.newApp()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:30 +0x5c
  main.main()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:23 +0x2e

Goroutine 7 (running) created at:
  main.main()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:17 +0x29
==================
==================
WARNING: DATA RACE
Read at 0x000004763678 by goroutine 7:
  github.com/AllenDang/giu.Update()
      /Users/whoareyou/code/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Utils.go:89 +0x4d
  main.main.func1()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:19 +0x2c

Previous write at 0x000004763678 by main goroutine:
  [failed to restore the stack]

Goroutine 7 (running) created at:
  main.main()
      /Users/whoareyou/code/go/src/github.com/open-binance/giu-demo/main.go:17 +0x29
==================

### Code example

<details><summary><code>main.go</code></summary>

```golang
// put your code here!
package main

import (
	"fmt"
	"time"

	"github.com/AllenDang/giu"
)

var (
	valueInt32   int32   = 10
	valueStr     string  = "123"
	valueFloat32 float32 = 3.14
)

func main() {
	go func() {
		for {
			giu.Update()
			time.Sleep(1 * time.Second)
		}
	}()
	newApp()
	select {}
}

func newApp() {
	app := giu.NewMasterWindow("gui-demo", 360, 300, 0)
	app.SetPos(0, 30)
	app.Run(mainWindow)
}

func mainWindow() {
	giu.SingleWindowWithMenuBar().Layout(
		giu.SplitLayout(giu.DirectionHorizontal, 360, getConfig(), &giu.TabBarWidget{}),
	)
}

func getConfig() *giu.TabBarWidget {
	return giu.TabBar().TabItems(giu.TabItem("参数配置").Layout(
		giu.Column(
			giu.Row(
				giu.Label("整数: "),
				giu.InputInt(&valueInt32).Size(120),
				giu.Button("确定(Enter)").OnClick(printValueInt32),
			),
			giu.Row(
				giu.Label("字符串: "),
				giu.InputText(&valueStr).Size(120).Flags(giu.InputTextFlagsCharsNoBlank),
				giu.Button("确定(Enter)").OnClick(printValueStr),
			),
			giu.Row(
				giu.Label("浮点数: "),
				giu.InputFloat(&valueFloat32).Size(120),
				giu.Button("确定(Enter)").OnClick(printValueFloat32),
			),
		),
	))
}

func printValueInt32() {
	fmt.Println("int32", valueInt32)
}

func printValueStr() {
	fmt.Println("string", valueStr)
}

func printValueFloat32() {
	fmt.Println("flaot32", valueFloat32)
}
```

</details>

### To Reproduce

1. go mod tidy
2. go run -race main.go

### Version

(latest)

### OS

macOS

**Comment by gucio321** [comment]
@wxdyhj could you check now? #641 fixed many data races in context

**Comment by gucio321** [comment]
Closing as likely fixed. Feel free to ping me if you think it should be re-opened.
