### ISSUE TITLE
Closing the main form.

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#63]
How would one go about closing the Master window when an item is clicked in the menu?

`			g.MenuBar(
				g.Layout{
					g.Menu("File", g.Layout{
						g.MenuItem("Close", closeWindow),
						}),
				},
			),`

I love what you have so far this project and I'm currently using it to help build a gui for an Asset Management program I am building. It really is awesome.

**Comment by AllenDang** [comment]
@roborobs1023 Simply call os.Exit(0) in closeWindow callback like this.
`func closeWindow() {
  os.Exit(0)
}`

**Comment by roborobs1023** [comment]
Thank you. I actually found it last night.

**Comment by roborobs1023** [comment]
Do you currently have a way of masking an input in a text field? I'm not seeing one in the documentation. 
Using it for a login form and need to mask the password field to that the user's password is not displayed while entering.

**Comment by roborobs1023** [comment]
Found it. - I wish all of the widgets were documented. such as inputtextV I finally found it nearly by accident.

**Comment by AllenDang** [comment]
@roborobs1023 Sorry for the missing document. I'm add them one by one now. :P
