### ISSUE TITLE
[bug] empty table issue

### ISSUE THREAD

**Issue by eclipseAce** [AllenDang/giu#631]
### What happend?

I created a table without rows, but table didn't show.
I found a special if condition in the beginning of TableWidgets's Build function:
```golang
// Build implements Widget interface.
func (t *TableWidget) Build() {
	if len(t.rows) == 0 {
		return
	}
...
```
It seems tables stop rendering when no rows?
It's a mistake or by design?

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

func main() {
	wnd := g.NewMasterWindow("emptytable", 400, 200, 0)
	wnd.Run(func() {
		g.SingleWindow().Layout(
			g.Table().Size(200, 200).Columns(
				g.TableColumn("Col1"),
				g.TableColumn("Col2"),
				g.TableColumn("Col3"),
			).Rows(
				//g.TableRow(g.Label("Val1"), g.Label("Val2"), g.Label("Val3")),
			),
		)
	})
}
```

</details>

### To Reproduce

1. Run my demo
2. Table doesn't show
3. Uncomment row definition code, table shows normally

### Version

(latest)

### OS

windows 10

**Comment by AllenDang** [comment]
Its not an issue. It is designed this way.

**Comment by eclipseAce** [comment]
How can I create a table without rows

**Comment by eclipseAce** [comment]
Data list will be empty in some case

**Comment by gucio321** [comment]
> Data list will be empty in some case

hmm, in such a situation, I always show some placeholder like "no data found" or something
But personally, I believe that giu shouldn't be limited to "what I always do" :grinning:.
So, is there any other reason (like imgui's restrictions) for putting this check there?

```go
        if len(t.rows) == 0 {
		return
	}
```

if not I don't see sense for keeping this code there, because:
1. it is logical for users, that if there can be a situation, when there is no rows, they will add condition to check that anyway.
2. simplify code
3. _increase performence_ (of course It will not save 5GB of your ram, but it is always one less condition to check :smile:)

@AllenDang whats your opinion?

**Comment by eclipseAce** [comment]
I've try to add a dummy row, but it leaves a small gap under header row
![image](https://user-images.githubusercontent.com/11436358/207379792-f65bb529-8133-4599-b602-6508640b8af8.png)

**Comment by gucio321** [comment]
@eclipseAce try to push ItemSpacing (or FramePadding - not really sure) style var

**Comment by eclipseAce** [comment]
I currently use raw api to create table
```golang
wnd := g.NewMasterWindow("emptytable", 400, 200, 0)
	wnd.Run(func() {
		data := []string{}
		g.SingleWindow().Layout(
			g.Custom(func() {
				imgui.BeginTable("table", 3, imgui.TableFlags_Borders|imgui.TableFlags_SizingStretchProp, imgui.Vec2{X: 200, Y: 200}, 200)
				imgui.TableSetupColumn("Col1", imgui.TableColumnFlags_None, 20, 0)
				imgui.TableSetupColumn("Col2", imgui.TableColumnFlags_None, 20, 0)
				imgui.TableSetupColumn("Col3", imgui.TableColumnFlags_None, 20, 0)
				imgui.TableHeadersRow()

				for _, v := range data {
					imgui.TableNextRow(imgui.TableRowFlags_None, 32)
					imgui.TableSetColumnIndex(0)
					imgui.Text(v)
					imgui.TableSetColumnIndex(1)
					imgui.Text(v)
					imgui.TableSetColumnIndex(2)
					imgui.Text(v)
				}
				imgui.EndTable()
			}),
		)
	})
```

**Comment by eclipseAce** [comment]
>  I always show some placeholder like "no data found" or something

I think so, but is there some options like rowspan, so I can display "no data found" in whole row instead of one cell?
![image](https://user-images.githubusercontent.com/11436358/207385722-57c51db3-bf3d-4374-8e9d-0901e607cc13.png)
```golang
g.SingleWindow().Layout(
	g.Table().Columns(
		g.TableColumn("Col1"),
		g.TableColumn("Col2"),
		g.TableColumn("Col3"),
	).Rows(
		g.TableRow(g.Label(""), g.Label("No data"), g.Label("")),
	),
)
```

**Comment by gucio321** [comment]
> > I always show some placeholder like "no data found" or something
> 
> I think so, but is there some options like rowspan, so I can display "no data found" in whole row instead of one cell? ![image](https://user-images.githubusercontent.com/11436358/207385722-57c51db3-bf3d-4374-8e9d-0901e607cc13.png)
> 
> ```go
> g.SingleWindow().Layout(
> 	g.Table().Columns(
> 		g.TableColumn("Col1"),
> 		g.TableColumn("Col2"),
> 		g.TableColumn("Col3"),
> 	).Rows(
> 		g.TableRow(g.Label(""), g.Label("No data"), g.Label("")),
> 	),
> )
> ```

not really sure, but what will happen, if you put only one argmuent in TableRow()?

**Comment by eclipseAce** [comment]
@gucio321 
![image](https://user-images.githubusercontent.com/11436358/207483719-a734f134-297c-42d3-9618-f4b4d0db4362.png)

**Comment by gucio321** [comment]
ok, let me open a PR
