### ISSUE TITLE
Does giu support system tray?

### ISSUE THREAD

**Issue by Esword618** [AllenDang/giu#633]
Does giu support system tray?

**Comment by gucio321** [comment]
@Esword618 what do you mean by "system tray support"?

**Comment by fniu** [comment]
I guess @Esword618 refers to something like 
https://github.com/fyne-io/systray

**Comment by Esword618** [comment]
Yes, that's what @fniu  said.

**Comment by gucio321** [comment]
So, the current situation like as follows:
- giu does not implement all the features from the repository mentioned by @fniu  
- giu only allows to set window icon
- in case of systray integration: it may be possible if only there aren't any C conflicts

**Comment by Esword618** [comment]
okay, thank you.
