### ISSUE TITLE
Is it possible to show non english characters?

### ISSUE THREAD

**Issue by Shafin098** [AllenDang/giu#635]
When I type something in *CodeEditorWidget* that is not english characters I get ??? instead of actual characters

**Comment by gucio321** [comment]
Do you have valid font added?

**Comment by Shafin098** [comment]
Yes i've tried multiple, still showing ???

**Comment by Shafin098** [comment]
I am trying to show Bengali text

**Comment by AllenDang** [comment]
@Shafin098 If the font for your language is not supported, you could add it to `https://github.com/AllenDang/giu/blob/master/FontAtlasProsessor.go` and raise a PR.

**Comment by gucio321** [comment]
@Shafin098 also, please check if you can display your text with plain labelWidget? If you succeed, the text is visible, but code editor still shows??? Let us know since it might be a bug in font atlas, 
Else, (if the label is??? Too), you are probably doing something wrong when adding font

**Comment by Shafin098** [comment]
Some more update

Bottom block of code didn't work.
```golang
bnFont := g.AddFont("kalpurush", 14)
if bnFont != nil {
	g.Style().SetFont(bnFont)
}
```

But this code is atleast not showing ??? and i am getting some of the characters right. But still not showing correctly.
```golang
g.SetDefaultFont("kalpurush", 14)
```

**Comment by Shafin098** [comment]
CodeEditorWidget and plain label widget both are showing fonts now but seems like grapheme cluster rendering is not working properly. 

This is how it should look like
<img width="27" alt="correct" src="https://user-images.githubusercontent.com/29890859/209947157-ae5c975f-e91c-485d-8356-f5253ecd85da.png">

This is what I am seeing
<img width="33" alt="wrong" src="https://user-images.githubusercontent.com/29890859/209947192-d32482ea-1659-400a-ad13-bab5a8909346.png">

**Comment by gucio321** [comment]
@Shafin098 In my opinion you need to adjust font size a bit

**Comment by gucio321** [comment]
@Shafin098 any updates?

**Comment by gucio321** [comment]
Closing as likely fixed. Feel free to ping me if you think it should be re-opened.
