### ISSUE TITLE
can't find a close button for Window

### ISSUE THREAD

**Issue by cwing2019** [AllenDang/giu#636]
After using g.MasterWindowFlagsFrameless  to hidden the OS style titlebar.
We create a window like this:
```go
g.Window("window").Flags(g.WindowFlagsMenuBar|g.WindowFlagsNoCollapse|g.FocusedFlagsChildWindows).Layout....
```

it shows a window with menubar without inner titlebar with close button.
is there any style can show a close button on the right corner?

**Comment by gucio321** [comment]
@cwing2019 `MasterWIndowFlagsFrameless` is supposed to remove window decoration with its buttons.
