### ISSUE TITLE
Proper way to use Window Padding

### ISSUE THREAD

**Issue by Vendicated** [AllenDang/giu#638]
Hello! I'm trying to add Window Padding to my window, but it also affects tooltips, messageboxes and more

Checking c++ imgui examples, you usually would (in pseudocode)
```
imgui.pushPadding()
imgui.begin()
imgui.popPadding()
imgui.someElement()
```
but this doesn't seem possible to do in giu, since begin is called by window.Layout which also builds the entire layout
https://github.com/AllenDang/giu/blob/da051513855e9e2628cc62fbb19c7ac2b1eec2f5/Window.go#L140-L146

My current code is
```go
g.PushWindowPadding(48, 48)
g.SingleWindow().Layout(...)
g.PopStyle()
```
but this also affects children as mentioned above

What's the proper way to use WindowPadding that solves this issue? I want the padding only on the root window

**Comment by AllenDang** [comment]
You could create window using imgui.Begin(...) in a giu.Custom(func() {})

**Comment by gucio321** [comment]
yes, in this case you need to do just like in c++ but using imgui-go functions
