### ISSUE TITLE
void* memset exceeds maximum object size

### ISSUE THREAD

**Issue by nullptr-ref** [AllenDang/giu#642]
### What happend?

Error/Warning:

```# github.com/AllenDang/imgui-go
imgui_draw.cpp: In function 'void ImFontAtlasBuildPackCustomRects(ImFontAtlas*, void*)':
imgui_draw.cpp:2630:11: warning: 'void* memset(void*, int, size_t)' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
 2630 |     memset(pack_rects.Data, 0, (size_t)pack_rects.size_in_bytes());
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is present on every example and/or program built with the library. 

OS: Windows 10 
Go ENV:

```set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ArtoS\AppData\Local\go-build
set GOENV=C:\Users\ArtoS\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ArtoS\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ArtoS\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Code\apacheLogAnalyzer\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ArtoS\AppData\Local\Temp\go-build2255402139=/tmp/go-build -gno-record-gcc-switches
```

It looks like the lib is using way too much memory for some reason, no matter what controls are present. 

Let me know if you need any further information. 

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"fmt"

	g "github.com/AllenDang/giu"
)

func loop() {
	g.SingleWindow().Layout(
		g.Button("Test Window").OnClick(func() {
			fmt.Print("test window")
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Test", 1920, 1080, g.MasterWindowFlagsNotResizable)
	wnd.Run(loop)
}

```

</details>

### To Reproduce

1. Run my demo
2. will see the warning

### Version

master

### OS

Windows 10

**Comment by gucio321** [comment]
Yeah, I am aware that it appears on some platforms (including all ubuntu workers hosted by GH actions.
However, I am unable to reproduce this behaviour on my own machine :smile:.

Anyway, I suppose this bug is rather related to imgui-go than giu. We should wait till cimgui-go migration. Since messing with imgui-go does not make sense now, when cimgui-go comes.

**Comment by vbmark** [comment]
What did you use to install GCC?

**Comment by nullptr-ref** [comment]
> 

```Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev6, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Rev6, Built by MSYS2 project)```

**Comment by vbmark** [comment]
This line on my system is different than yours:
`COLLECT_LTO_WRAPPER=C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe`

The site says, "If you are unsure, go with UCRT64."  So maybe give that a try.
[https://www.msys2.org/docs/environments/](https://www.msys2.org/docs/environments/)

**Comment by nullptr-ref** [comment]
This is a default installation. I don't believe special workarounds should be made to make it compatible. 

Anyway, we'll have to wait until the port to see if that resolves the issue.

**Comment by vbmark** [comment]
I'm not sure what you mean by default installation.  

Step 6 says to install this `mingw-w64-ucrt-x86_64-gcc`.
https://www.msys2.org/

You didn't select what the site recommended.

**Comment by Locter9001** [comment]
> Yeah, I am aware that it appears on some platforms (including all ubuntu workers hosted by GH actions. However, I am unable to reproduce this behaviour on my own machine 😄.
> 
> Anyway, I suppose this bug is rather related to imgui-go than giu. We should wait till cimgui-go migration. Since messing with imgui-go does not make sense now, when cimgui-go comes.

Can you please give me an overview of your plans and strategies regarding cimgui-go? Specifically, how will it be integrated into our current project, and what upgrades or changes can we expect in the future? Will this integration affect any of our previous projects or legacy code?

**Comment by gucio321** [comment]
Cimgui should be just a drop-in replacement for currently used o
Imgui-go, so i suppose nothing in giu api will change

**Comment by Locter9001** [comment]
> Cimgui should be just a drop-in replacement for currently used o Imgui-go, so i suppose nothing in giu api will change

cool

**Comment by gucio321** [comment]
Update here:
As far as I know this error is not present on [cimgui-go](https://github.com/allendang/cimgui-go) so our migration in #624 should fix this issue.
