### ISSUE TITLE
[Feature Request] Does InputTextMultiline support scrollX? 

### ISSUE THREAD

**Issue by 93Alliance** [AllenDang/giu#645]
### Your request

How does InputTextMultiline set the horizontal scroll bar?

**Comment by gucio321** [comment]
@93Alliance what do you mean by "Does it support scrollx"? could you please provide some context and code you want to run?

**Comment by gucio321** [comment]
@93Alliance ?

**Comment by 93Alliance** [comment]
I don't use it anymore, thank you for your reply, I will close this issue.
