### ISSUE TITLE
[Feature Request] Allow adding tabs dynamically

### ISSUE THREAD

**Issue by enty8080** [AllenDang/giu#659]
### Your request

In the demo provided, it is possible to add tab to tabs (Examples -> Tabs). But demo is written in C++ and I actually can't understand how to implement this functionality using Go.

P.S. Documentations does not contain any useful information unfortunately.

**Comment by gucio321** [comment]
@enty8080 did you find solution?

**Comment by enty8080** [comment]
@gucio321 Yes. Just create an array with tabs and append to it every time you want a new tab. Do not forget to unpack this array - `TabBar().TabItems(yourArray...)`
