### ISSUE TITLE
Temporarily unmask password field

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#67]
I have setup a login window which uses the InputText field with flag InputTextFlagsPassword. My question is how would i set this so I could temporarily allow the user to see the password? Such as clicking on a show password label beside the field. below is a snippet of the current window. 

g.Line(
	 g.Dummy(115,0),
	 g.Label("Password: "),
	 g.InputTextV("##password", 200, &u.Admin.Password, g.InputTextFlagsPassword, nil, nil),
	 g.Dummy(5,0),
	 g.Selectable("Show Password", nil),
),

**Comment by AllenDang** [comment]
@roborobs1023 Use an variable to control the InputTextFlags like below

```go
  inputFieldFlags := g.InputTextFlagsPassword
  ...
  g.InputTextV("##password", 200, &u.Admin.Password, inputFieldFlags, nil, nil)
```

And change the flags to what ever you need in some other function and call g.Update() to refresh UI.

**Comment by roborobs1023** [comment]
Yea that would work. thanks.
