### ISSUE TITLE
iskeypressed not working

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#68]
Working with a submission form and I have the following code. What I'm trying to make work is when you fill in the form and then hit enter the same function is performed as when you click the button at the bottom of the form. I'm not sure if I'm entering the wrong integer for the key or what exactly is happening... I used the IsItemHovered function on a selectable widget right after this in the same format, for making the password visible and the below passvisible variable sets it back to being masked. Any Ideas?

				giu.InputTextV("##password", 120, &cred.password, passwordflag, nil, func() {
					passvisible = false
					giu.Update()
				}),
				giu.Custom(func() {
					if giu.IsKeyPressed(15) {	
					        fmt.Println("Enter Pressed")
						subPressed()
					}
				}),

**Comment by AllenDang** [comment]
@roborobs1023 The key code of Enter is 257. You could get the key code of any key by running imguidemo.go, in the "Inpouts, Navigation & Focus" -> "Keyboard, Mouse & Navigation State".

**Comment by roborobs1023** [comment]
Thank you. That is a huge help.
