### ISSUE TITLE
Missing `StyleVarID`s

### ISSUE THREAD

**Issue by damntourists** [AllenDang/giu#688]
### What happend?

I'm currently implementing themes in a project using themes exported in TOML from https://github.com/Patitotective/ImThemes/ and noticed that we seem to be lacking a way to set the following styles:
```
windowMenuButtonPosition
columnsMinSpacing
colorButtonPosition
tabBorderSize
tabMinWidthForCloseButton
```

I wasn't able to find these specifically in any of the code, so I'm unsure if they were skipped on purpose or perhaps there's another way to set these?

Thanks for your time! :) 

### Code example

N/A

### To Reproduce

N/A

### Version

master

### OS

Ubuntu

**Comment by gucio321** [comment]
You can check if these styleVarIds are present in imgui-go library but (as I'm pretty sure they aren't) i suppose you need to wait for #628

**Comment by damntourists** [comment]
Closing this out since it's no longer relevant.
