### ISSUE TITLE
Multiple Window widgets with SplitLayout

### ISSUE THREAD

**Issue by kettek** [AllenDang/giu#69]
I'm attempting to use multiple WindowV instances for a game editor (a window for each open map, as well as other data types) and ran into the fact that SplitLayout does not work with more than one Window instance.

This is, afaik, due to:

https://github.com/AllenDang/giu/blob/321faa16e79bc7def64dc14488be93748dc33506/Window.go#L62-L68

which clears the Context states, in which the SplitLayout data is stored:

https://github.com/AllenDang/giu/blob/321faa16e79bc7def64dc14488be93748dc33506/SplitLayout.go#L81-L86

Is it necessary to invalidate all state when a Window widget is used? Should context be per Window widget? Would a Window Widget flag that specifies not to invalidate fix the problem?

**Comment by AllenDang** [comment]
@kettek I think I know what's going on here. Let me take a look.

**Comment by AllenDang** [comment]
@kettek The solution is more complicate then I thought, seems the content of inactive window is not refreshed, I need more time to find out what is happening. Sorry for the delay. :P

**Comment by kettek** [comment]
Any progress on this?

**Comment by AllenDang** [comment]
@kettek I'm working on it now, just few more days.

**Comment by AllenDang** [comment]
@kettek It is fixed now. Please have a try.

**Comment by kettek** [comment]
Unfortunately something else must have changed in giu's codebase since the last version I used... I'm getting constant freezing, likely due to using `g.NewTextureFromRgba` -- basically I'm loading 30+ images and using `go func() { ... g.NewTextureFromRgba(rgba) }`. And, for some reason, attempting to use any sync.Mutex locks or chans causes the goroutines to simply stop executing. This doesn't make sense to me, as using channels and/or mutexes should not cause a goroutine to completely stop.

This is rather frustrating but I'll keep trying to make it workable again...

**Comment by kettek** [comment]
I've adjusted the code and have successfully used SplitLayout on multiple Windows.
