### ISSUE TITLE
[question] Capture mouse wheel event 

### ISSUE THREAD

**Issue by mars315** [AllenDang/giu#697]
hi
I want to capture the middle mouse button scrolling event on a window,  increment or decrement/increment a number depending upon direction of wheel movement. what can i do?  thx.

**Comment by gucio321** [comment]
hmm, I can't see any way in nor giu or imgui-go, and since imgui-go is deprecated already, we can't do anything right now...
Wait for #628

**Comment by mars315** [comment]
thx
