### ISSUE TITLE
How to add tooltip to widget?

### ISSUE THREAD

**Issue by mikigal** [AllenDang/giu#698]
Hello!
I want to add tooltip to one of widgets (message which is displayed on hover).
I found `giu.Tooltip` widget, but I have no idea how can I bind it to checkbox.

How can I do it?

**Comment by gucio321** [comment]
just put tooltip after your widget.
```go
package main

import (
	"github.com/AllenDang/giu"
	g "github.com/AllenDang/giu"
)

var content bool

func loop() {
	g.SingleWindow().Layout(
		giu.Checkbox("I'm a checkbox", &content),
		giu.Tooltip("I'm a tooltip!"),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by mikigal** [comment]
Oh, I tried only adding it before checkbox
Thanks for fast response!

![Zrzut ekranu 2023-09-21 214612](https://github.com/AllenDang/giu/assets/10632503/c18401fb-1d56-4652-a452-cc54294770e2)

**Comment by gucio321** [comment]
No problem!
issue speedrun :smile:
