### ISSUE TITLE
Underlying library is called "Dear ImGui"

### ISSUE THREAD

**Issue by ocornut** [AllenDang/giu#7]
Hello,
Could you alter textual mentions of "imgui" into either "dear imgui" or "Dear ImGui" ? (both are interchangeable). 
Thaank you,
Regards!

**Comment by AllenDang** [comment]
@ocornut Sure thing!

**Comment by ocornut** [comment]
Thank you! The repository title still just says "imgui" there and there's another reference in the readme.

**Comment by AllenDang** [comment]
@ocornut Sorry to miss them. I updated again, should be all of them. :P

**Comment by AllenDang** [comment]
@ocornut BTW, I'm so glad that you seeing my project!
