### ISSUE TITLE
is it possible to add Push/PopClipRect?

### ISSUE THREAD

**Issue by ogau** [AllenDang/giu#70]
Here is an example "canvas" from dear imgui demo, that uses the function Push/PopClipRect.
Also i have implemented io.GetDeltaTime()

code: https://play.golang.org/p/QeyEpoz3Db3
![изображение](https://user-images.githubusercontent.com/25056868/93060777-09e3cd80-f68c-11ea-90ce-c4b0844daa7a.png)

**Comment by AllenDang** [comment]
@ogau Can you create a PR on this?

**Comment by ogau** [comment]
Thanks for your work!
