### ISSUE TITLE
[bug] Image widget click detection

### ISSUE THREAD

**Issue by deepin-pointer** [AllenDang/giu#702]
### What happend?

Why are we adding cursorPos to mousePos here?
https://github.com/AllenDang/giu/blob/fcf5e15ecf9693c3ec08456019d8121629b8c6cd/ImageWidgets.go#L97C14-L97C14

I try to click the top left corner of the image, and mousePos==cursorPos before adding extra cursor Pos
![image](https://github.com/AllenDang/giu/assets/27391161/bbf41fcf-ffae-4684-a779-df2757319a04)

### Code example

See description

### To Reproduce

See description

### Version

v0.6.1

### OS

windows11

**Comment by gucio321** [comment]
yeah, something is broken there. Let me check
