### ISSUE TITLE
[Feature Request] Support Begin End style API

### ISSUE THREAD

**Issue by 0-issue** [AllenDang/giu#707]
### Related problem

Deeply nested structures/indents is an anti-pattern in Go:

```go
func loop() {
	g.SingleWindow().Layout(
		g.SplitLayout(g.DirectionHorizontal, &sashPos1,
			g.Layout{
				g.Label("Left panel"),
				g.Row(g.Button("Button1"), g.Button("Button2")),
			},
			g.SplitLayout(g.DirectionVertical, &sashPos2,
				g.Layout{},
				g.SplitLayout(g.DirectionHorizontal, &sashPos3,
					g.Layout{},
					g.SplitLayout(g.DirectionVertical, &sashPos4,
						g.Layout{},
						g.Layout{},
					),
				),
			),
		),
	)
}
```

### Your request

Support Being, End style api like of [imguiplot](https://github.com/epezent/implot):
```go
int   bar_data[11] = ...;
float x_data[1000] = ...;
float y_data[1000] = ...;

ImGui::Begin("My Window");
if (ImPlot::BeginPlot("My Plot")) {
    ImPlot::PlotBars("My Bar Plot", bar_data, 11);
    ImPlot::PlotLine("My Line Plot", x_data, y_data, 1000);
    ...
    ImPlot::EndPlot();
}
ImGui::End();
```
src: https://github.com/epezent/implot#usage

**Comment by gucio321** [comment]
@amanvm you can always use style api from imgui (it is called PushStyle/PopStyle)

**Comment by AllenDang** [comment]
The reason why I use nested structures instead begin/end is I don't need to remember every pair and avoid crash if I forget a proper end somewhere.

**Comment by AllenDang** [comment]
That's not only pair check, also involve some tricky and inconsistent, for example, some `end` should called when `begin` return's true, some `end` need to be called no matter what, in my past experience, this part drives me crazy.

**Comment by gucio321** [comment]
I think we can close it for now. If you nneed imgui-styled api just use it ;-) (you can use cimgui-go api in your giu app)
