### ISSUE TITLE
Set default focus for textbox. 

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#71]
Trying to figure out what additional code I need in order for the first text field to automatically get focus on the window load.  below is an example of what I currently have but I'm not getting the desired result. 

			g.WindowV("Login", &c.Loginwin, g.WindowFlagsNoResize|g.WindowFlagsNoCollapse|g.WindowFlagsNoMove, (mw/2)-70, (mh/2)-90, 140, 180, g.Layout{
				g.Label("Username"),
				g.InputText("##username", 120, &cred.username),
				g.Custom(func(){
					g.SetItemDefaultFocus()
				}),

**Comment by AllenDang** [comment]
@roborobs1023 Use g.SetKeyboardFocusHere() instead of SetItemDefaultFocus()

**Comment by roborobs1023** [comment]
I just tried this and for some reason two things are happening: #1. I have to insert the g.Custom widget before my desired textbox and #2 when I do, it disallows tabbing to the next textbox and clicking the buttons. Any idea what could be causing this?

**Comment by roborobs1023** [comment]
Got it working using the g.IsWindowAppearing() function.
