### ISSUE TITLE
ImageWithRgba displayed image does not change when the supplied image.Image parameter changes

### ISSUE THREAD

**Issue by araoko** [AllenDang/giu#710]
unlike the **ImageWithFile** method, when **ImageWithRgba** is called with a different **image.Image** parameter does not change the image displayed
if the parameter changes when in the event loop, the image is not replaced. if the size is changed, the old image will just be resized but it will not be replaced by the new image.
**ImageWithFile** on the other hand appears to be re-evaluated every time in the event loop as the image changes

**Comment by gucio321** [comment]
@araoko does this fix the issue? https://github.com/AllenDang/giu/pull/713

**Comment by araoko** [comment]
> @araoko does this fix the issue? #713

I dont have the updates. I did a go get -u ./... and still have the old code

**Comment by gucio321** [comment]
Go get -u giupath@latestcommithash
