### ISSUE TITLE
[bug] CellPadding stylevar missing

### ISSUE THREAD

**Issue by damntourists** [AllenDang/giu#721]
### What happend?

I've been working on a theme loader for the themes.toml defined at https://github.com/Patitotective/ImThemes/ which has been working for the most part, however I'm having a bit of trouble tracking down the CellPadding style var.  It's referenced in some imgui issues like found here https://github.com/ocornut/imgui/issues/5615 `imgui.push_style_var_vec2(imgui.Style_Var.CellPadding, {15, 15})` however I'm not finding any `Cell*` or similar definitions within the cimgui or giu projects. I can skip assigning this one for now, but it would be nice to have them all present eventually. 

### Code example

<details><summary><code>main.go</code></summary>

```golang
// put your code here!
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

master

### OS

ubuntu

**Comment by gucio321** [comment]
fix is comming :smile:

**Comment by damntourists** [comment]
Thanks (yet again) @gucio321!
