### ISSUE TITLE
[bug] More style vars missing

### ISSUE THREAD

**Issue by damntourists** [AllenDang/giu#725]
### What happend?

Hi there, 

Similar to my last bug report https://github.com/AllenDang/giu/issues/721 it appears I'm also missing the following style vars (please correct me if I'm wrong!):

```
ColumnsMinSpacing
TabBorderSize
TabMinWidthForCloseButton
```

Could we get those added as well? :D 

Do you think theming using ImThemes would be useful on its own as an addon for giu? I can create a repository for it separate from the other work I'm doing with giu.  

### Code example

<details><summary><code>main.go</code></summary>

```golang
// put your code here!
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

master

### OS

ubuntu

**Comment by gucio321** [comment]
In reference to https://github.com/AllenDang/cimgui-go/blob/main/cimgui_enums.go
I found only this:
```go
        StyleVarTabBarBorderSize = 23
```
