### ISSUE TITLE
Align ext to the right ?

### ISSUE THREAD

**Issue by Koumbaya** [AllenDang/giu#73]
Hi, I'm still learning the library (very impressed btw !). Is there a way to justify the text to the right ?
If there is I'll contribute an example.
Thanks

**Comment by AllenDang** [comment]
@Koumbaya There is no alignment setting for label. But you could use following approach:
┌──────┐                          ┌─────┐
 │       Button       │─────────Dummy──────────▶│Label│
└──────┘                          └─────┘

Set the width of Dummy width to -100, which means the "rest of entire row - 100px". 

```go
g.Layout{
  g.Line(
    g.Button("Button", nil),
    g.Dummy(-100, 0),
    g.Label("Label"),
  ),
}
```

**Comment by Koumbaya** [comment]
Nice, thanks ! It takes off the last 2 chars of my string, but if I put -110 it works perfectly.
