### ISSUE TITLE
[Feature Request] ImNodes?

### ISSUE THREAD

**Issue by damntourists** [AllenDang/giu#730]
### Related problem

Hi there! This is a feature that I'm pretty interested in. Just curious if there's a plan for when this might be available?
https://github.com/AllenDang/giu/blob/master/MasterWindow.go#L77

I've looked around the repository and I see that the create context is commented out, but there are areas where imnodes seems to be exported. 
https://github.com/AllenDang/cimgui-go/blob/f9856eb4a9a725c37e34b415d3eabc00e90276fa/cmd/codegen/gencpp.go#L17

And sources seem to be in the repo..
https://github.com/AllenDang/cimgui-go/tree/main/cimgui/imnodes

If not in giu, is it at least in a functional state in cimgui?

### Your request

-

**Comment by gucio321** [comment]
We need to fix cimgui-go so that it generates imnodes binding correctly. At this point, it unfortunately doesn't generate ImNodesContext type (it seems to be essential here...)
On my fork, on the branch called `callbacks` I'm working on this feature. :smile:

**Comment by damntourists** [comment]
oh gotcha! i'll just wait then! i appreciate all of your efforts!

**Comment by gucio321** [comment]
@damntourists  could you check if it works for you on #733
