### ISSUE TITLE
How do i make InputTextMultiline wrapped

### ISSUE THREAD

**Issue by JunkMeal** [AllenDang/giu#734]
I want to make the text of 
```go
g.InputTextMultiline(&response).Size(g.Auto, g.Auto).Flags(g.InputTextFlagsReadOnly)
```
wrapped?
I know there is .Wrapped(true) on labels, but not here?

**Comment by AllenDang** [comment]
imgui doesn't provide wrap for InputTextMultiline, so it doesn't have it so far

**Comment by gucio321** [comment]
@JunkMeal I'm sorry, I had to miss this issue somehow.

In the black hole of this project there was a document about this:
https://github.com/AllenDang/giu/discussions/563 -> https://github.com/AllenDang/giu/issues/434

Need to link it somewhere, maybe on wiki.
