### ISSUE TITLE
How to disable widget

### ISSUE THREAD

**Issue by mikigal** [AllenDang/giu#744]
### Related problem

Hi,
I want to disable some widgets (e. g. combo and checkbox) in the same way I as can do it with button 
```golang 
g.Button("Start").OnClick(handleButton).Size(360, 30).Disabled(true)
```

How can I achieve it?

### Your request

Implement Disabled() function into other widgets same as for button

**Comment by gucio321** [comment]
Check Push/PopDisabled

**Comment by mikigal** [comment]
Can you provide more details? I didn't find any method for disabling widgets, most are related to colors/fonts/styles

**Comment by gucio321** [comment]
It's in cimgui (begindisabled), ill provide more details tomorrow
