### ISSUE TITLE
[bug?] Segmentation violation at NewMasterWindow()

### ISSUE THREAD

**Issue by ideasmatter** [AllenDang/giu#757]
### What happend?

I tried this interesting Imgui framework, which mostly works great on my MacOS, and Linux Mint 21.3, nice work! Recently it tried on a new Debian 12 workstation but failed with segmentation violation errors.

The error seems panics at the `NewMasterWindow` initialization, something like:
```
./helloworld
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54513c]

...giu.NewMasterWindow({0xb91db1, 0xb}, 0x190, 0xc8, 0xe3c548?)
...giu/MasterWindow.go:91 +0x1eb
main.main()
...examples/helloworld/helloworld.go:17 +0x2b
...
```
I'm not sure if it is a bug or not, as it happens on Debian 12 only. What might be the reason that I can look into? Thanks.

### Code example

I used the code in the examples directory, e.g. helloworld.

### To Reproduce

Run any example, which calls `NewMasterWindow()`

### Version

master

### OS

Debian 12

**Comment by gucio321** [comment]
Can I see more the exact commit and the full panic pls.
MasterWindow.go:91 is `        Context = CreateContext(backend)` so this can't panic about nil so its either not `master` or its not a full panic

**Comment by gucio321** [comment]
I close this for now. Let me know if you still need help.
