### ISSUE TITLE
[bug] InputMultilineWidget doesnt make new line with Enter or Crtl Enter and Backspace key doesnt work

### ISSUE THREAD

**Issue by ismyhc** [AllenDang/giu#776]
### What happend?

Im simply trying to use InputMultilineWidget for a message input box. When hitting enter or Crtl+Enter (when setting the flag) it doesnt create a new line.

Also, backspace key does not delete characters.

Its also worth noting this doesnt work in the examples either.

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var input string

func loop() {
	g.SingleWindow().Layout(
		g.InputTextMultiline(&input).OnChange(func() {
			println("input changed")
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Huge list demo", 800, 600, 0)
	wnd.Run(loop)
}
```

</details>

### To Reproduce

1. Run my demo
2. Trying entering text and then pressing enter for new line. Also try deleting text with backspace

### Version

master

### OS

Ubuntu 23.10

**Comment by ismyhc** [comment]
I guess this is related to #754

Is there an easy workaround for this yet?

**Comment by gucio321** [comment]
Unfortunately im not aware of any workaround... In going to fix this bug in the future...
For now id suggest using v0.7

**Comment by gucio321** [comment]
Closing as duplicate
