### ISSUE TITLE
Porting a dear imgui extension

### ISSUE THREAD

**Issue by DaBisounours** [AllenDang/giu#78]
Hi, first and foremost thank you for this cool library 👍 

Not sure if this is the right place to discuss the matter,

I'm interested in implementing a node editor within this library and found extensions to the original dear imgui such as [Nelarius/imnodes](https://github.com/Nelarius/imnodes). I would love to try porting this extension for my use case (audio graphs) but don't really know where I should start from. I have a brief experience with both Go and C++ but am no expert at all, and I discovered dear imgui and gui quite recently, so maybe it is out of my reach too.

If someone else is interested or could point me in the right direction, would be greatly appreciated.

Thanks 💯

**Comment by AllenDang** [comment]
@DaBisounours Thanks to use my lib! :P
You could refer following files which port ColorfulTextEditor:

This is the original extension written by C++
imgui/TextEditor.h
imgui/TextEditor.cpp

This is wrapper which provides C interface to access C++ methods
imgui/TextEditorWrapper.h
imgui/TextEditorWrapper.cpp

This is the go code to access C interface
imgui/TextEditor.go

**Comment by DaBisounours** [comment]
> @DaBisounours Thanks to use my lib! :P
> You could refer following files which port ColorfulTextEditor:
> 
> This is the original extension written by C++
> imgui/TextEditor.h
> imgui/TextEditor.cpp
> 
> This is wrapper which provides C interface to access C++ methods
> imgui/TextEditorWrapper.h
> imgui/TextEditorWrapper.cpp
> 
> This is the go code to access C interface
> imgui/TextEditor.go

Thank you for the guidance, I'll look that up and get back to this thread if I run into issues 👍
