### ISSUE TITLE
g.Label("very long ........ text")  is not shown completely 

### ISSUE THREAD

**Issue by francmarx** [AllenDang/giu#781]
### What happend?

if you put some very long text string into g.Label(), string is not shown completely, only the first 3000 chars

### Code example

simply try this:

```golang
g.Label(strings.Repeat("testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\n", 40)),
```

### Version

master

### OS

linux

**Comment by AllenDang** [comment]
The limitation comes from upstream imgui.

**Comment by francmarx** [comment]
In the earlier versions (imgui-go), labels with strings >3000 were possible, was anything changed in the upstream imgui?

**Comment by gucio321** [comment]
strange, something with imgui has to be broken... I'll check this when my local cimgui compiles :smile:

**Comment by gucio321** [comment]
in cimgui that seems to work...
![image](https://github.com/AllenDang/giu/assets/73652197/7bbb9120-5e0c-4bc5-a705-b72217ece148)

I'll check in giu as I compile it

**Comment by gucio321** [comment]
in giu it works as well
![image](https://github.com/AllenDang/giu/assets/73652197/31acb91c-e6ed-4550-8090-739645c7a3ed)
@francmarx did you use `Label(...).Wrapped(true)`?

**Comment by francmarx** [comment]
@AllenDang no, I don't use Wrapped(true). 

try much more then 3000 characters:

```
g.Label(strings.Repeat("testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\n", 50))
```
gives left side, but should look like right side:

![image](https://github.com/AllenDang/giu/assets/5364683/3b6ace9c-2605-4e62-b29e-904329d6b317)

**Comment by gucio321** [comment]
I see, could you check if it also happens in C++ imgui?

**Comment by gucio321** [comment]
It happens to cimgui-go too

**Comment by gucio321** [comment]
this seems to be something in Dear ImGui
```cpp
        ImGui::SetNextWindowSize(ImVec2{600,600});
        ImGui::Begin("Window");
        if (ImGui::Button("Add")) {
                j++;
        }
        ImGui::PushTextWrapPos();
        ImGui::Text(std::string(j*100, 'x').c_str());
        ImGui::End();
```

this acts the same

let me ping @ocornut at this point.
_let us know if we should open an issue in imgui repo_

**Comment by ocornut** [comment]
`TextUnformatted()` doesn't have a limitation, while `Text()` does.
I don't know how Go works and why the function is called "Label" but if you can detect that there's no formatting ongoing (single param) you could call TextUnformatted() instead of Text().

**Comment by gucio321** [comment]
ok I see:
```go
// raw text without formatting. Roughly equivalent to Text("TextUnformattedV", text) but: A) doesn't require null terminated string if '
```

**Comment by francmarx** [comment]
@ocornut 
TextWidget.go has always used imgui.Text(), with earlier versions of imgui it was possible to use very long texts without any problems. Has anything significant changed in recent versions of imgui.Text() in imgui?

**Comment by gucio321** [comment]
@francmarx it works now

**Comment by gucio321** [comment]
I think that
1. we're using docking branch
2. previous versions of giu were on imgui-go (which was on 1.86) and now we're using cimgui-go with upstream so 1.90.4+

something could have chaged

**Comment by ocornut** [comment]
I don’t think it has changed, no.
Tho the underlying tempbuffer system now technically allowing resizing so its possible to “fix” it with Text() function but i am not sure it is a great idea to encourage large formattiings.
