### ISSUE TITLE
[bug] g.Auto doesn't take tab bar height into account

### ISSUE THREAD

**Issue by samuelchristlie** [AllenDang/giu#802]
### What happend?

I'm following the recommendation from https://github.com/AllenDang/giu/issues/177 to create a spacer, but used `g.Auto` instead since it should automatically fill the space. What I got is this:

![image](https://github.com/AllenDang/giu/assets/127090887/b27619e1-6910-4e01-be70-c92792c8a9c6)
![image](https://github.com/AllenDang/giu/assets/127090887/cee3ed6b-6ec4-446f-b7a7-80a36fb73667)

What I think is happening is that it doesn't take the height of the tab bar into account.

### Code example

```
return g.TabBar().TabItems(
		g.TabItem("Edit").Layout(
			g.Column(
		                g.Row(g.Label("Name"), g.InputText(&name)),
		                g.Row(g.Label("Address"), g.InputTextMultiline(&address)),
		                g.Dummy(g.Auto, g.Auto),
		                g.Button("Submit"),
	                )
		),
		g.TabItem("New"),
	)

```

### To Reproduce

1. Run the code
2. `g.Auto` exceeds the height

### Version

master

### OS

Linux Mint 21.3 x86_64

**Comment by samuelchristlie** [comment]
I'm not sure if this is an expected behavior

```
const (
	// Auto is used to widget.Size to indicate height or width to occupy available spaces.
	Auto [float32](https://pkg.go.dev/builtin#float32) = -1
)
```
On one hand, it _does_ fill the available space, but I was thinking the sizes would get calculated after other widgets.

**Comment by gucio321** [comment]
@samuelchristlie sorry for late raply
This works as expected. 
Think about this like that: giu calls widgets one by one, so at the moment of calling your dummy (spacer) it does not know that you're going to add your submit button.

In order to calculate your dummy's height, you need to use `giu.GetAvailableRegion` and decrease it by height of your button

**Comment by samuelchristlie** [comment]
Ahh, that makes sense. Thank you :+1:
