### ISSUE TITLE
[bug] Labels keep getting corrupted with a ListBox and Table combo

### ISSUE THREAD

**Issue by hhvn-uk** [AllenDang/giu#804]
### What happend?

I have a ListBox which contains a string for each element in an array.

I then have a table below which shows more information about the selected element.

After selecting a couple different elements, all the text seems to get corrupted like this:
![gui](https://github.com/AllenDang/giu/assets/127678453/1bb97334-8b05-4a32-8506-72cfb2af4819)

But attaching dlv and looking at the function that builds the list.. it's all fine:
![dlv](https://github.com/AllenDang/giu/assets/127678453/62331dfc-cf92-431c-933d-03c98615e806)

### Code example

The program I'm working on is a bit of a mess at the moment, so I've made a [tarball](https://hhvn.uk/archive.tar.bz) that contains it in its current state and the input file I'm using.

### To Reproduce

```
make
./gui library.json
```

Click a couple different items in the list

### Version

(latest)

### OS

Void Linux x86_64

**Comment by hhvn-uk** [comment]
I should clarify that with the dlv screenshot, I simply broke on the tostrings() function and then stepped thru it a bit before printing ret, hence the empty strings.

**Comment by gucio321** [comment]
https://hhvn.uk/archive.tar.bz 404

unfortunately I can't say much without seeing your code..

**Comment by hhvn-uk** [comment]
Ah sorry my bad. I am way too scatterbrained.

https://hhvn.uk/gui.tar.bz

If that's not right you've got the right to demand I eat my hat :)

**Comment by gucio321** [comment]
ok, first of all, you're using v0.7.0, which was the last release with imgui-go. Now we migrated to cimgui-go and technically can't support imgui-go anymore (@AllenDang maybe we should release v0.8.0 now as most things seems to work?)
I've updated your project and now it crashes when clicking on 6th item:
```console
File: /home/runner/work/cimgui-go/cimgui-go/cimgui/imgui/imgui_draw.cpp, Line 3307

Expression: Glyphs.Size > 0 && "Font has not loaded glyph!"


```
I have no idea why :smile:

**Comment by AllenDang** [comment]
@gucio321 Agree, let's release the 0.8.0. Maybe you could do it and write a release announcement to reddit? Because you are the major developer of this release, many thanks from the bottom of my heart for your contribution. So I'd like you to be the one to do it. What do you think?

**Comment by gucio321** [comment]
@AllenDang you should see v0.8.0 - I made it draft for now, could you check if all is ok, and publish/let me know?

**Comment by AllenDang** [comment]
@gucio321 Everything looks good, lets roll it out.

**Comment by hhvn-uk** [comment]
> It takes sel.NSeries (which is intager) and enforces go to interpret it as a string, which then is passed to cimgui-go. In case of 6th position in your library, NSeries = 0, so `string(0)` becomes a `NULL` character ([ref: ascii table](https://www.asciitable.com/)). and ofc our default font does not have it.

Ah hah! I now see why strconv.Itoa exists.

Thanks. I could never have guessed that that caused it. Seems weird for one character to affect everything.
