### ISSUE TITLE
v0.8.0: Align+Row is broken

### ISSUE THREAD

**Issue by wsczx** [AllenDang/giu#807]
### What happend?

After upgrading to giu 0.8.0, I cannot use g.Row() to arrange Button widgets horizontally. 0.7.0 has no problem at all

### Code example

<details><summary><code>main.go</code></summary>

```golang
g.Row(
g.Button("Save").OnClick(func() {
if err := conf.SaveConfig(conf.Cfg); err != nil {
log.Printf("Configuration save failed: %s", err)
g.Msgbox("Warning", "Configuration save failed, please check the log!")
} else {
g.Msgbox("Tip:", "Configuration saved successfully!")
}
}),
g.Button("Exit").OnClick(func() {
systray.Quit()
os.Exit(0)
}),
),
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

(latest)

### OS

Windows11

**Comment by gucio321** [comment]
I need more code, because this one works for me
![image](https://github.com/AllenDang/giu/assets/73652197/6c8d15c5-d5a0-4853-abea-ea3a6f243858)

```go
package main

import (
	"github.com/AllenDang/giu"

	g "github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		g.Row(
			g.Button("Save").OnClick(func() {
				/*
					if err := conf.SaveConfig(conf.Cfg); err != nil {
						log.Printf("Configuration save failed: %s", err)
						g.Msgbox("Warning", "Configuration save failed, please check the log!")
					} else {
						g.Msgbox("Tip:", "Configuration saved successfully!")
					}
				*/
			}),
			g.Button("Exit").OnClick(func() {
				/*
					systray.Quit()
					os.Exit(0)
				*/
			}),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("Issue 807", 640, 480, 0)
	wnd.Run(loop)
}
```

**Comment by wsczx** [comment]
```
// g.Align(g.AlignCenter). To(
g.Row(
g. Button OnClick(func() {}),
g. Button OnClick(func() {}),
),
// )
```
It seems that the Align (g. AlignCenter) was caused by the use of centering

**Comment by gucio321** [comment]
Ok, I found a reason for that: it seems that `GetWidgtWidth` is bugged for some reason

If I comment it out from `(*AlignmentSetter).Build()` it doesn't remove last button... Why?

**Comment by gucio321** [comment]
I think I know whats wrong:

(from `Alignment.go`)

```go
        // save widget's width
        // check cursor position
        imgui.SameLine()

        spacingW, _ := GetItemSpacing()
        result = float32(GetCursorPos().X-startPos.X) - spacingW

```

this SameLine does some trick that I do not understand at all.

All we need to know is that adding imgui.NewLine after obtaining result works fine.
PR arrives soon and bugfix release will follow it.
