### ISSUE TITLE
[bug] Context.GetPlatform().GetContentScale() is missing in v0.8.0

### ISSUE THREAD

**Issue by xEricL** [AllenDang/giu#809]
### What happend?

In v0.7, I used `Context.GetPlatform().GetContentScale()` to scale a progress bar. However, it appears `GetPlatform()` has been removed in v0.8.0 [in this commit.](https://github.com/AllenDang/giu/commit/b42ec3d4900e536ab1024e9a944f0cf520f51fe3)

 What is the alternative?

### Code example

<details><summary><code>main.go</code></summary>

I was using
```golang
giu.SingleWindow().Layout(
	giu.Align(giu.AlignCenter).To(
		giu.Dummy(0, scaleDivider(6)),
		giu.ImageWithRgba(logoI).Size(LogoSize, LogoSize),
		giu.Dummy(0, scaleDivider(6)),
		giu.ProgressBar(ReadProgress()).Size(scaleValue(WindowWidth)*0.75, scaleValue(5)),
	),
)
```

where `scaleDivider` and `scaleValue` were defined as
```golang
func scaleDivider(value float32) float32 {
	scale := giu.Context.GetPlatform().GetContentScale()
	if scale > 1.0 {
		value *= 2
	}
	return value * scale
}

func scaleValue(value int) float32 {
	scale := giu.Context.GetPlatform().GetContentScale()
	return float32(value) * scale
}
```

</details>

### To Reproduce

1. Update to v0.8.0
2. Try to build project that was previously using `giu.Context.GetPlatform().GetContentScale()`

### Version

(latest)

### OS

Fedora

**Comment by gucio321** [comment]
hi, GetScaleFactor was a part of imgui-go api.
Now, we check scale as follows:
(MasterWindow.go)
```go
        // Scale DPI in windows
        if runtime.GOOS == "windows" {
                xScale, _ := Context.backend.ContentScale()
                imgui.CurrentStyle().ScaleAllSizes(xScale)
        }
```

go get access to Context.backend try using cimgui.CurrentBackend

**Comment by xEricL** [comment]
> go get access to Context.backend try using cimgui.CurrentBackend

Can you please give a code example? I'm having trouble finding `cimgui.CurrentBackend`.

**Comment by gucio321** [comment]
Because, as i just realized, v it doesn't exist hehe 😅 
 ill add `giu.Context.Backend` later

**Comment by gucio321** [comment]
- see #811

**Comment by gucio321** [comment]
I suppose this is fixed, lmk if you still need help.

# :warning: If you use ScaleAllSizes, this is IMPORTANT :warning:
Take a look at the following things:
- #810 
- #812
