### ISSUE TITLE
[bug] Freeze in the main loop after loading an embedded font file and use it as the default font

### ISSUE THREAD

**Issue by scorpheus** [AllenDang/giu#820]
### What happend?

My Goal is to display this kind of emoji "🚫🕒⏱️🏁📏🌍📍🚀➡️👉💨🎮🎚️⚙️🔩🏎️🛞🔧🔄⛽🔋🚥🛠️🛑🌡️🏆🔢🎡↖️↗️✅❌°C|/[]()#_")

I load an embedded file, set as default, and in the main loop, the app freeze.
It works in debug in vscode but not in release

version used:
	github.com/AllenDang/cimgui-go v0.0.0-20240611070805-39b5aa2438db
	github.com/AllenDang/giu v0.8.1

### Code example

<details><summary><code>main.go</code></summary>

```golang
//go:embed seguiemj.ttf
var embeddedFonts embed.FS

func loadFonts() {
	// Load font
	fontPath := "seguiemj.ttf"
	fontSize := float32(15)

	fontData, err := embeddedFonts.ReadFile(fontPath)
	if err != nil {
		log.Fatalf("Failed to read embedded font file: %v", err)
	}
	giu.Context.FontAtlas.AddFontFromBytes(fontPath, fontData, fontSize)

	giu.Context.FontAtlas.SetDefaultFont(fontPath, fontSize)
}
```

</details>

### To Reproduce

call loadFonts before wnd.Run(loop) (not in debug)
it should freeze 

### Version

(latest)

### OS

windows 10, go version go1.22.0 windows/amd64

**Comment by gucio321** [comment]
@scorpheus its always the problem unfortunately, but I thinkk its a good time to fix this now :smile:

Could you please attach your font file or create a github repo with your example project? (it should be easier to debug then)

**Comment by scorpheus** [comment]
[simple_test.zip](https://github.com/user-attachments/files/16160318/simple_test.zip)
After making this simple test, I saw an old reference to fyne in my project, it was the culprit.
just add `widget.BaseWidget` from `"fyne.io/fyne/v2/widget"` and the app freeze.
But only if you load a font.
if you comment loadFonts, the app is not freezing.
if you remove fyne, it works

**Comment by gucio321** [comment]
well, unfortunately I can't say why using fyne along with giu doesn't work.
I suppose this is something related to glfw (both fyne and giu may use it) and I suppose doing it at the same time may not be a good idea.

**Comment by scorpheus** [comment]
Not a good idea indeed,
Avoid to use fyne and load font at the same time and everything is working ;)
