### ISSUE TITLE
[bug]Abnormal CPU load

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/giu#827]
### What happend?

When I was using the latest version of giu, I found a CPU exception. You can see the difference in CPU load by using programs packaged in examples/widgets and programs compiled directly to run

### Code example

<details><summary><code>main.go</code></summary>

```golang
examples/widgets
```

</details>

### To Reproduce

1. Run my demo
2. will see the crash...

### Version

master

### OS

windows10

**Comment by AllenDang** [comment]
@lzytaro I just did a quick test on macOS, the CPU occupation is 0% when the gui is idle.
![image](https://github.com/user-attachments/assets/074b81b8-330e-4c41-b814-dcec523d48e4)

**Comment by lzytaro** [comment]
> @lzytaro I just did a quick test on macOS, the CPU occupation is 0% when the gui is idle. ![image](https://private-user-images.githubusercontent.com/18550/351252382-074b81b8-330e-4c41-b814-dcec523d48e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjUwODcsIm5iZiI6MTcyMTcyNDc4NywicGF0aCI6Ii8xODU1MC8zNTEyNTIzODItMDc0YjgxYjgtMzMwZS00YzQxLWI4MTQtZGNlYzUyM2Q0OGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4NTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNDY1NzA4OTM5MGZiYzgxYzE3OWQ4YjIwZjgzZjE5NDhjYmEyY2Y0NDE2ZjNiZTllYWU2YzVjYzc5ODljZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZGj0Tg3txJVbJo-bz7wi3QC-FLNXczY00hWh7mVfmo)

Sorry, my business pc cannot upload the screenshot. Maybe its only happend on a Windows 10 PC？
go version go1.21.12 windows/amd64

**Comment by gucio321** [comment]
@lzytaro may i ask you to write issue title and description in English pls Thank you!

Also, could you check if example from cimgui-go had the same problem?

**Comment by lzytaro** [comment]
Maybe there is any problem with my computer. I tried the same case today, but it works normally. I'll close this issue, sorry to bother you.

**Comment by lzytaro** [comment]
I used the fps example in the example directory and used the two versions 0.7.0 and 0.8.1 for a long time. The CPU usage of 0.8.1 is significantly higher than that of 0.7.0. Due to the many changes in the two versions, no specific problem points have been identified for the time being.

**Comment by lzytaro** [comment]
![image](https://github.com/user-attachments/assets/f325f5fb-bce0-4fab-be3e-8f8e5ac1444a)
The problem here is that the program will fall into a short endless loop while, causing a high CPU load. 0.7.0 used time.Ticker to process the timer in go, so this problem did not occur.

code file:
https://github.com/AllenDang/cimgui-go/blob/main/glfw_backend.cpp

@AllenDang @gucio321

**Comment by lzytaro** [comment]
I created a pr to solve this problem[https://github.com/AllenDang/cimgui-go/pull/294](url)

**Comment by gucio321** [comment]
Ok! well,  Generally I'm in the middle of the forest right now but will try to review asap

**Comment by gucio321** [comment]
Oh i see it's already merged. Could you please create a pr here to upgrade cimgui-go version?

**Comment by lzytaro** [comment]
> Oh i see it's already merged. Could you please create a pr here to upgrade cimgui-go version?

OK sure, here is it [https://github.com/AllenDang/giu/pull/833](url)
