### ISSUE TITLE
[Question] How to Center Master Window?

### ISSUE THREAD

**Issue by xEricL** [AllenDang/giu#828]
In v0.7, my Master Window was automatically centered on the screen. After upgrading to v0.8, it now renders at the top-left corner. How do I get it back to the middle of the screen?

**Comment by gucio321** [comment]
Maybe `(*MasterWindow).SetPos(...)` can help here

**Comment by xEricL** [comment]
> Maybe `(*MasterWindow).SetPos(...)` can help here

I tried that, but where should I get x,y from? I tried giu.GetAvailableRegion() but I keep getting a segment violation.

**Comment by xEricL** [comment]
@gucio321 I just figured out I can do it with this:

```go
window = giu.NewMasterWindow("title", 377, 144, 0)
monitor := cimgui.CurrentPlatformIO().Monitors()
ws := monitor.Data.WorkSize()

centerX := (ws.X - float32(377)) / 2
centerY := (ws.Y - float32(144)) / 2

window.SetPos(int(centerX), int(centerY))
```

Only problem is that I have 3 monitors and it keeps rendering on monitor 2, not my primary monitor. This was an issue in v0.7 and it appears to be only affecting me on Linux (I tested it and it renders on primary monitor on Windows).

**Comment by gucio321** [comment]
I'm not sure.. maybe `SetHighlightMonitorIdx`?

**Comment by gucio321** [comment]
I think the originall issue was resloved. lmk if you still need help here!
