### ISSUE TITLE
Popup Window outside the Master Window

### ISSUE THREAD

**Issue by OfflinePing** [AllenDang/giu#841]
### What happend?

I created a Master Window with a Popup Modal inside. And I am able to drag it anywhere on the screen. I dont know if this is intended or a bug :D

![image](https://github.com/user-attachments/assets/060d2621-ee13-4c01-81d1-dfd3c8bad037)

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import g "github.com/AllenDang/giu"

func loop() {
	Window := g.SingleWindow()

	Window.Layout(
		g.PopupModal("Popup Modal").Layout(
			g.Label("This is a popup modal"),
			g.Button("Close").OnClick(func() {
				g.CloseCurrentPopup()
			}),
		),
		g.Row(
			g.Button("Open Popup Modal").OnClick(func() {
				g.OpenPopup("Popup Modal")
			}),
		),
	)
}

func main() {
	wnd := g.NewMasterWindow("Cloud - Universal", 750, 500, g.MasterWindowFlagsNotResizable)

	wnd.Run(loop)
}
```
</details>

### To Reproduce

1. Run my demo
2. Drag the Window around
3. See its outside Master Window

### Version

master

### OS

Windows 11

**Comment by gucio321** [comment]
It is docking branch of imgui, idk how to disable it tbh. Ill need to check

**Comment by gucio321** [comment]
@OfflinePing I've checked out and added it on wiki: https://github.com/AllenDang/giu/wiki/FAQ#windows

 Q:  I can drag my Window out of the MasterWindow! I don't want that! \
 A:  This is a new Dear ImGui feature from the docking branch that is enabled by default in cimgui-go.
To disable it, do the following after `NewMasterWindow`:
```go
io := imgui.CurrentIO()
io.SetConfigFlags(io.ConfigFlags() & ^imgui.ConfigFlagsViewportsEnable)
```
