### ISSUE TITLE
[bug] StyleColorPlotLines has no effect on a Plot

### ISSUE THREAD

**Issue by hirikilabs** [AllenDang/giu#847]
### What happend?

Applying a SetColor with StyleColorPlotLines to a Plot with a Line, results in the line plot drawn in the default color. Any other color change in the same Style() call (border, background...) works normaly.

### Code example

<details><summary><code>main.go</code></summary>

```golang
g.SingleWindow().Layout(
		g.Style().
			SetColor(g.StyleColorBorder, color.RGBA{250, 100, 100, 255}).
			SetColor(g.StyleColorPlotLines, color.RGBA{250, 100, 100, 255}).
			To(
				g.Plot("Plot 1").AxisLimits(0, 128, -1.2, 1.2, g.ConditionOnce).Plots(
					g.Line("Kaixo", buffer[:]),
				),
			),
	)
```

</details>

### To Reproduce

1. Run the demo code
2. Line Plot will be drawn in the default bluish color instead of the red color provided

### Version

(latest)

### OS

Debian Sid

**Comment by gucio321** [comment]
ok, let me take a look
just btw, there was some reason why I wrote in #392 that we want the whole `main.go`.

<details><summary><code>main.go</code></summary>

```go
package main

import (
	"slices"

	"github.com/AllenDang/giu"
	"golang.org/x/image/colornames"
)

var buffer = slices.Repeat([]float64{0, 1}, 8)

func loop() {
	giu.SingleWindow().Layout(
		giu.Style().
			SetColor(giu.StyleColorBorder, colornames.Yellow).
			SetColor(giu.StyleColorPlotLines, colornames.Red).
			To(
				giu.Plot("Plot 1").AxisLimits(0, 128, -1.2, 1.2, giu.ConditionOnce).Plots(
					giu.Line("Kaixo", buffer[:]),
				),
			),
	)
}

func main() {
	wnd := giu.NewMasterWindow("Style for PlotLine [debug,issue-847]", 800, 600, 0)
	wnd.Run(loop)
}
```

</details>

**Comment by gucio321** [comment]
well, I see: `giu.StyleColorPlotLines` is a link to `cimgui.ColPlotLine` which does... IDK what it does but it does not change color of plot lines in implot (that makes sense as it comes from imgui not implot).
The correct link should be `cimgui.PloColLine`

**Comment by gucio321** [comment]
I've noticed one more thing: `cimgui.PlotCol` cannot be used in `cimgui.PushStyleColor*` but in `cimgui.PlotPushStyleCol*` this will force giu to implement additional features here.

We need to decide wheather we want to put all styles together (StyleSetter will figure out which method should it use) or make separated `StyleSetter`'s method for Plot styles and add another PlotStyleColor enum.
@AllenDang what do you think?
