### ISSUE TITLE
ListBox automatically puts the focus on first item

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#85]
Trying to figure out how to get around this. 

![image](https://user-images.githubusercontent.com/35279710/98691545-2292fb80-233c-11eb-9a8f-b815cc00916f.png)

You can see above an image of what is happening. When I open the window it defaults to the top selection for the focus and does not move off of it even if I select another item in the list. 

I'd like to set it so that it will keep the focus on the item currently selected and only it until a different user is selected. 

see code below. 
```go
g.SplitLayout("User Security", g.DirectionHorizontal, false, 200, g.Layout{
	g.Custom(func() {
		if len(dbUserList) <= 0 {
			dbUserList = u.InitDbUserList()
			u.ClearUser()
			g.Update()
		}
		if len(departments) <= 0 {
			initDepartments()
			g.Update()
		}	
		inituType()
	}),
	g.ListBox("##User List", dbUserList, dblookup, dblookup),
	g.Custom(func() {
		if g.IsKeyPressed(264){ 
			if lv <= len(dbUserList)-1{
			    lv++
			}else {
			   lv = 0
			}
			if lv >= 0 && lv < len(dbUserList){
				dblookup(lv)
			}
		} else if g.IsKeyPressed(265){
			if lv == 0 {
				lv = len(dbUserList)-1
			}else {
				lv--
			}
			   if lv >= 0 && lv < len(dbUserList){
				dblookup(lv)
			   }
			}
		}),
	g.ContextMenu(g.Layout{
	g.Checkbox("Sort", &u.AtoZ, func() {
		dbUserList = nil
		u.DbUserList = nil
		g.Update()
	}),
	g.Checkbox("Active Users", &u.ActiveUsers, func() {
		dbUserList = nil
		u.DbUserList = nil
		g.Update()
	}),
}),```

**Comment by AllenDang** [comment]
The suspicious root cause is `inituType()` and below code
```go
g.Custom(func() {
		if g.IsKeyPressed(264){ 
			if lv <= len(dbUserList)-1{
			    lv++
			}else {
			   lv = 0
			}
			if lv >= 0 && lv < len(dbUserList){
				dblookup(lv)
			}
		} else if g.IsKeyPressed(265){
			if lv == 0 {
				lv = len(dbUserList)-1
			}else {
				lv--
			}
			   if lv >= 0 && lv < len(dbUserList){
				dblookup(lv)
			   }
			}
		}),
```

You could comment them to test whether listbox works fine.

**Comment by roborobs1023** [comment]
Sorry should have had comments in the code to explain. 

inituType() intializes the items list for the User Type dropdown. Since it is a static list there was no need to do the if statement as with the above slices. 

I noticed this issue even before putting the User Type dropdown in.

**Comment by AllenDang** [comment]
@roborobs1023 I noticed that giu's version in your go.mod file is very old. Can you update giu to newest version and try again?

**Comment by AllenDang** [comment]
@roborobs1023 Any update?

**Comment by roborobs1023** [comment]
That worked perfectly. Is there any way in the new version to set the Splitter widget to a static position so that it cannot be updated by the user? 

For instance on my Security Users "window" I have the system list out every database user on the left pane and have a details panel on the right which only fills out when you select a user or when you fill it out to create a new user. As it currently stands after updating the GIU version, you can now move the bar separating the two panels. I would like this to be stationary in order to prevent a user from accidently moving it. 


I'm also having a hard time getting fonts to show up correctly. I can get the labels to change color based on the RGBA data entered but they aren't activating the font based on the fonts initialized during the main window launch. 

I'll create you a user in the database so you can see the issue above by running the software, if you don't mind helping. It is pretty a small package. Will send creds through github.

**Comment by AllenDang** [comment]
@roborobs1023 
You could use giu.Child with giu.Line to create static splitter widget like below.
```go
giu.Line(
  giu.Child("Left panel", true, width, height, 0, giu.Layout{}),
  giu.Child("Right panel", true, width2, height2, 0, giu.Layout{}),
)
```

To set different fonts for specified widgets, do like this
```go
func loadFont() {
  fonts := g.Context.IO().Fonts()
  
  // This will be the default font.
  defaultFont := fonts.AddFontFromFileTTFV(...)

  // Create another font for further usage.
  anotherFont := fonts.AddFontFromFileTTVF(...)
}

func loop() {
  g.PushFont(anotherFont)
  // All widgets here will use anotherFont.
  g.PopFont()
}

func main() {
  wnd := g.NewMasterWindow("Testing", 1024, 768, 0, loadFont)
  wnd.Main(loop)
}
```

**Comment by roborobs1023** [comment]
When I do the code as above I get defaultFont declared but not used.

func loadFont() {
    fonts := g.Context.IO().Fonts()

    //default font
    defaultFont := fonts.AddFontFromFileTTFV("./Fonts/PTSerif-Regular.ttf", 16, imgui.DefaultFontConfig, fonts.GlyphRangesDefault())
    //g.PushFont(defaultFont)

}


func loop() {

    if showmain == true {
        g.SingleWindowWithMenuBar("TAM - Aseet Management", g.Layout{
            g.MenuBar(
                g.Layout{
                    g.Menu("File", g.Layout{
                        g.MenuItem("Users", nil),
                        g.MenuItem("Assets", nil),
                        g.MenuItem("Close", nil),
                    }),
                },
            ),
            g.Label("This is a test of fonts."),
        })
    }

}

func main() {
    w := g.NewMasterWindow("TAM - Asset Management", 1000, 800, 0, loadFont)
    w.Main(loop)
}



When I uncomment the g.PushFont(defaultFont) I get

Assertion failed: font && font->IsLoaded(), file imgui.cpp, line 6278

Any ideas?

ps: this is a test file and not the files on github.

Robert Tucker
IT Specialist



“When the storms come and all other birds seek shelter, the eagle alone avoids the storm by flying over it. So, in the storms of life may your heart soar like an eagle.” ~Author Unknown

________________________________

**Comment by roborobs1023** [comment]
Never mind I got it figured out. it was cause of the way I was declaring it.


Robert Tucker
IT Specialist
Email: roborobs_computers@live.com
Phone: (863) 651-1827


“When the storms come and all other birds seek shelter, the eagle alone avoids the storm by flying over it. So, in the storms of life may your heart soar like an eagle.” ~Author Unknown

________________________________

**Comment by roborobs1023** [comment]
Haven't quite gotten the g.PushFont and g.Popfont functions working as go throws an error that I'm using them as values when I try to put them around a single label or set of widgets within a layout.

Robert Tucker
IT Specialist



“When the storms come and all other birds seek shelter, the eagle alone avoids the storm by flying over it. So, in the storms of life may your heart soar like an eagle.” ~Author Unknown

________________________________

**Comment by AllenDang** [comment]
@roborobs1023 
g.PushFont is a function call. You should wrap them like this.
```go
g.Layout{
  g.Custom(func() {
    g.PushFont()
  }),
  g.Label(...),
  g.Custom(func() {
    g.PopFont()
  }),
}
```

**Comment by roborobs1023** [comment]
Oh ok. That makes sense.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
