### ISSUE TITLE
[bug] Finalizer still misbehaving againt ImageWithRGBA

### ISSUE THREAD

**Issue by cjbrigato** [AllenDang/giu#854]
### What happend?

It seems that the GPU Memory leak via `ImageWithRGBA` is still there and strong, with the finalizer not firing most of the time.

I came to an overall very satisfying and simple solution by wrapping the `giu.Texture`methods to a check agains last know state, updating it if necessary *and* forcefully releasing the GPU Resources in case of update.

```
type RGBABackedTexture struct {
	Image   *image.RGBA
	tex     *giu.Texture
	lastSum uint32
}

func (i *RGBABackedTexture) sum() uint32 {
	return crc32.ChecksumIEEE(i.Image.Pix)
}

func(i *RGBABackedTexture) ensureSynced() {
	if sum := i.sum(); sum != i.lastSum {
		giu.Context.Backend().DeleteTexture(i.tex.ID())
		giu.NewTextureFromRgba(i.Image, func(tex *giu.Texture) {
			i.tex = tex
		})
		i.lastSum = sum
	}
}

func(i *RGBABackedTexture) Texture() *giu.Texture {
	i.ensureSynced()
	return i.tex
}

func(i *RGBABackedTexture) ID() imgui.TextureID {
	return i.Texture().ID()
}
```

I usually directly feed ```giu.Image()``` at anytime in the render loop, had it changed or not, it just works flawlessly.

```golang
// [...] somewhere

	draws := g.GetDrawCommands(g.Canvas.LastComputedLen)
	for _, r := range draws {
		switch r.Tool {
		case 0:
			line := r.ToLine()
			paint.DrawLine(line.P1.X, line.P1.Y, line.P2.X, line.P2.Y, line.C, line.Thickness, myRGBABackedTexture.Image)
		case 1:
			f := r.ToFill()
			paint.Floodfill(myRGBABackedTexture.Image, f.C, f.P1.X, f.P1.Y)
		default:
		}
	}
// dont even bother about refreshing texture now

// [...] then in render loop:
func CanvasWidget(game *skribbl.Game) *g.CustomWidget {
return g.Custom(func() {
 g.Image(myRGBABackedTexture.Texture()).Size(800, 600).Build()
		if g.IsItemHovered() {
//[...]
}
```

I think we should definitely "fix" or workaround ImageWithRGBA because this bug is old enough to assume that it will missbehave by default.

If you agree with this, i'd be happy to send a PR.

### Code example

<details><summary><code>main.go</code></summary>

```golang
// [...]
	g.ImageWithRgba(rgba).OnClick(func() {
			fmt.Println("rgba image was clicked")
		})
//[...]
```

</details>

### To Reproduce

1. Use gImageWithRgba in render loop
2. Appreciate your GPU Memory filling up

### Version

master

### OS

Windows 11

**Comment by gucio321** [comment]
@cjbrigato would be awesome to have a pr from you!

I'm just quite busy with cimgui-go and had no time for giu 😭

**Comment by cjbrigato** [comment]
Incoming in few hours, max 1day.
It overhauls quite the whole "Image" Widgets. For the good.

**Comment by cjbrigato** [comment]
https://github.com/AllenDang/giu/pull/855

nearly finished
