### ISSUE TITLE
Windows open outside MasterWindow

### ISSUE THREAD

**Issue by jasmeer** [AllenDang/giu#880]
Hi
I am running multiwindow example and windows are opened out side the MasterWindow.  Is it possible to keep the windows inside Masterwindow always? They should never move outside Master window boundaries.
Thanks
Jas

**Comment by gucio321** [comment]
Technically, disabling bu imgui CurrentIO().SetFlags  docking geatires should work

**Comment by jasmeer** [comment]
I couldn't figure out how to do it. I think what I need is to disable multiple viewport, but require docking. Looking at thus issue https://github.com/ocornut/imgui/issues/7985 there is a way to do this:

> ImGui::SetNextWindowViewport(ImGui::GetMainViewport()->ID); // Disable this widget from popping out
> ImGuiWindowFlags window_flags = 
>     ImGuiWindowFlags_NoCollapse 
>     | ImGuiWindowFlags_NoBringToFrontOnFocus
>     | ImGuiWindowFlags_NoDocking;
> ImGui::Begin((std::string(ICON_FA_GRIP_LINES) + " Layer Stack").c_str(), nullptr, window_flags);
> // Left out for brevity
> ImGui::End();

Thanks for quick response.
Jas

**Comment by gucio321** [comment]
you can do this if you want to keep viewport features but set window pos relative to MW:
```go
        vp := imgui.MainViewport().Pos()
        giu.Window("I don't want to be outside of my MasterWindow
                Pos(0+vp.X, 0+vp.Y).
                Layout(
                        giu.Label("I'm a window btw"),
                )
```

**Comment by gucio321** [comment]
to completely disable viewports use the following line (in any other improved form)
```go
        imgui.CurrentIO().SetConfigFlags(imgui.CurrentIO().ConfigFlags() & ^imgui.ConfigFlagsViewportsEnable)
```

Let me close this. lmk if you still need help ;-)

**Comment by jasmeer** [comment]
Thanks a lot. Really appreciate your help.
