### ISSUE TITLE
[bug] Vertical split layout height off by 1 pixel

### ISSUE THREAD

**Issue by SleepyPrince** [AllenDang/giu#888]
https://github.com/AllenDang/giu/blob/c4e585a3f8b10bfc9ba0e1d8ed61824bd8db4f2f/SplitLayout.go#L104

This line using 0 instead of Auto like in other places within func (s *SplitLayoutWidget) Build() is causing the left side height to be 1 pixel larger than the right side. On the other hand, I was expecting any value <= 0 for width/height should have the same effect as 'Auto'.

**Comment by gucio321** [comment]
You're right, let me fix that
