### ISSUE TITLE
Table from CSV Struct data 

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#89]
Allen,

I'm trying to put data from the following into rows within a table to display on the iusers window. Below is the code I have any idea why the table errors out on me?
```
g.Condition(issue == false, g.Layout{
						g.Table("Import Details", true, g.Rows{
							g.Row(g.Label("First Name"), g.Label("Last Name"), g.Label("Username"),g.Label("Email"), g.Label("Department"),g.Label("Supervisor")), 
							g.Row(g.Custom(func(){
								firstnames = nil
								lastnames = nil
								usernames = nil
								emails = nil
								supervisors = nil
								departments = nil
									for i := 0; i <= len(u.Users); i++ {
										u.LookupEndUser("username", u.Users[i], cred.username)
										firstnames = append(firstnames, u.User.FirstName)
										lastnames =  append(lastnames, u.User.LastName)
										usernames = append(usernames, u.User.UserName)
										emails = append(emails, u.User.Email)
										departments = append(departments, u.User.Department)
										supervisors = append(supervisors, u.User.Supervisor)
										g.Row(g.Label(firstnames[i]), g.Label(lastnames[i]), g.Label(usernames[i]),g.Label(emails[i]), g.Label(departments[i]), g.Label(supervisors[i]))
									}
								})),
							}),
						},
						g.Layout{}), 
					}, 

```

Here is the message that Go is giving me.

goroutine 1 [running, locked to thread]:
main.loop.func60()
        C:/Scripts/Go/TAM/main.go:1134 +0xba3
github.com/AllenDang/giu.(*CustomWidget).Build(0xc000006400)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Widgets.go:1451 +0x3d
github.com/AllenDang/giu.(*RowWidget).Build(0xc0000054c0)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Widgets.go:1301 +0x7d
github.com/AllenDang/giu.(*TabelWidget).Build(0xc0002b61b0)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Widgets.go:1334 +0x93
github.com/AllenDang/giu.Layout.Build(0xc0001a8ca0, 0x1, 0x1)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Layout.go:11 +0x61
github.com/AllenDang/giu.(*ConditionWidget).Build(0xc000260800)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Widgets.go:1478 +0x5c
github.com/AllenDang/giu.Layout.Build(0xc000144000, 0x7, 0x7)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Layout.go:11 +0x61
github.com/AllenDang/giu.(*ConditionWidget).Build(0xc000260840)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Widgets.go:1478 +0x5c
github.com/AllenDang/giu.Layout.Build(0xc00045dba0, 0x5, 0x5)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Layout.go:11 +0x61
github.com/AllenDang/giu.WindowV(0xbab340, 0x5, 0xffcdaa, 0x426, 0x41a0000043020000, 0x4479400044dfc000, 0xc00045dba0, 0x5, 0x5)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/Window.go:62 +0xe4
main.loop()
        C:/Scripts/Go/TAM/main.go:903 +0x97c1
github.com/AllenDang/giu.(*MasterWindow).render(0xc00009c000)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/MasterWindow.go:170 +0x9d
github.com/AllenDang/giu.(*MasterWindow).run.func1()
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/MasterWindow.go:189 +0x60
github.com/AllenDang/giu.Call.func1()
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/MainThread.go:67 +0x36
github.com/AllenDang/giu.Run(0xc00009a260)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/MainThread.go:53 +0x79
github.com/AllenDang/giu.(*MasterWindow).Main(0xc00009c000, 0xbd9908)
        C:/Scripts/Go/TAM/vendor/github.com/AllenDang/giu/MasterWindow.go:236 +0x67
main.main()
        C:/Scripts/Go/TAM/main.go:1628 +0x197

**Comment by AllenDang** [comment]
This line, you need to invoke Build method in giu.Custom().

Change below
```go
g.Row(g.Label(firstnames[i]), g.Label(lastnames[i]), g.Label(usernames[i]),g.Label(emails[i]), g.Label(departments[i]), g.Label(supervisors[i]))
```
to
```go
g.Row(g.Label(firstnames[i]), g.Label(lastnames[i]), g.Label(usernames[i]),g.Label(emails[i]), g.Label(departments[i]), g.Label(supervisors[i])).Build()
```

**Comment by AllenDang** [comment]
@roborobs1023 Any update?

**Comment by roborobs1023** [comment]
Sorry, 

Just getting a chance to look into it this morning. Been dealing with the holiday and family.

**Comment by roborobs1023** [comment]
That worked to get to pull the data unfortunately it is cascading the data across the row instead of going to a new row. What would be the command to make it do a new row after each pass?

**Comment by AllenDang** [comment]
@roborobs1023 Because you create row inside a row.

**Comment by roborobs1023** [comment]
I thought that was the issue. However when I try to do it such as the following,

g.Rows{ 
g.Custom(func(){})

I get an error. Is there a way to return a g.Row or multiple rows from a function? As g.Row isn't a type nor is g.Rows.

**Comment by AllenDang** [comment]
@roborobs1023 Table needs a g.RowWidget array, and g.Row(...) returns a g.RowWidget.
You could define a function which returns a g.RowWidget array like below.

```go
func createRows(...) g.Rows {
}

func loop() {
   ...
   g.Table("Data table", true, createRows())
}
```

**Comment by roborobs1023** [comment]
I have the following however I'm getting an error on the for loop. 


func initImportRows() g.Rows{
	firstnames = nil
	lastnames = nil
	usernames = nil
	emails = nil
	supervisors = nil
	departments = nil
	rows = g.Row(g.Label("Row Number"),g.Label("First Name"), g.Label("Last Name"), g.Label("Username"),g.Label("Email"), g.Label("Department"),g.Label("Supervisor")),
		for i := 0; i < len(u.Users); i++ {
			u.LookupEndUser("username", u.Users[i], cred.username)
			firstnames = append(firstnames, u.User.FirstName)
			lastnames =  append(lastnames, u.User.LastName)
			usernames = append(usernames, u.User.UserName)
			emails = append(emails, u.User.Email)
			departments = append(departments, u.User.Department)
			supervisors = append(supervisors, u.User.Supervisor) 
			g.Row(g.Label(strconv.Itoa(i)),g.Label(firstnames[i]), g.Label(lastnames[i]), g.Label(usernames[i]),g.Label(emails[i]), g.Label(departments[i]), g.Label(supervisors[i])).Build() 
		}

	return rows
}

**Comment by AllenDang** [comment]
@roborobs1023 
```go
var rows g.Rows
rows = append(rows, g.Row(....)) // <- Header
for ... {
  rows = append(rows, g.Row(...)) // <- content
}
```

**Comment by roborobs1023** [comment]
Thank you - That worked. Now I just have to figure out the formatting side of things.
