### ISSUE TITLE
[Feature Request] Support for overlapping (SetNextItemAllowOverlap)

### ISSUE THREAD

**Issue by 11Spades** [AllenDang/giu#904]
### Related problem

I'm currently working on an application which tries to implement a graph with drag-and-droppable nodes. I'm implementing this by making the graph background a full-window invisible button that can be dragged to move around the graph. After `Build()`ing that button, I loop through all of the nodes and `Build()` buttons for them as well. The code is as follows:

Node:
```go
func (w *GraphNodeWidget) Build() {
	g.Context.Backend().DisplaySize()
	g.Button("").Size(25.0, 25.0).OnClick(w.clicked).Build()

	if g.IsItemHovered() && g.IsMouseDoubleClicked(g.MouseButtonLeft) {
		w.doubleClicked()
		return
	}

	if !w.dragging && g.IsItemHovered() && g.IsMouseDown(g.MouseButtonLeft)  {
		println("Dragging!")
		w.dragging = true
		w.lastMousePosition = g.GetMousePos()
	}

	if !w.dragging {
		return
	}

	if g.IsMouseReleased(g.MouseButtonLeft) {
		w.dragging = false
		return
	}

	currentMousePosition := g.GetMousePos()
	w.position = w.position.Add(currentMousePosition.Sub(w.lastMousePosition))
	w.lastMousePosition = currentMousePosition
}
```

Graph:
```go
func (w *DraggableGraphWidget) Build() {
	sizeX, sizeY := g.GetAvailableRegion()
	if sizeX <= 0 || sizeY <= 0 {
		return
	}

	g.InvisibleButton().Size(sizeX, sizeY).Build()

	for _, node := range(w.nodes) {
		g.SetCursorPos(node.position.Sub(w.offset))
		node.Build()
	}

	if !w.dragging && g.IsItemHovered() && g.IsMouseDown(g.MouseButtonLeft) {
		w.dragging = true
		w.lastMousePosition = g.GetMousePos()
		println("YAY")
	}

	if !w.dragging {
		return
	}

	if g.IsMouseReleased(g.MouseButtonLeft) {
		w.dragging = false
		return
	}

	println("Big drag!")

	currentMousePosition := g.GetMousePos()
	w.offset = w.offset.Add(currentMousePosition.Sub(w.lastMousePosition))
	w.lastMousePosition = currentMousePosition

	w.offsetChanged(w.offset)
}
```

The result is that I can drag-and-drop the button that was last built, and only once.

I recognize that I am probably going about this in the most stupid way, and would appreciate being pointed in the right direction.

### Your request

Regardless of whether or not my approach is sound, giu seems to lack the SetNextItemAllowOverlap feature that ImGUI has to solve issues like the one I'm currently experiencing. Some analogue to it would be nice.

**Comment by gucio321** [comment]
hi, Here are some notes from me :smile:
- maybe `giu.GetAvailableRegion` woudl be better here?
```go
	g.Context.Backend().DisplaySize()
	g.Button("").Size(25.0, 25.0).OnClick(w.clicked).Build()
```
- you know about imnodes? https://github.com/Nelarius/imnodes
if it is what you're looking for - cimgui-go has it already implemented (but giu doesn't) so you can use cimgui-go's version

> Regardless of whether or not my approach is sound, giu seems to lack the SetNextItemAllowOverlap feature that ImGUI has to solve issues like the one I'm currently experiencing. Some analogue to it would be nice.

Could you please suggest some API layout for that?
generally, at this point you can always do
```go
giu.Custom(imgui.SetNextItemAllowOverlap),

**Comment by 11Spades** [comment]
Ah, I wasn't aware that you could use `giu.Custom()` in that way. Since that's a possibility, this issue is redundant. I apologize for not looking hard enough.

**Comment by gucio321** [comment]
you're welcome! ;-)
