### ISSUE TITLE
InputFloatV Format String

### ISSUE THREAD

**Issue by roborobs1023** [AllenDang/giu#91]
Do you by any chance have an example of using the InputFloatV field? 

I'm trying to figure out what the Format String needs to be in order for it to process data correctly for USD currency.

I was able to get it to work with the format string "$%.2f" however this doesn't allow for a comma at the thousands place. Is there a way to do this?

Thanks.

**Comment by AllenDang** [comment]
Currently there is no easy way to do that. Need to create a new widget from scratch. If you could read cpp code, you could refer the implementation of InputFloat widget from imgui. It should not so hard.

**Comment by roborobs1023** [comment]
Okay. I just wanted to see if something had already been implemented. Didn't want to go reinventing the wheel.
