### ISSUE TITLE
How can I add onClick for TreeNode widgets?

### ISSUE THREAD

**Issue by fr3fou** [AllenDang/giu#98]
![image](https://user-images.githubusercontent.com/1344906/102924070-852dfa00-4499-11eb-9301-2c6f65539307.png)
I want to be able to call a function when I click on on this. My current workaround is putting a button next to it but it results in poor UX.

**Comment by AllenDang** [comment]
@fr3fou Do you mean click on tree parent or tree item?
If you mean tree item, just use giu.Selectable instead of giu.Label.

```go
g.TreeNode("TreeNode1", g.TreeNodeFlagsCollapsingHeader|g.TreeNodeFlagsDefaultOpen, g.Layout{
  g.Selectable("Tree node 1", onClick),
  g.Selectable("Tree node 2", onClick),
  g.Selectable("Tree node 3", onClick),
  g.Button("Button inside tree", nil),
  }),
```

**Comment by fr3fou** [comment]
But I also want to have the onClick on the parent, i.e TreeNode1 at the top

**Comment by AllenDang** [comment]
@fr3fou Try this
```go
g.TreeNode("TreeNode1", g.TreeNodeFlagsCollapsingHeader|g.TreeNodeFlagsDefaultOpen, g.Layout{
  g.Custom(func() {
    if g.IsItemActive() && g.IsMouseClicked(g.MouseButtonLeft) {
      fmt.Println("Tree node clicked")
    }
  }),
  g.Selectable("Tree node 1", func() {
    fmt.Println("Click tree node 1")
  }),
  g.Label("Tree node 2"),
  g.Label("Tree node 3"),
  g.Button("Button inside tree", nil),
}),
```

**Comment by fr3fou** [comment]
That almost works, only 2 issues:
- It only works if it's open
- The children use Label / Selectable, where in my case they are other TreeNode (it looks weird when using Label / Selectable)

for context, i'm trying to recreate a small part of this UI
![image](https://user-images.githubusercontent.com/1344906/102992893-d6cf9680-4524-11eb-86e8-f1d1ea2d3562.png)

Here's what I have: (The Buttons next to each process look ugly and I want to get rid of them)
![image](https://user-images.githubusercontent.com/1344906/102993122-46de1c80-4525-11eb-8052-e429b47ecf17.png)

On an unrelated note, I'd like to disable the resizing of the SplitLayout, how can I achieve that? (I like the borders it provides, but I don't want the resizability)

**Comment by AllenDang** [comment]
@fr3fou For the click event detection, I added a eventHandler param to TreeNodeV function. You could refer the usage in example/widgets.

To disable resizing of SplitLayout, use giu.Child to create a static panel like below.

```go
g.Line(
  g.Child("Left panel" ...),
  g.Child("Right panel" ...),
)
```

**Comment by fr3fou** [comment]
Thanks for the incredibly quick response! I implemented the latter, but I'm unable to use `TreeNodeV` (I can't update the package, even when using `go get -u`. The compiler keeps telling me that this function doesn't exist.

**Comment by fr3fou** [comment]
Used `go get -u github.com/AllenDang/giu@master` and that fixed it! Thanks!
