### ISSUE TITLE
Attaching a Custom() to a Row()

### ISSUE THREAD

**Issue by neutralinsomniac** [AllenDang/giu#99]
Is it possible/does it make sense to be able to attach a Custom() event handler to a Row() object? It looks like doing a Custom() after a Row() currently attaches the event to the last non-Row object.

**Comment by AllenDang** [comment]
@neutralinsomniac Can you describe more detail about what are you trying to do?

**Comment by neutralinsomniac** [comment]
@AllenDang https://pintobyte.com/tmp/exogiu_explanation.mp4

**Comment by AllenDang** [comment]
@neutralinsomniac I see. There are two approaches in a quick think.
1. Create a new widget from scratch, using canvas apis, to enable display clickable and editable text row.
2. Use TextEditor widget, it's a powerful code editor with syntax highlight and necessary event detections, but need to expose more its internal APIs from cpp side. You could read TextEditor.go and TextEditor.cpp.

In my understanding, you are trying to create a dual-link note system right?

I'm a fan of roam research, :P

I'm willing to provide any necessary assistant, let's make it happen!

**Comment by neutralinsomniac** [comment]
@AllenDang Thank you for your reply. Creating a new custom widget was going to be my next step if something didn't already exist.

You deduced correctly, I'm trying to make a roam research "clone": Repo is [here](https://github.com/neutralinsomniac/exocortex)

The README is a bit out of date. The CLI ([exotui](https://github.com/neutralinsomniac/exocortex/blob/master/cmd/exotui/exotui.go)) is fully functional and compatible with the other frontends I've created (they all use the same backend db code). I attempted a gioui port [here](https://github.com/neutralinsomniac/exocortex/blob/master/cmd/exogio/exogio.go) but stopped because of the lack of text selection in the Editor widget. Your framework has everything I need to make this dream a reality (a tree widget, rich editor, widget drag and drop...). The only thing I haven't seen evidence of is URL clicking support (for when a row has a URL in it), but for now I think that switching to edit mode and manually copying/pasting the URL will suffice.

Anyway, feel free to look at the code/help if you want. I've solo'd this on and off for the past year or so so it's exciting to see someone else with a potential interest in the project :)

**Comment by cgimenez** [comment]
Seems that I've a similar problem - I'm trying to attach a Custom() to a FastTable row like this
```
row := g.Row(
  g.Label(audioFile.pathname),
  g.Custom(func() {
  //	if appCtx.deleteEnabled {
    g.ButtonV("Delete", 100, 20, func() {})
  //}
  }),
 )
rows = append(rows, row)
```

The code inside g.Custom() is executed, but the button is never displayed. I'm missing something for sure ;-)

**Comment by AllenDang** [comment]
@cgimenez I need to invoke g.ButtonV(...).Build() manually.
```go
row := g.Row(
  g.Label(audioFile.pathname),
  g.Custom(func() {
  //	if appCtx.deleteEnabled {
    g.ButtonV("Delete", 100, 20, func() {}).Build()
  //}
  }),
 )
rows = append(rows, row)
```

**Comment by cgimenez** [comment]
Thanks !

BTW, how can I force the width of the FastTable Rows columns ?
In the code above, forcing the width of the g.Label

**Comment by AllenDang** [comment]
@cgimenez Use imgui.SetColumnWidth to set width of column.
